import type { JsonId } from "../types";

export interface ListResponse {
  data: SettlementTransaction[];
  page: number;
  pageSize: number;
  status: "ok";
  total: number;
  totalPages: number;
}

export interface SettlementTransaction {
  businessUnit: null | string;
  cardInitialNumber: null | string;
  couponAmount: null | number;
  description: null | string;
  externalPosId: null | string;
  externalReference: null | string;
  externalStoreId: null | string;
  feeAmount: null | number;
  financingFeeAmount: null | number;
  franchise: null | string;
  id: number;
  installments: null | number;
  invoicingPeriod: null | Date;
  isReleased: boolean | null;
  issuerName: null | string;
  lastFourDigits: null | string;
  metadata: unknown;
  mkpFeeAmount: null | number;
  moneyReleaseDate: null | Date;
  operationTags: unknown;
  orderId: JsonId | null;
  orderMp: null | string;
  packId: JsonId | null;
  payBankTransferId: null | string;
  paymentMethod: null | string;
  paymentMethodType: null | string;
  poiBankName: null | string;
  poiId: null | string;
  poiWalletName: null | string;
  posId: null | string;
  posName: null | string;
  productSku: null | string;
  purchaseId: null | string;
  realAmount: null | number;
  saleDetail: null | string;
  sellerAmount: null | number;
  settlementCurrency: null | string;
  settlementDate: null | Date;
  settlementNetAmount: null | number;
  shipmentMode: null | string;
  shippingFeeAmount: null | number;
  shippingId: JsonId | null;
  shippingOrderId: null | string;
  site: null | string;
  sourceId: string;
  storeId: null | string;
  storeName: null | string;
  subUnit: null | string;
  taxDetail: null | string;
  taxesAmount: null | number;
  taxesDisaggregated: unknown;
  tipAmount: null | number;
  totalCouponAmount: null | number;
  transactionAmount: null | number;
  transactionCurrency: null | string;
  transactionDate: Date;
  transactionIntentId: null | string;
  transactionType: null | string;
  userId: null | string;
}
