import { z } from "zod";

const DecimalValueSchema = z.union([z.number(), z.string(), z.null()]);
const JsonIdSchema = z.union([z.number(), z.string()]).nullable();

export const TransactionSchema = z.strictObject({
  description: z.string().nullable(),
  externalReference: z.string().nullable(),
  id: z.number(),
  paymentMethod: z.string().nullable(),
  settlementNetAmount: z.number().nullable(),
  sourceId: z.string().nullable(),
  status: z.string().nullable(),
  transactionAmount: z.number().nullable(),
  transactionDate: z.string(),
  transactionType: z.string(),
});

export const TransactionsResponseSchema = z.strictObject({
  data: z.array(TransactionSchema),
  hasAmounts: z.boolean().optional(),
  page: z.number().optional(),
  pageSize: z.number().optional(),
  status: z.enum(["error", "ok"]),
  total: z.number().optional(),
  totalPages: z.number().optional(),
});

export const ReleaseTransactionSchema = z.strictObject({
  balanceAmount: DecimalValueSchema,
  businessUnit: z.string().nullable(),
  cardInitialNumber: z.string().nullable(),
  couponAmount: DecimalValueSchema,
  currency: z.string().nullable(),
  date: z.string(),
  description: z.string().nullable(),
  effectiveCouponAmount: DecimalValueSchema,
  externalPosId: z.string().nullable(),
  externalReference: z.string().nullable(),
  externalStoreId: z.string().nullable(),
  financingFeeAmount: DecimalValueSchema,
  franchise: z.string().nullable(),
  grossAmount: DecimalValueSchema,
  id: z.number(),
  installments: z.number().nullable(),
  issuerName: z.string().nullable(),
  itemId: z.string().nullable(),
  lastFourDigits: z.string().nullable(),
  mpFeeAmount: DecimalValueSchema,
  netCreditAmount: DecimalValueSchema,
  netDebitAmount: DecimalValueSchema,
  operationTags: z.unknown(),
  orderId: JsonIdSchema,
  orderMp: z.string().nullable(),
  packId: JsonIdSchema,
  paymentMethod: z.string().nullable(),
  paymentMethodType: z.string().nullable(),
  payoutBankAccountNumber: z.string().nullable(),
  poiBankName: z.string().nullable(),
  poiId: z.string().nullable(),
  poiWalletName: z.string().nullable(),
  posId: z.string().nullable(),
  posName: z.string().nullable(),
  productSku: z.string().nullable(),
  purchaseId: z.string().nullable(),
  recordType: z.string().nullable(),
  saleDetail: z.string().nullable(),
  sellerAmount: DecimalValueSchema,
  shipmentMode: z.string().nullable(),
  shippingFeeAmount: DecimalValueSchema,
  shippingId: JsonIdSchema,
  shippingOrderId: z.string().nullable(),
  sourceId: z.string(),
  storeId: z.string().nullable(),
  storeName: z.string().nullable(),
  subUnit: z.string().nullable(),
  taxAmountTelco: DecimalValueSchema,
  taxDetail: z.string().nullable(),
  taxesAmount: DecimalValueSchema,
  taxesDisaggregated: z.unknown(),
  transactionApprovalDate: z.string().nullable(),
  transactionIntentId: z.string().nullable(),
});

export const ReleaseTransactionsResponseSchema = z.strictObject({
  data: z.array(ReleaseTransactionSchema),
  page: z.number(),
  pageSize: z.number(),
  status: z.literal("ok"),
  total: z.number(),
  totalPages: z.number(),
});

export const SettlementTransactionSchema = z.strictObject({
  businessUnit: z.string().nullable(),
  cardInitialNumber: z.string().nullable(),
  couponAmount: z.number().nullable(),
  description: z.string().nullable(),
  externalPosId: z.string().nullable(),
  externalReference: z.string().nullable(),
  externalStoreId: z.string().nullable(),
  feeAmount: z.number().nullable(),
  financingFeeAmount: z.number().nullable(),
  franchise: z.string().nullable(),
  id: z.number(),
  installments: z.number().nullable(),
  invoicingPeriod: z.string().nullable(),
  isReleased: z.boolean().nullable(),
  issuerName: z.string().nullable(),
  lastFourDigits: z.string().nullable(),
  metadata: z.unknown(),
  mkpFeeAmount: z.number().nullable(),
  moneyReleaseDate: z.string().nullable(),
  operationTags: z.unknown(),
  orderId: JsonIdSchema,
  orderMp: z.string().nullable(),
  packId: JsonIdSchema,
  payBankTransferId: z.string().nullable(),
  paymentMethod: z.string().nullable(),
  paymentMethodType: z.string().nullable(),
  poiBankName: z.string().nullable(),
  poiId: z.string().nullable(),
  poiWalletName: z.string().nullable(),
  posId: z.string().nullable(),
  posName: z.string().nullable(),
  productSku: z.string().nullable(),
  purchaseId: z.string().nullable(),
  realAmount: z.number().nullable(),
  saleDetail: z.string().nullable(),
  sellerAmount: z.number().nullable(),
  settlementCurrency: z.string().nullable(),
  settlementDate: z.string().nullable(),
  settlementNetAmount: z.number().nullable(),
  shipmentMode: z.string().nullable(),
  shippingFeeAmount: z.number().nullable(),
  shippingId: JsonIdSchema,
  shippingOrderId: z.string().nullable(),
  site: z.string().nullable(),
  sourceId: z.string(),
  storeId: z.string().nullable(),
  storeName: z.string().nullable(),
  subUnit: z.string().nullable(),
  taxDetail: z.string().nullable(),
  taxesAmount: z.number().nullable(),
  taxesDisaggregated: z.unknown(),
  tipAmount: z.number().nullable(),
  totalCouponAmount: z.number().nullable(),
  transactionAmount: z.number().nullable(),
  transactionCurrency: z.string().nullable(),
  transactionDate: z.string(),
  transactionIntentId: z.string().nullable(),
  transactionType: z.string().nullable(),
  userId: z.string().nullable(),
});

export const SettlementTransactionsResponseSchema = z.strictObject({
  data: z.array(SettlementTransactionSchema),
  page: z.number(),
  pageSize: z.number(),
  status: z.literal("ok"),
  total: z.number(),
  totalPages: z.number(),
});
