packages:
  - "apps/*"
  - "packages/*"

# pnpm v10 Advantages & Optimizations
verifyDepsBeforeRun: install
optimisticRepeatInstall: true
dedupePeerDependents: true
injectWorkspacePackages: true

# Allow/deny dependency build scripts (pnpm v10+)
allowBuilds:
  argon2: true
  esbuild: true
  prisma: false
  "@prisma/engines": false
  better-sqlite3: false
