export interface SettlementTransaction {
  id: number;
  sourceId: string;
  transactionDate: string;
  settlementDate: string | null;
  moneyReleaseDate: string | null;
  externalReference: string | null;
  userId: string | null;
  paymentMethodType: string | null;
  paymentMethod: string | null;
  site: string | null;
  transactionType: string | null;
  transactionAmount: number | null;
  transactionCurrency: string | null;
  sellerAmount: number | null;
  feeAmount: number | null;
  settlementNetAmount: number | null;
  settlementCurrency: string | null;
  realAmount: number | null;
  couponAmount: number | null;
  metadata: unknown;
  mkpFeeAmount: number | null;
  financingFeeAmount: number | null;
  shippingFeeAmount: number | null;
  taxesAmount: number | null;
  installments: number | null;
  taxDetail: string | null;
  taxesDisaggregated: unknown;
  description: string | null;
  cardInitialNumber: string | null;
  operationTags: unknown;
  businessUnit: string | null;
  subUnit: string | null;
  productSku: string | null;
  saleDetail: string | null;
  transactionIntentId: string | null;
  franchise: string | null;
  issuerName: string | null;
  lastFourDigits: string | null;
  orderMp: string | null;
  invoicingPeriod: string | null;
  payBankTransferId: string | null;
  isReleased: boolean | null;
  tipAmount: number | null;
  purchaseId: string | null;
  totalCouponAmount: number | null;
  posId: string | null;
  posName: string | null;
  externalPosId: string | null;
  storeId: string | null;
  storeName: string | null;
  externalStoreId: string | null;
  poiId: string | null;
  orderId: string | number | bigint | null;
  shippingId: string | number | bigint | null;
  shipmentMode: string | null;
  packId: string | number | bigint | null;
  shippingOrderId: string | null;
  poiWalletName: string | null;
  poiBankName: string | null;
}

export interface ListResponse {
  status: string;
  data: SettlementTransaction[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}
