-- Settlement + Release combined view (FULL OUTER JOIN)
-- ZenStack migration

CREATE OR REPLACE VIEW public.settlement_release_transactions AS
SELECT
  COALESCE(s.source_id, r.source_id) AS row_id,
  COALESCE(s.source_id, r.source_id) AS source_id,
  CASE
    WHEN s.source_id IS NOT NULL AND r.source_id IS NOT NULL THEN 'both'
    WHEN s.source_id IS NOT NULL THEN 'settlement'
    ELSE 'release'
  END AS origin,
  COALESCE(s.transaction_date, r.date) AS effective_date,
  s.id AS settlement_id,
  s.source_id AS settlement_source_id,
  s.transaction_date AS settlement_transaction_date,
  s.settlement_date AS settlement_settlement_date,
  s.money_release_date AS settlement_money_release_date,
  s.external_reference AS settlement_external_reference,
  s.user_id AS settlement_user_id,
  s.payment_method_type AS settlement_payment_method_type,
  s.payment_method AS settlement_payment_method,
  s.site AS settlement_site,
  s.transaction_type AS settlement_transaction_type,
  s.transaction_amount AS settlement_transaction_amount,
  s.transaction_currency AS settlement_transaction_currency,
  s.seller_amount AS settlement_seller_amount,
  s.fee_amount AS settlement_fee_amount,
  s.settlement_net_amount AS settlement_settlement_net_amount,
  s.settlement_currency AS settlement_settlement_currency,
  s.real_amount AS settlement_real_amount,
  s.coupon_amount AS settlement_coupon_amount,
  s.metadata AS settlement_metadata,
  s.mkp_fee_amount AS settlement_mkp_fee_amount,
  s.financing_fee_amount AS settlement_financing_fee_amount,
  s.shipping_fee_amount AS settlement_shipping_fee_amount,
  s.taxes_amount AS settlement_taxes_amount,
  s.installments AS settlement_installments,
  s.tax_detail AS settlement_tax_detail,
  s.taxes_disaggregated AS settlement_taxes_disaggregated,
  s.description AS settlement_description,
  s.card_initial_number AS settlement_card_initial_number,
  s.operation_tags AS settlement_operation_tags,
  s.business_unit AS settlement_business_unit,
  s.sub_unit AS settlement_sub_unit,
  s.product_sku AS settlement_product_sku,
  s.sale_detail AS settlement_sale_detail,
  s.transaction_intent_id AS settlement_transaction_intent_id,
  s.franchise AS settlement_franchise,
  s.issuer_name AS settlement_issuer_name,
  s.last_four_digits AS settlement_last_four_digits,
  s.order_mp AS settlement_order_mp,
  s.invoicing_period AS settlement_invoicing_period,
  s.pay_bank_transfer_id AS settlement_pay_bank_transfer_id,
  s.is_released AS settlement_is_released,
  s.tip_amount AS settlement_tip_amount,
  s.purchase_id AS settlement_purchase_id,
  s.total_coupon_amount AS settlement_total_coupon_amount,
  s.pos_id AS settlement_pos_id,
  s.pos_name AS settlement_pos_name,
  s.external_pos_id AS settlement_external_pos_id,
  s.store_id AS settlement_store_id,
  s.store_name AS settlement_store_name,
  s.external_store_id AS settlement_external_store_id,
  s.poi_id AS settlement_poi_id,
  s.order_id AS settlement_order_id,
  s.shipping_id AS settlement_shipping_id,
  s.shipment_mode AS settlement_shipment_mode,
  s.pack_id AS settlement_pack_id,
  s.shipping_order_id AS settlement_shipping_order_id,
  s.poi_wallet_name AS settlement_poi_wallet_name,
  s.poi_bank_name AS settlement_poi_bank_name,
  s.created_at AS settlement_created_at,
  s.updated_at AS settlement_updated_at,
  r.id AS release_id,
  r.source_id AS release_source_id,
  r.date AS release_date,
  r.external_reference AS release_external_reference,
  r.record_type AS release_record_type,
  r.description AS release_description,
  r.net_credit_amount AS release_net_credit_amount,
  r.net_debit_amount AS release_net_debit_amount,
  r.gross_amount AS release_gross_amount,
  r.seller_amount AS release_seller_amount,
  r.mp_fee_amount AS release_mp_fee_amount,
  r.financing_fee_amount AS release_financing_fee_amount,
  r.shipping_fee_amount AS release_shipping_fee_amount,
  r.taxes_amount AS release_taxes_amount,
  r.coupon_amount AS release_coupon_amount,
  r.effective_coupon_amount AS release_effective_coupon_amount,
  r.balance_amount AS release_balance_amount,
  r.tax_amount_telco AS release_tax_amount_telco,
  r.installments AS release_installments,
  r.payment_method AS release_payment_method,
  r.payment_method_type AS release_payment_method_type,
  r.tax_detail AS release_tax_detail,
  r.taxes_disaggregated AS release_taxes_disaggregated,
  r.transaction_approval_date AS release_transaction_approval_date,
  r.transaction_intent_id AS release_transaction_intent_id,
  r.pos_id AS release_pos_id,
  r.pos_name AS release_pos_name,
  r.external_pos_id AS release_external_pos_id,
  r.store_id AS release_store_id,
  r.store_name AS release_store_name,
  r.external_store_id AS release_external_store_id,
  r.currency AS release_currency,
  r.shipping_id AS release_shipping_id,
  r.shipment_mode AS release_shipment_mode,
  r.shipping_order_id AS release_shipping_order_id,
  r.order_id AS release_order_id,
  r.pack_id AS release_pack_id,
  r.poi_id AS release_poi_id,
  r.item_id AS release_item_id,
  r.metadata AS release_metadata,
  r.card_initial_number AS release_card_initial_number,
  r.operation_tags AS release_operation_tags,
  r.last_four_digits AS release_last_four_digits,
  r.franchise AS release_franchise,
  r.issuer_name AS release_issuer_name,
  r.poi_bank_name AS release_poi_bank_name,
  r.poi_wallet_name AS release_poi_wallet_name,
  r.business_unit AS release_business_unit,
  r.sub_unit AS release_sub_unit,
  r.payout_bank_account_number AS release_payout_bank_account_number,
  r.product_sku AS release_product_sku,
  r.sale_detail AS release_sale_detail,
  r.order_mp AS release_order_mp,
  r.purchase_id AS release_purchase_id,
  r.created_at AS release_created_at,
  r.updated_at AS release_updated_at
FROM public.settlement_transactions s
FULL OUTER JOIN public.release_transactions r
  ON s.source_id = r.source_id;
