//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/orm/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql"
    } as const;
    models = {
        Person: {
            name: "Person",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                rut: {
                    name: "rut",
                    type: "String",
                    unique: true
                },
                names: {
                    name: "names",
                    type: "String"
                },
                fatherName: {
                    name: "fatherName",
                    type: "String",
                    optional: true
                },
                motherName: {
                    name: "motherName",
                    type: "String",
                    optional: true
                },
                email: {
                    name: "email",
                    type: "String",
                    optional: true
                },
                phone: {
                    name: "phone",
                    type: "String",
                    optional: true
                },
                address: {
                    name: "address",
                    type: "String",
                    optional: true
                },
                personType: {
                    name: "personType",
                    type: "PersonType",
                    default: "NATURAL"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                counterpart: {
                    name: "counterpart",
                    type: "Counterpart",
                    optional: true,
                    relation: { opposite: "person" }
                },
                employee: {
                    name: "employee",
                    type: "Employee",
                    optional: true,
                    relation: { opposite: "person" }
                },
                transactions: {
                    name: "transactions",
                    type: "Transaction",
                    array: true,
                    relation: { opposite: "people" }
                },
                user: {
                    name: "user",
                    type: "User",
                    optional: true,
                    relation: { opposite: "person" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                rut: { type: "String" }
            }
        },
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                personId: {
                    name: "personId",
                    type: "Int",
                    unique: true,
                    foreignKeyFor: [
                        "person"
                    ]
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true
                },
                passwordHash: {
                    name: "passwordHash",
                    type: "String",
                    optional: true
                },
                status: {
                    name: "status",
                    type: "UserStatus",
                    default: "PENDING_SETUP"
                },
                mfaSecret: {
                    name: "mfaSecret",
                    type: "String",
                    optional: true
                },
                mfaEnabled: {
                    name: "mfaEnabled",
                    type: "Boolean",
                    default: false
                },
                passkeys: {
                    name: "passkeys",
                    type: "Passkey",
                    array: true,
                    relation: { opposite: "user" }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                mfaEnforced: {
                    name: "mfaEnforced",
                    type: "Boolean",
                    default: true
                },
                auditLogs: {
                    name: "auditLogs",
                    type: "AuditLog",
                    array: true,
                    relation: { opposite: "user" }
                },
                dailyProductionBalances: {
                    name: "dailyProductionBalances",
                    type: "DailyProductionBalance",
                    array: true,
                    relation: { opposite: "user" }
                },
                pushSubscriptions: {
                    name: "pushSubscriptions",
                    type: "PushSubscription",
                    array: true,
                    relation: { opposite: "user" }
                },
                supplyRequests: {
                    name: "supplyRequests",
                    type: "SupplyRequest",
                    array: true,
                    relation: { opposite: "user" }
                },
                permissionVersion: {
                    name: "permissionVersion",
                    type: "UserPermissionVersion",
                    optional: true,
                    relation: { opposite: "user" }
                },
                roles: {
                    name: "roles",
                    type: "UserRoleAssignment",
                    array: true,
                    relation: { opposite: "user" }
                },
                person: {
                    name: "person",
                    type: "Person",
                    relation: { opposite: "user", fields: ["personId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                personId: { type: "Int" },
                email: { type: "String" }
            }
        },
        Passkey: {
            name: "Passkey",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("cuid")
                },
                userId: {
                    name: "userId",
                    type: "Int",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                credentialId: {
                    name: "credentialId",
                    type: "String",
                    unique: true
                },
                publicKey: {
                    name: "publicKey",
                    type: "Bytes"
                },
                counter: {
                    name: "counter",
                    type: "BigInt",
                    default: 0
                },
                transports: {
                    name: "transports",
                    type: "Json",
                    optional: true
                },
                webAuthnUserID: {
                    name: "webAuthnUserID",
                    type: "String"
                },
                deviceType: {
                    name: "deviceType",
                    type: "String"
                },
                backedUp: {
                    name: "backedUp",
                    type: "Boolean",
                    default: false
                },
                friendlyName: {
                    name: "friendlyName",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                lastUsedAt: {
                    name: "lastUsedAt",
                    type: "DateTime",
                    optional: true
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "passkeys", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                credentialId: { type: "String" }
            }
        },
        Role: {
            name: "Role",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                name: {
                    name: "name",
                    type: "String",
                    unique: true
                },
                description: {
                    name: "description",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                isSystem: {
                    name: "isSystem",
                    type: "Boolean",
                    default: false
                },
                permissions: {
                    name: "permissions",
                    type: "RolePermission",
                    array: true,
                    relation: { opposite: "role" }
                },
                users: {
                    name: "users",
                    type: "UserRoleAssignment",
                    array: true,
                    relation: { opposite: "role" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                name: { type: "String" }
            }
        },
        Permission: {
            name: "Permission",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                action: {
                    name: "action",
                    type: "String"
                },
                subject: {
                    name: "subject",
                    type: "String"
                },
                description: {
                    name: "description",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                roles: {
                    name: "roles",
                    type: "RolePermission",
                    array: true,
                    relation: { opposite: "permission" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                action_subject: { action: { type: "String" }, subject: { type: "String" } }
            }
        },
        RolePermission: {
            name: "RolePermission",
            fields: {
                roleId: {
                    name: "roleId",
                    type: "Int",
                    id: true,
                    foreignKeyFor: [
                        "role"
                    ]
                },
                permissionId: {
                    name: "permissionId",
                    type: "Int",
                    id: true,
                    foreignKeyFor: [
                        "permission"
                    ]
                },
                conditions: {
                    name: "conditions",
                    type: "Json",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                permission: {
                    name: "permission",
                    type: "Permission",
                    relation: { opposite: "roles", fields: ["permissionId"], references: ["id"], onDelete: "Cascade" }
                },
                role: {
                    name: "role",
                    type: "Role",
                    relation: { opposite: "permissions", fields: ["roleId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["roleId", "permissionId"],
            uniqueFields: {
                roleId_permissionId: { roleId: { type: "Int" }, permissionId: { type: "Int" } }
            }
        },
        UserRoleAssignment: {
            name: "UserRoleAssignment",
            fields: {
                userId: {
                    name: "userId",
                    type: "Int",
                    id: true,
                    foreignKeyFor: [
                        "user"
                    ]
                },
                roleId: {
                    name: "roleId",
                    type: "Int",
                    id: true,
                    foreignKeyFor: [
                        "role"
                    ]
                },
                assignedAt: {
                    name: "assignedAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                role: {
                    name: "role",
                    type: "Role",
                    relation: { opposite: "users", fields: ["roleId"], references: ["id"], onDelete: "Cascade" }
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "roles", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["userId", "roleId"],
            uniqueFields: {
                userId_roleId: { userId: { type: "Int" }, roleId: { type: "Int" } }
            }
        },
        UserPermissionVersion: {
            name: "UserPermissionVersion",
            fields: {
                userId: {
                    name: "userId",
                    type: "Int",
                    id: true,
                    foreignKeyFor: [
                        "user"
                    ]
                },
                version: {
                    name: "version",
                    type: "Int",
                    default: 1
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "permissionVersion", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["userId"],
            uniqueFields: {
                userId: { type: "Int" }
            }
        },
        Employee: {
            name: "Employee",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                personId: {
                    name: "personId",
                    type: "Int",
                    unique: true,
                    foreignKeyFor: [
                        "person"
                    ]
                },
                position: {
                    name: "position",
                    type: "String"
                },
                department: {
                    name: "department",
                    type: "String",
                    optional: true
                },
                startDate: {
                    name: "startDate",
                    type: "DateTime"
                },
                endDate: {
                    name: "endDate",
                    type: "DateTime",
                    optional: true
                },
                status: {
                    name: "status",
                    type: "EmployeeStatus",
                    default: "ACTIVE"
                },
                salaryType: {
                    name: "salaryType",
                    type: "EmployeeSalaryType",
                    default: "FIXED"
                },
                baseSalary: {
                    name: "baseSalary",
                    type: "Decimal",
                    default: 0
                },
                hourlyRate: {
                    name: "hourlyRate",
                    type: "Decimal",
                    optional: true
                },
                bankName: {
                    name: "bankName",
                    type: "String",
                    optional: true
                },
                bankAccountType: {
                    name: "bankAccountType",
                    type: "String",
                    optional: true
                },
                bankAccountNumber: {
                    name: "bankAccountNumber",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                metadata: {
                    name: "metadata",
                    type: "Json",
                    optional: true
                },
                overtimeRate: {
                    name: "overtimeRate",
                    type: "Decimal",
                    optional: true
                },
                retentionRate: {
                    name: "retentionRate",
                    type: "Decimal",
                    default: 0.145
                },
                timesheets: {
                    name: "timesheets",
                    type: "EmployeeTimesheet",
                    array: true,
                    relation: { opposite: "employee" }
                },
                person: {
                    name: "person",
                    type: "Person",
                    relation: { opposite: "employee", fields: ["personId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                personId: { type: "Int" }
            }
        },
        Counterpart: {
            name: "Counterpart",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                personId: {
                    name: "personId",
                    type: "Int",
                    unique: true,
                    foreignKeyFor: [
                        "person"
                    ]
                },
                category: {
                    name: "category",
                    type: "CounterpartCategory",
                    default: "SUPPLIER"
                },
                notes: {
                    name: "notes",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                accounts: {
                    name: "accounts",
                    type: "CounterpartAccount",
                    array: true,
                    relation: { opposite: "counterpart" }
                },
                person: {
                    name: "person",
                    type: "Person",
                    relation: { opposite: "counterpart", fields: ["personId"], references: ["id"], onDelete: "Cascade" }
                },
                services: {
                    name: "services",
                    type: "Service",
                    array: true,
                    relation: { opposite: "counterpart" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                personId: { type: "Int" }
            }
        },
        CounterpartAccount: {
            name: "CounterpartAccount",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                counterpartId: {
                    name: "counterpartId",
                    type: "Int",
                    foreignKeyFor: [
                        "counterpart"
                    ]
                },
                bankName: {
                    name: "bankName",
                    type: "String",
                    optional: true
                },
                accountType: {
                    name: "accountType",
                    type: "String",
                    optional: true
                },
                accountNumber: {
                    name: "accountNumber",
                    type: "String"
                },
                counterpart: {
                    name: "counterpart",
                    type: "Counterpart",
                    relation: { opposite: "accounts", fields: ["counterpartId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        },
        EmployeeTimesheet: {
            name: "EmployeeTimesheet",
            fields: {
                id: {
                    name: "id",
                    type: "BigInt",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                employeeId: {
                    name: "employeeId",
                    type: "Int",
                    foreignKeyFor: [
                        "employee"
                    ]
                },
                workDate: {
                    name: "workDate",
                    type: "DateTime"
                },
                startTime: {
                    name: "startTime",
                    type: "DateTime",
                    optional: true
                },
                endTime: {
                    name: "endTime",
                    type: "DateTime",
                    optional: true
                },
                workedMinutes: {
                    name: "workedMinutes",
                    type: "Int"
                },
                overtimeMinutes: {
                    name: "overtimeMinutes",
                    type: "Int",
                    default: 0
                },
                comment: {
                    name: "comment",
                    type: "String",
                    optional: true
                },
                employee: {
                    name: "employee",
                    type: "Employee",
                    relation: { opposite: "timesheets", fields: ["employeeId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "BigInt" },
                employeeId_workDate: { employeeId: { type: "Int" }, workDate: { type: "DateTime" } }
            }
        },
        Transaction: {
            name: "Transaction",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                description: {
                    name: "description",
                    type: "String",
                    optional: true
                },
                person_id: {
                    name: "person_id",
                    type: "Int",
                    optional: true,
                    foreignKeyFor: [
                        "people"
                    ]
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                businessUnit: {
                    name: "businessUnit",
                    type: "String",
                    optional: true
                },
                cardInitialNumber: {
                    name: "cardInitialNumber",
                    type: "String",
                    optional: true
                },
                couponAmount: {
                    name: "couponAmount",
                    type: "Decimal",
                    optional: true
                },
                externalPosId: {
                    name: "externalPosId",
                    type: "String",
                    optional: true
                },
                externalReference: {
                    name: "externalReference",
                    type: "String",
                    optional: true
                },
                externalStoreId: {
                    name: "externalStoreId",
                    type: "String",
                    optional: true
                },
                feeAmount: {
                    name: "feeAmount",
                    type: "Decimal",
                    optional: true
                },
                financingFeeAmount: {
                    name: "financingFeeAmount",
                    type: "Decimal",
                    optional: true
                },
                franchise: {
                    name: "franchise",
                    type: "String",
                    optional: true
                },
                installments: {
                    name: "installments",
                    type: "Int",
                    optional: true
                },
                invoicingPeriod: {
                    name: "invoicingPeriod",
                    type: "String",
                    optional: true
                },
                isReleased: {
                    name: "isReleased",
                    type: "Boolean",
                    optional: true
                },
                issuerName: {
                    name: "issuerName",
                    type: "String",
                    optional: true
                },
                lastFourDigits: {
                    name: "lastFourDigits",
                    type: "String",
                    optional: true
                },
                metadata: {
                    name: "metadata",
                    type: "Json",
                    optional: true
                },
                mkpFeeAmount: {
                    name: "mkpFeeAmount",
                    type: "Decimal",
                    optional: true
                },
                moneyReleaseDate: {
                    name: "moneyReleaseDate",
                    type: "DateTime",
                    optional: true
                },
                operationTags: {
                    name: "operationTags",
                    type: "Json",
                    optional: true
                },
                orderId: {
                    name: "orderId",
                    type: "BigInt",
                    optional: true
                },
                orderMp: {
                    name: "orderMp",
                    type: "String",
                    optional: true
                },
                packId: {
                    name: "packId",
                    type: "BigInt",
                    optional: true
                },
                payBankTransferId: {
                    name: "payBankTransferId",
                    type: "String",
                    optional: true
                },
                paymentMethod: {
                    name: "paymentMethod",
                    type: "String",
                    optional: true
                },
                paymentMethodType: {
                    name: "paymentMethodType",
                    type: "String",
                    optional: true
                },
                poiBankName: {
                    name: "poiBankName",
                    type: "String",
                    optional: true
                },
                poiId: {
                    name: "poiId",
                    type: "String",
                    optional: true
                },
                poiWalletName: {
                    name: "poiWalletName",
                    type: "String",
                    optional: true
                },
                posId: {
                    name: "posId",
                    type: "String",
                    optional: true
                },
                posName: {
                    name: "posName",
                    type: "String",
                    optional: true
                },
                productSku: {
                    name: "productSku",
                    type: "String",
                    optional: true
                },
                purchaseId: {
                    name: "purchaseId",
                    type: "String",
                    optional: true
                },
                realAmount: {
                    name: "realAmount",
                    type: "Decimal",
                    optional: true
                },
                saleDetail: {
                    name: "saleDetail",
                    type: "String",
                    optional: true
                },
                sellerAmount: {
                    name: "sellerAmount",
                    type: "Decimal",
                    optional: true
                },
                settlementCurrency: {
                    name: "settlementCurrency",
                    type: "String",
                    optional: true
                },
                settlementDate: {
                    name: "settlementDate",
                    type: "DateTime",
                    optional: true
                },
                settlementNetAmount: {
                    name: "settlementNetAmount",
                    type: "Decimal",
                    optional: true
                },
                shipmentMode: {
                    name: "shipmentMode",
                    type: "String",
                    optional: true
                },
                shippingFeeAmount: {
                    name: "shippingFeeAmount",
                    type: "Decimal",
                    optional: true
                },
                shippingId: {
                    name: "shippingId",
                    type: "BigInt",
                    optional: true
                },
                shippingOrderId: {
                    name: "shippingOrderId",
                    type: "String",
                    optional: true
                },
                site: {
                    name: "site",
                    type: "String",
                    optional: true
                },
                sourceId: {
                    name: "sourceId",
                    type: "String",
                    optional: true
                },
                status: {
                    name: "status",
                    type: "String",
                    optional: true
                },
                storeId: {
                    name: "storeId",
                    type: "String",
                    optional: true
                },
                storeName: {
                    name: "storeName",
                    type: "String",
                    optional: true
                },
                subUnit: {
                    name: "subUnit",
                    type: "String",
                    optional: true
                },
                taxDetail: {
                    name: "taxDetail",
                    type: "String",
                    optional: true
                },
                taxesAmount: {
                    name: "taxesAmount",
                    type: "Decimal",
                    optional: true
                },
                taxesDisaggregated: {
                    name: "taxesDisaggregated",
                    type: "Json",
                    optional: true
                },
                tipAmount: {
                    name: "tipAmount",
                    type: "Decimal",
                    optional: true
                },
                totalCouponAmount: {
                    name: "totalCouponAmount",
                    type: "Decimal",
                    optional: true
                },
                transactionAmount: {
                    name: "transactionAmount",
                    type: "Decimal"
                },
                transactionCurrency: {
                    name: "transactionCurrency",
                    type: "String"
                },
                transactionDate: {
                    name: "transactionDate",
                    type: "DateTime"
                },
                transactionIntentId: {
                    name: "transactionIntentId",
                    type: "String",
                    optional: true
                },
                transactionType: {
                    name: "transactionType",
                    type: "String"
                },
                userId: {
                    name: "userId",
                    type: "String",
                    optional: true
                },
                people: {
                    name: "people",
                    type: "Person",
                    optional: true,
                    relation: { opposite: "transactions", fields: ["person_id"], references: ["id"] }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                sourceId_transactionType: { sourceId: { type: "String" }, transactionType: { type: "String" } }
            }
        },
        DailyBalance: {
            name: "DailyBalance",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                date: {
                    name: "date",
                    type: "DateTime",
                    unique: true
                },
                amount: {
                    name: "amount",
                    type: "Decimal"
                },
                note: {
                    name: "note",
                    type: "String",
                    optional: true
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                date: { type: "DateTime" }
            }
        },
        Service: {
            name: "Service",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                name: {
                    name: "name",
                    type: "String"
                },
                counterpartId: {
                    name: "counterpartId",
                    type: "Int",
                    optional: true,
                    foreignKeyFor: [
                        "counterpart"
                    ]
                },
                type: {
                    name: "type",
                    type: "ServiceType",
                    default: "BUSINESS"
                },
                frequency: {
                    name: "frequency",
                    type: "ServiceFrequency",
                    default: "MONTHLY"
                },
                defaultAmount: {
                    name: "defaultAmount",
                    type: "Decimal",
                    default: 0
                },
                status: {
                    name: "status",
                    type: "ServiceStatus",
                    default: "ACTIVE"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                counterpart: {
                    name: "counterpart",
                    type: "Counterpart",
                    optional: true,
                    relation: { opposite: "services", fields: ["counterpartId"], references: ["id"] }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        },
        Loan: {
            name: "Loan",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                title: {
                    name: "title",
                    type: "String"
                },
                principalAmount: {
                    name: "principalAmount",
                    type: "Decimal"
                },
                interestRate: {
                    name: "interestRate",
                    type: "Decimal"
                },
                startDate: {
                    name: "startDate",
                    type: "DateTime"
                },
                status: {
                    name: "status",
                    type: "LoanStatus",
                    default: "ACTIVE"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                schedules: {
                    name: "schedules",
                    type: "LoanSchedule",
                    array: true,
                    relation: { opposite: "loan" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        },
        LoanSchedule: {
            name: "LoanSchedule",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                loanId: {
                    name: "loanId",
                    type: "Int",
                    foreignKeyFor: [
                        "loan"
                    ]
                },
                installmentNumber: {
                    name: "installmentNumber",
                    type: "Int"
                },
                dueDate: {
                    name: "dueDate",
                    type: "DateTime"
                },
                expectedAmount: {
                    name: "expectedAmount",
                    type: "Decimal"
                },
                status: {
                    name: "status",
                    type: "LoanScheduleStatus",
                    default: "PENDING"
                },
                loan: {
                    name: "loan",
                    type: "Loan",
                    relation: { opposite: "schedules", fields: ["loanId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        },
        AuditLog: {
            name: "AuditLog",
            fields: {
                id: {
                    name: "id",
                    type: "BigInt",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                userId: {
                    name: "userId",
                    type: "Int",
                    optional: true,
                    foreignKeyFor: [
                        "user"
                    ]
                },
                action: {
                    name: "action",
                    type: "String"
                },
                entity: {
                    name: "entity",
                    type: "String"
                },
                entityId: {
                    name: "entityId",
                    type: "String",
                    optional: true
                },
                details: {
                    name: "details",
                    type: "Json",
                    optional: true
                },
                ipAddress: {
                    name: "ipAddress",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                user: {
                    name: "user",
                    type: "User",
                    optional: true,
                    relation: { opposite: "auditLogs", fields: ["userId"], references: ["id"] }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "BigInt" }
            }
        },
        Setting: {
            name: "Setting",
            fields: {
                key: {
                    name: "key",
                    type: "String",
                    id: true
                },
                value: {
                    name: "value",
                    type: "String",
                    optional: true
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                }
            },
            idFields: ["key"],
            uniqueFields: {
                key: { type: "String" }
            }
        },
        PushSubscription: {
            name: "PushSubscription",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                userId: {
                    name: "userId",
                    type: "Int",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                endpoint: {
                    name: "endpoint",
                    type: "String",
                    unique: true
                },
                keys: {
                    name: "keys",
                    type: "Json"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "pushSubscriptions", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                endpoint: { type: "String" }
            }
        },
        Calendar: {
            name: "Calendar",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                googleId: {
                    name: "googleId",
                    type: "String",
                    unique: true
                },
                name: {
                    name: "name",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                watchChannels: {
                    name: "watchChannels",
                    type: "CalendarWatchChannel",
                    array: true,
                    relation: { opposite: "calendar" }
                },
                events: {
                    name: "events",
                    type: "Event",
                    array: true,
                    relation: { opposite: "calendar" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                googleId: { type: "String" }
            }
        },
        CalendarWatchChannel: {
            name: "CalendarWatchChannel",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                calendarId: {
                    name: "calendarId",
                    type: "Int",
                    foreignKeyFor: [
                        "calendar"
                    ]
                },
                channelId: {
                    name: "channelId",
                    type: "String",
                    unique: true
                },
                resourceId: {
                    name: "resourceId",
                    type: "String"
                },
                expiration: {
                    name: "expiration",
                    type: "DateTime"
                },
                webhookUrl: {
                    name: "webhookUrl",
                    type: "String"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                calendar: {
                    name: "calendar",
                    type: "Calendar",
                    relation: { opposite: "watchChannels", fields: ["calendarId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                channelId: { type: "String" }
            }
        },
        Event: {
            name: "Event",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                calendarId: {
                    name: "calendarId",
                    type: "Int",
                    foreignKeyFor: [
                        "calendar"
                    ]
                },
                externalEventId: {
                    name: "externalEventId",
                    type: "String"
                },
                eventStatus: {
                    name: "eventStatus",
                    type: "String",
                    optional: true
                },
                eventType: {
                    name: "eventType",
                    type: "String",
                    optional: true
                },
                summary: {
                    name: "summary",
                    type: "String",
                    optional: true
                },
                description: {
                    name: "description",
                    type: "String",
                    optional: true
                },
                startDate: {
                    name: "startDate",
                    type: "DateTime",
                    optional: true
                },
                startDateTime: {
                    name: "startDateTime",
                    type: "DateTime",
                    optional: true
                },
                startTimeZone: {
                    name: "startTimeZone",
                    type: "String",
                    optional: true
                },
                endDate: {
                    name: "endDate",
                    type: "DateTime",
                    optional: true
                },
                endDateTime: {
                    name: "endDateTime",
                    type: "DateTime",
                    optional: true
                },
                endTimeZone: {
                    name: "endTimeZone",
                    type: "String",
                    optional: true
                },
                eventCreatedAt: {
                    name: "eventCreatedAt",
                    type: "DateTime",
                    optional: true
                },
                eventUpdatedAt: {
                    name: "eventUpdatedAt",
                    type: "DateTime",
                    optional: true
                },
                colorId: {
                    name: "colorId",
                    type: "String",
                    optional: true
                },
                location: {
                    name: "location",
                    type: "String",
                    optional: true
                },
                transparency: {
                    name: "transparency",
                    type: "String",
                    optional: true
                },
                visibility: {
                    name: "visibility",
                    type: "String",
                    optional: true
                },
                hangoutLink: {
                    name: "hangoutLink",
                    type: "String",
                    optional: true
                },
                category: {
                    name: "category",
                    type: "String",
                    optional: true
                },
                amountExpected: {
                    name: "amountExpected",
                    type: "Int",
                    optional: true
                },
                amountPaid: {
                    name: "amountPaid",
                    type: "Int",
                    optional: true
                },
                attended: {
                    name: "attended",
                    type: "Boolean",
                    optional: true
                },
                dosage: {
                    name: "dosage",
                    type: "String",
                    optional: true
                },
                treatmentStage: {
                    name: "treatmentStage",
                    type: "String",
                    optional: true
                },
                rawEvent: {
                    name: "rawEvent",
                    type: "Json",
                    optional: true
                },
                lastSyncedAt: {
                    name: "lastSyncedAt",
                    type: "DateTime"
                },
                calendar: {
                    name: "calendar",
                    type: "Calendar",
                    relation: { opposite: "events", fields: ["calendarId"], references: ["id"] }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                calendarId_externalEventId: { calendarId: { type: "Int" }, externalEventId: { type: "String" } }
            }
        },
        SyncLog: {
            name: "SyncLog",
            fields: {
                id: {
                    name: "id",
                    type: "BigInt",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                triggerSource: {
                    name: "triggerSource",
                    type: "String"
                },
                triggerUserId: {
                    name: "triggerUserId",
                    type: "Int",
                    optional: true
                },
                triggerLabel: {
                    name: "triggerLabel",
                    type: "String",
                    optional: true
                },
                status: {
                    name: "status",
                    type: "String",
                    default: "SUCCESS"
                },
                startedAt: {
                    name: "startedAt",
                    type: "DateTime"
                },
                finishedAt: {
                    name: "finishedAt",
                    type: "DateTime",
                    optional: true
                },
                fetchedAt: {
                    name: "fetchedAt",
                    type: "DateTime",
                    optional: true
                },
                inserted: {
                    name: "inserted",
                    type: "Int",
                    optional: true,
                    default: 0
                },
                updated: {
                    name: "updated",
                    type: "Int",
                    optional: true,
                    default: 0
                },
                skipped: {
                    name: "skipped",
                    type: "Int",
                    optional: true,
                    default: 0
                },
                excluded: {
                    name: "excluded",
                    type: "Int",
                    optional: true,
                    default: 0
                },
                errorMessage: {
                    name: "errorMessage",
                    type: "String",
                    optional: true
                },
                changeDetails: {
                    name: "changeDetails",
                    type: "Json",
                    optional: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "BigInt" }
            }
        },
        BackupLog: {
            name: "BackupLog",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                timestamp: {
                    name: "timestamp",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                level: {
                    name: "level",
                    type: "String"
                },
                message: {
                    name: "message",
                    type: "String"
                },
                context: {
                    name: "context",
                    type: "Json",
                    optional: true
                },
                jobId: {
                    name: "jobId",
                    type: "String",
                    optional: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        InventoryCategory: {
            name: "InventoryCategory",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                name: {
                    name: "name",
                    type: "String",
                    unique: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                items: {
                    name: "items",
                    type: "InventoryItem",
                    array: true,
                    relation: { opposite: "category" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                name: { type: "String" }
            }
        },
        InventoryItem: {
            name: "InventoryItem",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                categoryId: {
                    name: "categoryId",
                    type: "Int",
                    optional: true,
                    foreignKeyFor: [
                        "category"
                    ]
                },
                name: {
                    name: "name",
                    type: "String"
                },
                description: {
                    name: "description",
                    type: "String",
                    optional: true
                },
                currentStock: {
                    name: "currentStock",
                    type: "Int",
                    default: 0
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                category: {
                    name: "category",
                    type: "InventoryCategory",
                    optional: true,
                    relation: { opposite: "items", fields: ["categoryId"], references: ["id"] }
                },
                movements: {
                    name: "movements",
                    type: "InventoryMovement",
                    array: true,
                    relation: { opposite: "item" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        },
        InventoryMovement: {
            name: "InventoryMovement",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                itemId: {
                    name: "itemId",
                    type: "Int",
                    foreignKeyFor: [
                        "item"
                    ]
                },
                quantityChange: {
                    name: "quantityChange",
                    type: "Int"
                },
                reason: {
                    name: "reason",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                item: {
                    name: "item",
                    type: "InventoryItem",
                    relation: { opposite: "movements", fields: ["itemId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        },
        DailyProductionBalance: {
            name: "DailyProductionBalance",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                balanceDate: {
                    name: "balanceDate",
                    type: "DateTime",
                    unique: true
                },
                ingresoTarjetas: {
                    name: "ingresoTarjetas",
                    type: "Int",
                    default: 0
                },
                ingresoTransferencias: {
                    name: "ingresoTransferencias",
                    type: "Int",
                    default: 0
                },
                ingresoEfectivo: {
                    name: "ingresoEfectivo",
                    type: "Int",
                    default: 0
                },
                gastosDiarios: {
                    name: "gastosDiarios",
                    type: "Int",
                    default: 0
                },
                otrosAbonos: {
                    name: "otrosAbonos",
                    type: "Int",
                    default: 0
                },
                comentarios: {
                    name: "comentarios",
                    type: "String",
                    optional: true
                },
                status: {
                    name: "status",
                    type: "String",
                    default: "DRAFT"
                },
                changeReason: {
                    name: "changeReason",
                    type: "String",
                    optional: true
                },
                createdBy: {
                    name: "createdBy",
                    type: "Int",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                consultasMonto: {
                    name: "consultasMonto",
                    type: "Int",
                    default: 0
                },
                controlesMonto: {
                    name: "controlesMonto",
                    type: "Int",
                    default: 0
                },
                licenciasMonto: {
                    name: "licenciasMonto",
                    type: "Int",
                    default: 0
                },
                roxairMonto: {
                    name: "roxairMonto",
                    type: "Int",
                    default: 0
                },
                testsMonto: {
                    name: "testsMonto",
                    type: "Int",
                    default: 0
                },
                vacunasMonto: {
                    name: "vacunasMonto",
                    type: "Int",
                    default: 0
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "dailyProductionBalances", fields: ["createdBy"], references: ["id"] }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                balanceDate: { type: "DateTime" }
            }
        },
        SupplyRequest: {
            name: "SupplyRequest",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                userId: {
                    name: "userId",
                    type: "Int",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                supplyName: {
                    name: "supplyName",
                    type: "String"
                },
                quantity: {
                    name: "quantity",
                    type: "Int"
                },
                brand: {
                    name: "brand",
                    type: "String",
                    optional: true
                },
                model: {
                    name: "model",
                    type: "String",
                    optional: true
                },
                notes: {
                    name: "notes",
                    type: "String",
                    optional: true
                },
                status: {
                    name: "status",
                    type: "String",
                    default: "PENDING"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "supplyRequests", fields: ["userId"], references: ["id"] }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        },
        CommonSupply: {
            name: "CommonSupply",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                name: {
                    name: "name",
                    type: "String"
                },
                brand: {
                    name: "brand",
                    type: "String",
                    optional: true
                },
                model: {
                    name: "model",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                name_brand_model: { name: { type: "String" }, brand: { type: "String" }, model: { type: "String" } }
            }
        },
        CalendarSyncLog: {
            name: "CalendarSyncLog",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                startedAt: {
                    name: "startedAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                endedAt: {
                    name: "endedAt",
                    type: "DateTime",
                    optional: true
                },
                status: {
                    name: "status",
                    type: "String"
                },
                eventsSynced: {
                    name: "eventsSynced",
                    type: "Int",
                    default: 0
                },
                eventsInserted: {
                    name: "eventsInserted",
                    type: "Int",
                    default: 0
                },
                eventsUpdated: {
                    name: "eventsUpdated",
                    type: "Int",
                    default: 0
                },
                eventsSkipped: {
                    name: "eventsSkipped",
                    type: "Int",
                    default: 0
                },
                eventsExcluded: {
                    name: "eventsExcluded",
                    type: "Int",
                    default: 0
                },
                errorMessage: {
                    name: "errorMessage",
                    type: "String",
                    optional: true
                },
                triggerSource: {
                    name: "triggerSource",
                    type: "String",
                    optional: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        }
    } as const;
    enums = {
        PersonType: {
            values: {
                NATURAL: "NATURAL",
                JURIDICAL: "JURIDICAL"
            }
        },
        CounterpartCategory: {
            values: {
                SUPPLIER: "SUPPLIER",
                PATIENT: "PATIENT",
                EMPLOYEE: "EMPLOYEE",
                PARTNER: "PARTNER",
                RELATED: "RELATED",
                OTHER: "OTHER",
                CLIENT: "CLIENT",
                LENDER: "LENDER",
                OCCASIONAL: "OCCASIONAL"
            }
        },
        EmployeeStatus: {
            values: {
                ACTIVE: "ACTIVE",
                INACTIVE: "INACTIVE",
                TERMINATED: "TERMINATED"
            }
        },
        EmployeeSalaryType: {
            values: {
                HOURLY: "HOURLY",
                FIXED: "FIXED"
            }
        },
        TransactionDirection: {
            values: {
                IN: "IN",
                OUT: "OUT",
                NEUTRO: "NEUTRO"
            }
        },
        ServiceType: {
            values: {
                BUSINESS: "BUSINESS",
                PERSONAL: "PERSONAL",
                SUPPLIER: "SUPPLIER",
                TAX: "TAX",
                UTILITY: "UTILITY",
                LEASE: "LEASE",
                SOFTWARE: "SOFTWARE",
                OTHER: "OTHER"
            }
        },
        ServiceFrequency: {
            values: {
                WEEKLY: "WEEKLY",
                BIWEEKLY: "BIWEEKLY",
                MONTHLY: "MONTHLY",
                BIMONTHLY: "BIMONTHLY",
                QUARTERLY: "QUARTERLY",
                SEMIANNUAL: "SEMIANNUAL",
                ANNUAL: "ANNUAL",
                ONCE: "ONCE"
            }
        },
        ServiceStatus: {
            values: {
                ACTIVE: "ACTIVE",
                INACTIVE: "INACTIVE",
                ARCHIVED: "ARCHIVED"
            }
        },
        LoanStatus: {
            values: {
                ACTIVE: "ACTIVE",
                COMPLETED: "COMPLETED",
                DEFAULTED: "DEFAULTED"
            }
        },
        LoanScheduleStatus: {
            values: {
                PENDING: "PENDING",
                PARTIAL: "PARTIAL",
                PAID: "PAID",
                OVERDUE: "OVERDUE"
            }
        },
        UserStatus: {
            values: {
                PENDING_SETUP: "PENDING_SETUP",
                ACTIVE: "ACTIVE",
                SUSPENDED: "SUSPENDED"
            }
        }
    } as const;
    authType = "User" as const;
    plugins = {};
}
export const schema = new SchemaType();
