/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as OnboardingRouteImport } from "./routes/onboarding"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AuthedRouteImport } from "./routes/_authed"
import { Route as AuthedIndexRouteImport } from "./routes/_authed/index"
import { Route as VerifyIdRouteImport } from "./routes/verify.$id"
import { Route as AuthedWaCloudRouteImport } from "./routes/_authed/wa-cloud"
import { Route as AuthedSettingsRouteImport } from "./routes/_authed/settings"
import { Route as AuthedServicesRouteImport } from "./routes/_authed/services"
import { Route as AuthedOutreachRouteImport } from "./routes/_authed/outreach"
import { Route as AuthedOperationsRouteImport } from "./routes/_authed/operations"
import { Route as AuthedMarcarRouteImport } from "./routes/_authed/marcar"
import { Route as AuthedHrRouteImport } from "./routes/_authed/hr"
import { Route as AuthedFinanzasRouteImport } from "./routes/_authed/finanzas"
import { Route as AuthedClinicalRouteImport } from "./routes/_authed/clinical"
import { Route as AuthedCertificatesRouteImport } from "./routes/_authed/certificates"
import { Route as AuthedCalendarRouteImport } from "./routes/_authed/calendar"
import { Route as AuthedAccountRouteImport } from "./routes/_authed/account"
import { Route as AuthedWaCloudIndexRouteImport } from "./routes/_authed/wa-cloud/index"
import { Route as AuthedSettingsIndexRouteImport } from "./routes/_authed/settings/index"
import { Route as AuthedServicesIndexRouteImport } from "./routes/_authed/services/index"
import { Route as AuthedPatientsIndexRouteImport } from "./routes/_authed/patients/index"
import { Route as AuthedOutreachIndexRouteImport } from "./routes/_authed/outreach/index"
import { Route as AuthedHrIndexRouteImport } from "./routes/_authed/hr/index"
import { Route as AuthedExamReportsIndexRouteImport } from "./routes/_authed/exam-reports/index"
import { Route as AuthedClinicalIndexRouteImport } from "./routes/_authed/clinical/index"
import { Route as AuthedWaCloudWebhooksRouteImport } from "./routes/_authed/wa-cloud/webhooks"
import { Route as AuthedWaCloudProgramadosRouteImport } from "./routes/_authed/wa-cloud/programados"
import { Route as AuthedWaCloudPlantillasRouteImport } from "./routes/_authed/wa-cloud/plantillas"
import { Route as AuthedWaCloudConfiguracionRouteImport } from "./routes/_authed/wa-cloud/configuracion"
import { Route as AuthedWaCloudCatalogoRouteImport } from "./routes/_authed/wa-cloud/catalogo"
import { Route as AuthedWaCloudBuscarRouteImport } from "./routes/_authed/wa-cloud/buscar"
import { Route as AuthedWaCloudBroadcastsRouteImport } from "./routes/_authed/wa-cloud/broadcasts"
import { Route as AuthedWaCloudAnalyticsRouteImport } from "./routes/_authed/wa-cloud/analytics"
import { Route as AuthedWaCloudAlertasRouteImport } from "./routes/_authed/wa-cloud/alertas"
import { Route as AuthedSettingsTiendaRouteImport } from "./routes/_authed/settings/tienda"
import { Route as AuthedSettingsRolesRouteImport } from "./routes/_authed/settings/roles"
import { Route as AuthedSettingsNotificationsRouteImport } from "./routes/_authed/settings/notifications"
import { Route as AuthedSettingsMercadopagoRouteImport } from "./routes/_authed/settings/mercadopago"
import { Route as AuthedSettingsMercadolibreRouteImport } from "./routes/_authed/settings/mercadolibre"
import { Route as AuthedSettingsInventarioRouteImport } from "./routes/_authed/settings/inventario"
import { Route as AuthedSettingsHaulmerRouteImport } from "./routes/_authed/settings/haulmer"
import { Route as AuthedSettingsDoctoraliaRouteImport } from "./routes/_authed/settings/doctoralia"
import { Route as AuthedSettingsCsvUploadRouteImport } from "./routes/_authed/settings/csv-upload"
import { Route as AuthedSettingsConclusionTemplatesRouteImport } from "./routes/_authed/settings/conclusion-templates"
import { Route as AuthedSettingsClinicRouteImport } from "./routes/_authed/settings/clinic"
import { Route as AuthedSettingsBackupsRouteImport } from "./routes/_authed/settings/backups"
import { Route as AuthedServicesAgendaRouteImport } from "./routes/_authed/services/agenda"
import { Route as AuthedPatientsNewRouteImport } from "./routes/_authed/patients/new"
import { Route as AuthedPatientsCampaignsRouteImport } from "./routes/_authed/patients/campaigns"
import { Route as AuthedOutreachEstablecimientosRouteImport } from "./routes/_authed/outreach/establecimientos"
import { Route as AuthedOutreachDescubrirRouteImport } from "./routes/_authed/outreach/descubrir"
import { Route as AuthedOutreachCrawlerMasivoRouteImport } from "./routes/_authed/outreach/crawler-masivo"
import { Route as AuthedOutreachCampanasRouteImport } from "./routes/_authed/outreach/campanas"
import { Route as AuthedOperationsSuppliesRouteImport } from "./routes/_authed/operations/supplies"
import { Route as AuthedOperationsShipmentsRouteImport } from "./routes/_authed/operations/shipments"
import { Route as AuthedOperationsReviewsRouteImport } from "./routes/_authed/operations/reviews"
import { Route as AuthedOperationsInventoryRouteImport } from "./routes/_authed/operations/inventory"
import { Route as AuthedOperationsHaulmerDteRouteImport } from "./routes/_authed/operations/haulmer-dte"
import { Route as AuthedOperationsChannelPricesRouteImport } from "./routes/_authed/operations/channel-prices"
import { Route as AuthedOperationsCatalogRouteImport } from "./routes/_authed/operations/catalog"
import { Route as AuthedHrTimesheetsRouteImport } from "./routes/_authed/hr/timesheets"
import { Route as AuthedHrReportsRouteImport } from "./routes/_authed/hr/reports"
import { Route as AuthedHrEmployeesRouteImport } from "./routes/_authed/hr/employees"
import { Route as AuthedHrAuditRouteImport } from "./routes/_authed/hr/audit"
import { Route as AuthedHrAttendanceRouteImport } from "./routes/_authed/hr/attendance"
import { Route as AuthedFinanzasStatisticsRouteImport } from "./routes/_authed/finanzas/statistics"
import { Route as AuthedFinanzasProductionBalancesRouteImport } from "./routes/_authed/finanzas/production-balances"
import { Route as AuthedFinanzasPersonalRouteImport } from "./routes/_authed/finanzas/personal"
import { Route as AuthedFinanzasLoansRouteImport } from "./routes/_authed/finanzas/loans"
import { Route as AuthedFinanzasDteAnalyticsRouteImport } from "./routes/_authed/finanzas/dte-analytics"
import { Route as AuthedFinanzasDashboardRouteImport } from "./routes/_authed/finanzas/dashboard"
import { Route as AuthedFinanzasDailyRouteImport } from "./routes/_authed/finanzas/daily"
import { Route as AuthedFinanzasCounterpartsRouteImport } from "./routes/_authed/finanzas/counterparts"
import { Route as AuthedFinanzasCashFlowRouteImport } from "./routes/_authed/finanzas/cash-flow"
import { Route as AuthedExamReportsIdRouteImport } from "./routes/_authed/exam-reports/$id"
import { Route as AuthedDevRoutesAuditRouteImport } from "./routes/_authed/dev/routes-audit"
import { Route as AuthedClinicalRecordsRouteImport } from "./routes/_authed/clinical/records"
import { Route as AuthedClinicalHeatmapRouteImport } from "./routes/_authed/clinical/heatmap"
import { Route as AuthedClinicalDoctoraliaRouteImport } from "./routes/_authed/clinical/doctoralia"
import { Route as AuthedClinicalDayRouteImport } from "./routes/_authed/clinical/day"
import { Route as AuthedClinicalClassifyRouteImport } from "./routes/_authed/clinical/classify"
import { Route as AuthedClinicalAnalyticsRouteImport } from "./routes/_authed/clinical/analytics"
import { Route as AuthedClinicalAgendaRouteImport } from "./routes/_authed/clinical/agenda"
import { Route as AuthedCertificatesMedicalRouteImport } from "./routes/_authed/certificates/medical"
import { Route as AuthedCalendarSyncHistoryRouteImport } from "./routes/_authed/calendar/sync-history"
import { Route as AuthedCalendarDteLinksRouteImport } from "./routes/_authed/calendar/dte-links"
import { Route as AuthedSettingsUsersIndexRouteImport } from "./routes/_authed/settings/users/index"
import { Route as AuthedPatientsIdIndexRouteImport } from "./routes/_authed/patients/$id/index"
import { Route as AuthedSettingsUsersAddRouteImport } from "./routes/_authed/settings/users/add"
import { Route as AuthedServicesIdEditRouteImport } from "./routes/_authed/services/$id.edit"
import { Route as AuthedPatientsIdNewPaymentRouteImport } from "./routes/_authed/patients/$id/new-payment"
import { Route as AuthedPatientsIdNewConsultationRouteImport } from "./routes/_authed/patients/$id/new-consultation"
import { Route as AuthedPatientsIdNewBudgetRouteImport } from "./routes/_authed/patients/$id/new-budget"
import { Route as AuthedOutreachEstablecimientosRbdRouteImport } from "./routes/_authed/outreach/establecimientos.$rbd"
import { Route as AuthedOutreachCampanasNuevaRouteImport } from "./routes/_authed/outreach/campanas.nueva"
import { Route as AuthedOutreachCampanasIdRouteImport } from "./routes/_authed/outreach/campanas.$id"
import { Route as AuthedFinanzasPersonalCreditIdRouteImport } from "./routes/_authed/finanzas/personal.$creditId"

const OnboardingRoute = OnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedRoute,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: "/verify/$id",
  path: "/verify/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWaCloudRoute = AuthedWaCloudRouteImport.update({
  id: "/wa-cloud",
  path: "/wa-cloud",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServicesRoute = AuthedServicesRouteImport.update({
  id: "/services",
  path: "/services",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOutreachRoute = AuthedOutreachRouteImport.update({
  id: "/outreach",
  path: "/outreach",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOperationsRoute = AuthedOperationsRouteImport.update({
  id: "/operations",
  path: "/operations",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMarcarRoute = AuthedMarcarRouteImport.update({
  id: "/marcar",
  path: "/marcar",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHrRoute = AuthedHrRouteImport.update({
  id: "/hr",
  path: "/hr",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFinanzasRoute = AuthedFinanzasRouteImport.update({
  id: "/finanzas",
  path: "/finanzas",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClinicalRoute = AuthedClinicalRouteImport.update({
  id: "/clinical",
  path: "/clinical",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCertificatesRoute = AuthedCertificatesRouteImport.update({
  id: "/certificates",
  path: "/certificates",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalendarRoute = AuthedCalendarRouteImport.update({
  id: "/calendar",
  path: "/calendar",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWaCloudIndexRoute = AuthedWaCloudIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedWaCloudRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedServicesIndexRoute = AuthedServicesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedServicesRoute,
} as any)
const AuthedPatientsIndexRoute = AuthedPatientsIndexRouteImport.update({
  id: "/patients/",
  path: "/patients/",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOutreachIndexRoute = AuthedOutreachIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedOutreachRoute,
} as any)
const AuthedHrIndexRoute = AuthedHrIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedHrRoute,
} as any)
const AuthedExamReportsIndexRoute = AuthedExamReportsIndexRouteImport.update({
  id: "/exam-reports/",
  path: "/exam-reports/",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClinicalIndexRoute = AuthedClinicalIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedClinicalRoute,
} as any)
const AuthedWaCloudWebhooksRoute = AuthedWaCloudWebhooksRouteImport.update({
  id: "/webhooks",
  path: "/webhooks",
  getParentRoute: () => AuthedWaCloudRoute,
} as any)
const AuthedWaCloudProgramadosRoute =
  AuthedWaCloudProgramadosRouteImport.update({
    id: "/programados",
    path: "/programados",
    getParentRoute: () => AuthedWaCloudRoute,
  } as any)
const AuthedWaCloudPlantillasRoute = AuthedWaCloudPlantillasRouteImport.update({
  id: "/plantillas",
  path: "/plantillas",
  getParentRoute: () => AuthedWaCloudRoute,
} as any)
const AuthedWaCloudConfiguracionRoute =
  AuthedWaCloudConfiguracionRouteImport.update({
    id: "/configuracion",
    path: "/configuracion",
    getParentRoute: () => AuthedWaCloudRoute,
  } as any)
const AuthedWaCloudCatalogoRoute = AuthedWaCloudCatalogoRouteImport.update({
  id: "/catalogo",
  path: "/catalogo",
  getParentRoute: () => AuthedWaCloudRoute,
} as any)
const AuthedWaCloudBuscarRoute = AuthedWaCloudBuscarRouteImport.update({
  id: "/buscar",
  path: "/buscar",
  getParentRoute: () => AuthedWaCloudRoute,
} as any)
const AuthedWaCloudBroadcastsRoute = AuthedWaCloudBroadcastsRouteImport.update({
  id: "/broadcasts",
  path: "/broadcasts",
  getParentRoute: () => AuthedWaCloudRoute,
} as any)
const AuthedWaCloudAnalyticsRoute = AuthedWaCloudAnalyticsRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => AuthedWaCloudRoute,
} as any)
const AuthedWaCloudAlertasRoute = AuthedWaCloudAlertasRouteImport.update({
  id: "/alertas",
  path: "/alertas",
  getParentRoute: () => AuthedWaCloudRoute,
} as any)
const AuthedSettingsTiendaRoute = AuthedSettingsTiendaRouteImport.update({
  id: "/tienda",
  path: "/tienda",
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsRolesRoute = AuthedSettingsRolesRouteImport.update({
  id: "/roles",
  path: "/roles",
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsNotificationsRoute =
  AuthedSettingsNotificationsRouteImport.update({
    id: "/notifications",
    path: "/notifications",
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsMercadopagoRoute =
  AuthedSettingsMercadopagoRouteImport.update({
    id: "/mercadopago",
    path: "/mercadopago",
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsMercadolibreRoute =
  AuthedSettingsMercadolibreRouteImport.update({
    id: "/mercadolibre",
    path: "/mercadolibre",
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsInventarioRoute =
  AuthedSettingsInventarioRouteImport.update({
    id: "/inventario",
    path: "/inventario",
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsHaulmerRoute = AuthedSettingsHaulmerRouteImport.update({
  id: "/haulmer",
  path: "/haulmer",
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsDoctoraliaRoute =
  AuthedSettingsDoctoraliaRouteImport.update({
    id: "/doctoralia",
    path: "/doctoralia",
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsCsvUploadRoute = AuthedSettingsCsvUploadRouteImport.update({
  id: "/csv-upload",
  path: "/csv-upload",
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsConclusionTemplatesRoute =
  AuthedSettingsConclusionTemplatesRouteImport.update({
    id: "/conclusion-templates",
    path: "/conclusion-templates",
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsClinicRoute = AuthedSettingsClinicRouteImport.update({
  id: "/clinic",
  path: "/clinic",
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsBackupsRoute = AuthedSettingsBackupsRouteImport.update({
  id: "/backups",
  path: "/backups",
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedServicesAgendaRoute = AuthedServicesAgendaRouteImport.update({
  id: "/agenda",
  path: "/agenda",
  getParentRoute: () => AuthedServicesRoute,
} as any)
const AuthedPatientsNewRoute = AuthedPatientsNewRouteImport.update({
  id: "/patients/new",
  path: "/patients/new",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPatientsCampaignsRoute = AuthedPatientsCampaignsRouteImport.update({
  id: "/patients/campaigns",
  path: "/patients/campaigns",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOutreachEstablecimientosRoute =
  AuthedOutreachEstablecimientosRouteImport.update({
    id: "/establecimientos",
    path: "/establecimientos",
    getParentRoute: () => AuthedOutreachRoute,
  } as any)
const AuthedOutreachDescubrirRoute = AuthedOutreachDescubrirRouteImport.update({
  id: "/descubrir",
  path: "/descubrir",
  getParentRoute: () => AuthedOutreachRoute,
} as any)
const AuthedOutreachCrawlerMasivoRoute =
  AuthedOutreachCrawlerMasivoRouteImport.update({
    id: "/crawler-masivo",
    path: "/crawler-masivo",
    getParentRoute: () => AuthedOutreachRoute,
  } as any)
const AuthedOutreachCampanasRoute = AuthedOutreachCampanasRouteImport.update({
  id: "/campanas",
  path: "/campanas",
  getParentRoute: () => AuthedOutreachRoute,
} as any)
const AuthedOperationsSuppliesRoute =
  AuthedOperationsSuppliesRouteImport.update({
    id: "/supplies",
    path: "/supplies",
    getParentRoute: () => AuthedOperationsRoute,
  } as any)
const AuthedOperationsShipmentsRoute =
  AuthedOperationsShipmentsRouteImport.update({
    id: "/shipments",
    path: "/shipments",
    getParentRoute: () => AuthedOperationsRoute,
  } as any)
const AuthedOperationsReviewsRoute = AuthedOperationsReviewsRouteImport.update({
  id: "/reviews",
  path: "/reviews",
  getParentRoute: () => AuthedOperationsRoute,
} as any)
const AuthedOperationsInventoryRoute =
  AuthedOperationsInventoryRouteImport.update({
    id: "/inventory",
    path: "/inventory",
    getParentRoute: () => AuthedOperationsRoute,
  } as any)
const AuthedOperationsHaulmerDteRoute =
  AuthedOperationsHaulmerDteRouteImport.update({
    id: "/haulmer-dte",
    path: "/haulmer-dte",
    getParentRoute: () => AuthedOperationsRoute,
  } as any)
const AuthedOperationsChannelPricesRoute =
  AuthedOperationsChannelPricesRouteImport.update({
    id: "/channel-prices",
    path: "/channel-prices",
    getParentRoute: () => AuthedOperationsRoute,
  } as any)
const AuthedOperationsCatalogRoute = AuthedOperationsCatalogRouteImport.update({
  id: "/catalog",
  path: "/catalog",
  getParentRoute: () => AuthedOperationsRoute,
} as any)
const AuthedHrTimesheetsRoute = AuthedHrTimesheetsRouteImport.update({
  id: "/timesheets",
  path: "/timesheets",
  getParentRoute: () => AuthedHrRoute,
} as any)
const AuthedHrReportsRoute = AuthedHrReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => AuthedHrRoute,
} as any)
const AuthedHrEmployeesRoute = AuthedHrEmployeesRouteImport.update({
  id: "/employees",
  path: "/employees",
  getParentRoute: () => AuthedHrRoute,
} as any)
const AuthedHrAuditRoute = AuthedHrAuditRouteImport.update({
  id: "/audit",
  path: "/audit",
  getParentRoute: () => AuthedHrRoute,
} as any)
const AuthedHrAttendanceRoute = AuthedHrAttendanceRouteImport.update({
  id: "/attendance",
  path: "/attendance",
  getParentRoute: () => AuthedHrRoute,
} as any)
const AuthedFinanzasStatisticsRoute =
  AuthedFinanzasStatisticsRouteImport.update({
    id: "/statistics",
    path: "/statistics",
    getParentRoute: () => AuthedFinanzasRoute,
  } as any)
const AuthedFinanzasProductionBalancesRoute =
  AuthedFinanzasProductionBalancesRouteImport.update({
    id: "/production-balances",
    path: "/production-balances",
    getParentRoute: () => AuthedFinanzasRoute,
  } as any)
const AuthedFinanzasPersonalRoute = AuthedFinanzasPersonalRouteImport.update({
  id: "/personal",
  path: "/personal",
  getParentRoute: () => AuthedFinanzasRoute,
} as any)
const AuthedFinanzasLoansRoute = AuthedFinanzasLoansRouteImport.update({
  id: "/loans",
  path: "/loans",
  getParentRoute: () => AuthedFinanzasRoute,
} as any)
const AuthedFinanzasDteAnalyticsRoute =
  AuthedFinanzasDteAnalyticsRouteImport.update({
    id: "/dte-analytics",
    path: "/dte-analytics",
    getParentRoute: () => AuthedFinanzasRoute,
  } as any)
const AuthedFinanzasDashboardRoute = AuthedFinanzasDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthedFinanzasRoute,
} as any)
const AuthedFinanzasDailyRoute = AuthedFinanzasDailyRouteImport.update({
  id: "/daily",
  path: "/daily",
  getParentRoute: () => AuthedFinanzasRoute,
} as any)
const AuthedFinanzasCounterpartsRoute =
  AuthedFinanzasCounterpartsRouteImport.update({
    id: "/counterparts",
    path: "/counterparts",
    getParentRoute: () => AuthedFinanzasRoute,
  } as any)
const AuthedFinanzasCashFlowRoute = AuthedFinanzasCashFlowRouteImport.update({
  id: "/cash-flow",
  path: "/cash-flow",
  getParentRoute: () => AuthedFinanzasRoute,
} as any)
const AuthedExamReportsIdRoute = AuthedExamReportsIdRouteImport.update({
  id: "/exam-reports/$id",
  path: "/exam-reports/$id",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDevRoutesAuditRoute = AuthedDevRoutesAuditRouteImport.update({
  id: "/dev/routes-audit",
  path: "/dev/routes-audit",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClinicalRecordsRoute = AuthedClinicalRecordsRouteImport.update({
  id: "/records",
  path: "/records",
  getParentRoute: () => AuthedClinicalRoute,
} as any)
const AuthedClinicalHeatmapRoute = AuthedClinicalHeatmapRouteImport.update({
  id: "/heatmap",
  path: "/heatmap",
  getParentRoute: () => AuthedClinicalRoute,
} as any)
const AuthedClinicalDoctoraliaRoute =
  AuthedClinicalDoctoraliaRouteImport.update({
    id: "/doctoralia",
    path: "/doctoralia",
    getParentRoute: () => AuthedClinicalRoute,
  } as any)
const AuthedClinicalDayRoute = AuthedClinicalDayRouteImport.update({
  id: "/day",
  path: "/day",
  getParentRoute: () => AuthedClinicalRoute,
} as any)
const AuthedClinicalClassifyRoute = AuthedClinicalClassifyRouteImport.update({
  id: "/classify",
  path: "/classify",
  getParentRoute: () => AuthedClinicalRoute,
} as any)
const AuthedClinicalAnalyticsRoute = AuthedClinicalAnalyticsRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => AuthedClinicalRoute,
} as any)
const AuthedClinicalAgendaRoute = AuthedClinicalAgendaRouteImport.update({
  id: "/agenda",
  path: "/agenda",
  getParentRoute: () => AuthedClinicalRoute,
} as any)
const AuthedCertificatesMedicalRoute =
  AuthedCertificatesMedicalRouteImport.update({
    id: "/medical",
    path: "/medical",
    getParentRoute: () => AuthedCertificatesRoute,
  } as any)
const AuthedCalendarSyncHistoryRoute =
  AuthedCalendarSyncHistoryRouteImport.update({
    id: "/sync-history",
    path: "/sync-history",
    getParentRoute: () => AuthedCalendarRoute,
  } as any)
const AuthedCalendarDteLinksRoute = AuthedCalendarDteLinksRouteImport.update({
  id: "/dte-links",
  path: "/dte-links",
  getParentRoute: () => AuthedCalendarRoute,
} as any)
const AuthedSettingsUsersIndexRoute =
  AuthedSettingsUsersIndexRouteImport.update({
    id: "/users/",
    path: "/users/",
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedPatientsIdIndexRoute = AuthedPatientsIdIndexRouteImport.update({
  id: "/patients/$id/",
  path: "/patients/$id/",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsUsersAddRoute = AuthedSettingsUsersAddRouteImport.update({
  id: "/users/add",
  path: "/users/add",
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedServicesIdEditRoute = AuthedServicesIdEditRouteImport.update({
  id: "/$id/edit",
  path: "/$id/edit",
  getParentRoute: () => AuthedServicesRoute,
} as any)
const AuthedPatientsIdNewPaymentRoute =
  AuthedPatientsIdNewPaymentRouteImport.update({
    id: "/patients/$id/new-payment",
    path: "/patients/$id/new-payment",
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPatientsIdNewConsultationRoute =
  AuthedPatientsIdNewConsultationRouteImport.update({
    id: "/patients/$id/new-consultation",
    path: "/patients/$id/new-consultation",
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPatientsIdNewBudgetRoute =
  AuthedPatientsIdNewBudgetRouteImport.update({
    id: "/patients/$id/new-budget",
    path: "/patients/$id/new-budget",
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOutreachEstablecimientosRbdRoute =
  AuthedOutreachEstablecimientosRbdRouteImport.update({
    id: "/$rbd",
    path: "/$rbd",
    getParentRoute: () => AuthedOutreachEstablecimientosRoute,
  } as any)
const AuthedOutreachCampanasNuevaRoute =
  AuthedOutreachCampanasNuevaRouteImport.update({
    id: "/nueva",
    path: "/nueva",
    getParentRoute: () => AuthedOutreachCampanasRoute,
  } as any)
const AuthedOutreachCampanasIdRoute =
  AuthedOutreachCampanasIdRouteImport.update({
    id: "/$id",
    path: "/$id",
    getParentRoute: () => AuthedOutreachCampanasRoute,
  } as any)
const AuthedFinanzasPersonalCreditIdRoute =
  AuthedFinanzasPersonalCreditIdRouteImport.update({
    id: "/$creditId",
    path: "/$creditId",
    getParentRoute: () => AuthedFinanzasPersonalRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof AuthedIndexRoute
  "/login": typeof LoginRoute
  "/onboarding": typeof OnboardingRoute
  "/account": typeof AuthedAccountRoute
  "/calendar": typeof AuthedCalendarRouteWithChildren
  "/certificates": typeof AuthedCertificatesRouteWithChildren
  "/clinical": typeof AuthedClinicalRouteWithChildren
  "/finanzas": typeof AuthedFinanzasRouteWithChildren
  "/hr": typeof AuthedHrRouteWithChildren
  "/marcar": typeof AuthedMarcarRoute
  "/operations": typeof AuthedOperationsRouteWithChildren
  "/outreach": typeof AuthedOutreachRouteWithChildren
  "/services": typeof AuthedServicesRouteWithChildren
  "/settings": typeof AuthedSettingsRouteWithChildren
  "/wa-cloud": typeof AuthedWaCloudRouteWithChildren
  "/verify/$id": typeof VerifyIdRoute
  "/calendar/dte-links": typeof AuthedCalendarDteLinksRoute
  "/calendar/sync-history": typeof AuthedCalendarSyncHistoryRoute
  "/certificates/medical": typeof AuthedCertificatesMedicalRoute
  "/clinical/agenda": typeof AuthedClinicalAgendaRoute
  "/clinical/analytics": typeof AuthedClinicalAnalyticsRoute
  "/clinical/classify": typeof AuthedClinicalClassifyRoute
  "/clinical/day": typeof AuthedClinicalDayRoute
  "/clinical/doctoralia": typeof AuthedClinicalDoctoraliaRoute
  "/clinical/heatmap": typeof AuthedClinicalHeatmapRoute
  "/clinical/records": typeof AuthedClinicalRecordsRoute
  "/dev/routes-audit": typeof AuthedDevRoutesAuditRoute
  "/exam-reports/$id": typeof AuthedExamReportsIdRoute
  "/finanzas/cash-flow": typeof AuthedFinanzasCashFlowRoute
  "/finanzas/counterparts": typeof AuthedFinanzasCounterpartsRoute
  "/finanzas/daily": typeof AuthedFinanzasDailyRoute
  "/finanzas/dashboard": typeof AuthedFinanzasDashboardRoute
  "/finanzas/dte-analytics": typeof AuthedFinanzasDteAnalyticsRoute
  "/finanzas/loans": typeof AuthedFinanzasLoansRoute
  "/finanzas/personal": typeof AuthedFinanzasPersonalRouteWithChildren
  "/finanzas/production-balances": typeof AuthedFinanzasProductionBalancesRoute
  "/finanzas/statistics": typeof AuthedFinanzasStatisticsRoute
  "/hr/attendance": typeof AuthedHrAttendanceRoute
  "/hr/audit": typeof AuthedHrAuditRoute
  "/hr/employees": typeof AuthedHrEmployeesRoute
  "/hr/reports": typeof AuthedHrReportsRoute
  "/hr/timesheets": typeof AuthedHrTimesheetsRoute
  "/operations/catalog": typeof AuthedOperationsCatalogRoute
  "/operations/channel-prices": typeof AuthedOperationsChannelPricesRoute
  "/operations/haulmer-dte": typeof AuthedOperationsHaulmerDteRoute
  "/operations/inventory": typeof AuthedOperationsInventoryRoute
  "/operations/reviews": typeof AuthedOperationsReviewsRoute
  "/operations/shipments": typeof AuthedOperationsShipmentsRoute
  "/operations/supplies": typeof AuthedOperationsSuppliesRoute
  "/outreach/campanas": typeof AuthedOutreachCampanasRouteWithChildren
  "/outreach/crawler-masivo": typeof AuthedOutreachCrawlerMasivoRoute
  "/outreach/descubrir": typeof AuthedOutreachDescubrirRoute
  "/outreach/establecimientos": typeof AuthedOutreachEstablecimientosRouteWithChildren
  "/patients/campaigns": typeof AuthedPatientsCampaignsRoute
  "/patients/new": typeof AuthedPatientsNewRoute
  "/services/agenda": typeof AuthedServicesAgendaRoute
  "/settings/backups": typeof AuthedSettingsBackupsRoute
  "/settings/clinic": typeof AuthedSettingsClinicRoute
  "/settings/conclusion-templates": typeof AuthedSettingsConclusionTemplatesRoute
  "/settings/csv-upload": typeof AuthedSettingsCsvUploadRoute
  "/settings/doctoralia": typeof AuthedSettingsDoctoraliaRoute
  "/settings/haulmer": typeof AuthedSettingsHaulmerRoute
  "/settings/inventario": typeof AuthedSettingsInventarioRoute
  "/settings/mercadolibre": typeof AuthedSettingsMercadolibreRoute
  "/settings/mercadopago": typeof AuthedSettingsMercadopagoRoute
  "/settings/notifications": typeof AuthedSettingsNotificationsRoute
  "/settings/roles": typeof AuthedSettingsRolesRoute
  "/settings/tienda": typeof AuthedSettingsTiendaRoute
  "/wa-cloud/alertas": typeof AuthedWaCloudAlertasRoute
  "/wa-cloud/analytics": typeof AuthedWaCloudAnalyticsRoute
  "/wa-cloud/broadcasts": typeof AuthedWaCloudBroadcastsRoute
  "/wa-cloud/buscar": typeof AuthedWaCloudBuscarRoute
  "/wa-cloud/catalogo": typeof AuthedWaCloudCatalogoRoute
  "/wa-cloud/configuracion": typeof AuthedWaCloudConfiguracionRoute
  "/wa-cloud/plantillas": typeof AuthedWaCloudPlantillasRoute
  "/wa-cloud/programados": typeof AuthedWaCloudProgramadosRoute
  "/wa-cloud/webhooks": typeof AuthedWaCloudWebhooksRoute
  "/clinical/": typeof AuthedClinicalIndexRoute
  "/exam-reports/": typeof AuthedExamReportsIndexRoute
  "/hr/": typeof AuthedHrIndexRoute
  "/outreach/": typeof AuthedOutreachIndexRoute
  "/patients/": typeof AuthedPatientsIndexRoute
  "/services/": typeof AuthedServicesIndexRoute
  "/settings/": typeof AuthedSettingsIndexRoute
  "/wa-cloud/": typeof AuthedWaCloudIndexRoute
  "/finanzas/personal/$creditId": typeof AuthedFinanzasPersonalCreditIdRoute
  "/outreach/campanas/$id": typeof AuthedOutreachCampanasIdRoute
  "/outreach/campanas/nueva": typeof AuthedOutreachCampanasNuevaRoute
  "/outreach/establecimientos/$rbd": typeof AuthedOutreachEstablecimientosRbdRoute
  "/patients/$id/new-budget": typeof AuthedPatientsIdNewBudgetRoute
  "/patients/$id/new-consultation": typeof AuthedPatientsIdNewConsultationRoute
  "/patients/$id/new-payment": typeof AuthedPatientsIdNewPaymentRoute
  "/services/$id/edit": typeof AuthedServicesIdEditRoute
  "/settings/users/add": typeof AuthedSettingsUsersAddRoute
  "/patients/$id/": typeof AuthedPatientsIdIndexRoute
  "/settings/users/": typeof AuthedSettingsUsersIndexRoute
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute
  "/onboarding": typeof OnboardingRoute
  "/account": typeof AuthedAccountRoute
  "/calendar": typeof AuthedCalendarRouteWithChildren
  "/certificates": typeof AuthedCertificatesRouteWithChildren
  "/finanzas": typeof AuthedFinanzasRouteWithChildren
  "/marcar": typeof AuthedMarcarRoute
  "/operations": typeof AuthedOperationsRouteWithChildren
  "/verify/$id": typeof VerifyIdRoute
  "/": typeof AuthedIndexRoute
  "/calendar/dte-links": typeof AuthedCalendarDteLinksRoute
  "/calendar/sync-history": typeof AuthedCalendarSyncHistoryRoute
  "/certificates/medical": typeof AuthedCertificatesMedicalRoute
  "/clinical/agenda": typeof AuthedClinicalAgendaRoute
  "/clinical/analytics": typeof AuthedClinicalAnalyticsRoute
  "/clinical/classify": typeof AuthedClinicalClassifyRoute
  "/clinical/day": typeof AuthedClinicalDayRoute
  "/clinical/doctoralia": typeof AuthedClinicalDoctoraliaRoute
  "/clinical/heatmap": typeof AuthedClinicalHeatmapRoute
  "/clinical/records": typeof AuthedClinicalRecordsRoute
  "/dev/routes-audit": typeof AuthedDevRoutesAuditRoute
  "/exam-reports/$id": typeof AuthedExamReportsIdRoute
  "/finanzas/cash-flow": typeof AuthedFinanzasCashFlowRoute
  "/finanzas/counterparts": typeof AuthedFinanzasCounterpartsRoute
  "/finanzas/daily": typeof AuthedFinanzasDailyRoute
  "/finanzas/dashboard": typeof AuthedFinanzasDashboardRoute
  "/finanzas/dte-analytics": typeof AuthedFinanzasDteAnalyticsRoute
  "/finanzas/loans": typeof AuthedFinanzasLoansRoute
  "/finanzas/personal": typeof AuthedFinanzasPersonalRouteWithChildren
  "/finanzas/production-balances": typeof AuthedFinanzasProductionBalancesRoute
  "/finanzas/statistics": typeof AuthedFinanzasStatisticsRoute
  "/hr/attendance": typeof AuthedHrAttendanceRoute
  "/hr/audit": typeof AuthedHrAuditRoute
  "/hr/employees": typeof AuthedHrEmployeesRoute
  "/hr/reports": typeof AuthedHrReportsRoute
  "/hr/timesheets": typeof AuthedHrTimesheetsRoute
  "/operations/catalog": typeof AuthedOperationsCatalogRoute
  "/operations/channel-prices": typeof AuthedOperationsChannelPricesRoute
  "/operations/haulmer-dte": typeof AuthedOperationsHaulmerDteRoute
  "/operations/inventory": typeof AuthedOperationsInventoryRoute
  "/operations/reviews": typeof AuthedOperationsReviewsRoute
  "/operations/shipments": typeof AuthedOperationsShipmentsRoute
  "/operations/supplies": typeof AuthedOperationsSuppliesRoute
  "/outreach/campanas": typeof AuthedOutreachCampanasRouteWithChildren
  "/outreach/crawler-masivo": typeof AuthedOutreachCrawlerMasivoRoute
  "/outreach/descubrir": typeof AuthedOutreachDescubrirRoute
  "/outreach/establecimientos": typeof AuthedOutreachEstablecimientosRouteWithChildren
  "/patients/campaigns": typeof AuthedPatientsCampaignsRoute
  "/patients/new": typeof AuthedPatientsNewRoute
  "/services/agenda": typeof AuthedServicesAgendaRoute
  "/settings/backups": typeof AuthedSettingsBackupsRoute
  "/settings/clinic": typeof AuthedSettingsClinicRoute
  "/settings/conclusion-templates": typeof AuthedSettingsConclusionTemplatesRoute
  "/settings/csv-upload": typeof AuthedSettingsCsvUploadRoute
  "/settings/doctoralia": typeof AuthedSettingsDoctoraliaRoute
  "/settings/haulmer": typeof AuthedSettingsHaulmerRoute
  "/settings/inventario": typeof AuthedSettingsInventarioRoute
  "/settings/mercadolibre": typeof AuthedSettingsMercadolibreRoute
  "/settings/mercadopago": typeof AuthedSettingsMercadopagoRoute
  "/settings/notifications": typeof AuthedSettingsNotificationsRoute
  "/settings/roles": typeof AuthedSettingsRolesRoute
  "/settings/tienda": typeof AuthedSettingsTiendaRoute
  "/wa-cloud/alertas": typeof AuthedWaCloudAlertasRoute
  "/wa-cloud/analytics": typeof AuthedWaCloudAnalyticsRoute
  "/wa-cloud/broadcasts": typeof AuthedWaCloudBroadcastsRoute
  "/wa-cloud/buscar": typeof AuthedWaCloudBuscarRoute
  "/wa-cloud/catalogo": typeof AuthedWaCloudCatalogoRoute
  "/wa-cloud/configuracion": typeof AuthedWaCloudConfiguracionRoute
  "/wa-cloud/plantillas": typeof AuthedWaCloudPlantillasRoute
  "/wa-cloud/programados": typeof AuthedWaCloudProgramadosRoute
  "/wa-cloud/webhooks": typeof AuthedWaCloudWebhooksRoute
  "/clinical": typeof AuthedClinicalIndexRoute
  "/exam-reports": typeof AuthedExamReportsIndexRoute
  "/hr": typeof AuthedHrIndexRoute
  "/outreach": typeof AuthedOutreachIndexRoute
  "/patients": typeof AuthedPatientsIndexRoute
  "/services": typeof AuthedServicesIndexRoute
  "/settings": typeof AuthedSettingsIndexRoute
  "/wa-cloud": typeof AuthedWaCloudIndexRoute
  "/finanzas/personal/$creditId": typeof AuthedFinanzasPersonalCreditIdRoute
  "/outreach/campanas/$id": typeof AuthedOutreachCampanasIdRoute
  "/outreach/campanas/nueva": typeof AuthedOutreachCampanasNuevaRoute
  "/outreach/establecimientos/$rbd": typeof AuthedOutreachEstablecimientosRbdRoute
  "/patients/$id/new-budget": typeof AuthedPatientsIdNewBudgetRoute
  "/patients/$id/new-consultation": typeof AuthedPatientsIdNewConsultationRoute
  "/patients/$id/new-payment": typeof AuthedPatientsIdNewPaymentRoute
  "/services/$id/edit": typeof AuthedServicesIdEditRoute
  "/settings/users/add": typeof AuthedSettingsUsersAddRoute
  "/patients/$id": typeof AuthedPatientsIdIndexRoute
  "/settings/users": typeof AuthedSettingsUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_authed": typeof AuthedRouteWithChildren
  "/login": typeof LoginRoute
  "/onboarding": typeof OnboardingRoute
  "/_authed/account": typeof AuthedAccountRoute
  "/_authed/calendar": typeof AuthedCalendarRouteWithChildren
  "/_authed/certificates": typeof AuthedCertificatesRouteWithChildren
  "/_authed/clinical": typeof AuthedClinicalRouteWithChildren
  "/_authed/finanzas": typeof AuthedFinanzasRouteWithChildren
  "/_authed/hr": typeof AuthedHrRouteWithChildren
  "/_authed/marcar": typeof AuthedMarcarRoute
  "/_authed/operations": typeof AuthedOperationsRouteWithChildren
  "/_authed/outreach": typeof AuthedOutreachRouteWithChildren
  "/_authed/services": typeof AuthedServicesRouteWithChildren
  "/_authed/settings": typeof AuthedSettingsRouteWithChildren
  "/_authed/wa-cloud": typeof AuthedWaCloudRouteWithChildren
  "/verify/$id": typeof VerifyIdRoute
  "/_authed/": typeof AuthedIndexRoute
  "/_authed/calendar/dte-links": typeof AuthedCalendarDteLinksRoute
  "/_authed/calendar/sync-history": typeof AuthedCalendarSyncHistoryRoute
  "/_authed/certificates/medical": typeof AuthedCertificatesMedicalRoute
  "/_authed/clinical/agenda": typeof AuthedClinicalAgendaRoute
  "/_authed/clinical/analytics": typeof AuthedClinicalAnalyticsRoute
  "/_authed/clinical/classify": typeof AuthedClinicalClassifyRoute
  "/_authed/clinical/day": typeof AuthedClinicalDayRoute
  "/_authed/clinical/doctoralia": typeof AuthedClinicalDoctoraliaRoute
  "/_authed/clinical/heatmap": typeof AuthedClinicalHeatmapRoute
  "/_authed/clinical/records": typeof AuthedClinicalRecordsRoute
  "/_authed/dev/routes-audit": typeof AuthedDevRoutesAuditRoute
  "/_authed/exam-reports/$id": typeof AuthedExamReportsIdRoute
  "/_authed/finanzas/cash-flow": typeof AuthedFinanzasCashFlowRoute
  "/_authed/finanzas/counterparts": typeof AuthedFinanzasCounterpartsRoute
  "/_authed/finanzas/daily": typeof AuthedFinanzasDailyRoute
  "/_authed/finanzas/dashboard": typeof AuthedFinanzasDashboardRoute
  "/_authed/finanzas/dte-analytics": typeof AuthedFinanzasDteAnalyticsRoute
  "/_authed/finanzas/loans": typeof AuthedFinanzasLoansRoute
  "/_authed/finanzas/personal": typeof AuthedFinanzasPersonalRouteWithChildren
  "/_authed/finanzas/production-balances": typeof AuthedFinanzasProductionBalancesRoute
  "/_authed/finanzas/statistics": typeof AuthedFinanzasStatisticsRoute
  "/_authed/hr/attendance": typeof AuthedHrAttendanceRoute
  "/_authed/hr/audit": typeof AuthedHrAuditRoute
  "/_authed/hr/employees": typeof AuthedHrEmployeesRoute
  "/_authed/hr/reports": typeof AuthedHrReportsRoute
  "/_authed/hr/timesheets": typeof AuthedHrTimesheetsRoute
  "/_authed/operations/catalog": typeof AuthedOperationsCatalogRoute
  "/_authed/operations/channel-prices": typeof AuthedOperationsChannelPricesRoute
  "/_authed/operations/haulmer-dte": typeof AuthedOperationsHaulmerDteRoute
  "/_authed/operations/inventory": typeof AuthedOperationsInventoryRoute
  "/_authed/operations/reviews": typeof AuthedOperationsReviewsRoute
  "/_authed/operations/shipments": typeof AuthedOperationsShipmentsRoute
  "/_authed/operations/supplies": typeof AuthedOperationsSuppliesRoute
  "/_authed/outreach/campanas": typeof AuthedOutreachCampanasRouteWithChildren
  "/_authed/outreach/crawler-masivo": typeof AuthedOutreachCrawlerMasivoRoute
  "/_authed/outreach/descubrir": typeof AuthedOutreachDescubrirRoute
  "/_authed/outreach/establecimientos": typeof AuthedOutreachEstablecimientosRouteWithChildren
  "/_authed/patients/campaigns": typeof AuthedPatientsCampaignsRoute
  "/_authed/patients/new": typeof AuthedPatientsNewRoute
  "/_authed/services/agenda": typeof AuthedServicesAgendaRoute
  "/_authed/settings/backups": typeof AuthedSettingsBackupsRoute
  "/_authed/settings/clinic": typeof AuthedSettingsClinicRoute
  "/_authed/settings/conclusion-templates": typeof AuthedSettingsConclusionTemplatesRoute
  "/_authed/settings/csv-upload": typeof AuthedSettingsCsvUploadRoute
  "/_authed/settings/doctoralia": typeof AuthedSettingsDoctoraliaRoute
  "/_authed/settings/haulmer": typeof AuthedSettingsHaulmerRoute
  "/_authed/settings/inventario": typeof AuthedSettingsInventarioRoute
  "/_authed/settings/mercadolibre": typeof AuthedSettingsMercadolibreRoute
  "/_authed/settings/mercadopago": typeof AuthedSettingsMercadopagoRoute
  "/_authed/settings/notifications": typeof AuthedSettingsNotificationsRoute
  "/_authed/settings/roles": typeof AuthedSettingsRolesRoute
  "/_authed/settings/tienda": typeof AuthedSettingsTiendaRoute
  "/_authed/wa-cloud/alertas": typeof AuthedWaCloudAlertasRoute
  "/_authed/wa-cloud/analytics": typeof AuthedWaCloudAnalyticsRoute
  "/_authed/wa-cloud/broadcasts": typeof AuthedWaCloudBroadcastsRoute
  "/_authed/wa-cloud/buscar": typeof AuthedWaCloudBuscarRoute
  "/_authed/wa-cloud/catalogo": typeof AuthedWaCloudCatalogoRoute
  "/_authed/wa-cloud/configuracion": typeof AuthedWaCloudConfiguracionRoute
  "/_authed/wa-cloud/plantillas": typeof AuthedWaCloudPlantillasRoute
  "/_authed/wa-cloud/programados": typeof AuthedWaCloudProgramadosRoute
  "/_authed/wa-cloud/webhooks": typeof AuthedWaCloudWebhooksRoute
  "/_authed/clinical/": typeof AuthedClinicalIndexRoute
  "/_authed/exam-reports/": typeof AuthedExamReportsIndexRoute
  "/_authed/hr/": typeof AuthedHrIndexRoute
  "/_authed/outreach/": typeof AuthedOutreachIndexRoute
  "/_authed/patients/": typeof AuthedPatientsIndexRoute
  "/_authed/services/": typeof AuthedServicesIndexRoute
  "/_authed/settings/": typeof AuthedSettingsIndexRoute
  "/_authed/wa-cloud/": typeof AuthedWaCloudIndexRoute
  "/_authed/finanzas/personal/$creditId": typeof AuthedFinanzasPersonalCreditIdRoute
  "/_authed/outreach/campanas/$id": typeof AuthedOutreachCampanasIdRoute
  "/_authed/outreach/campanas/nueva": typeof AuthedOutreachCampanasNuevaRoute
  "/_authed/outreach/establecimientos/$rbd": typeof AuthedOutreachEstablecimientosRbdRoute
  "/_authed/patients/$id/new-budget": typeof AuthedPatientsIdNewBudgetRoute
  "/_authed/patients/$id/new-consultation": typeof AuthedPatientsIdNewConsultationRoute
  "/_authed/patients/$id/new-payment": typeof AuthedPatientsIdNewPaymentRoute
  "/_authed/services/$id/edit": typeof AuthedServicesIdEditRoute
  "/_authed/settings/users/add": typeof AuthedSettingsUsersAddRoute
  "/_authed/patients/$id/": typeof AuthedPatientsIdIndexRoute
  "/_authed/settings/users/": typeof AuthedSettingsUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/onboarding"
    | "/account"
    | "/calendar"
    | "/certificates"
    | "/clinical"
    | "/finanzas"
    | "/hr"
    | "/marcar"
    | "/operations"
    | "/outreach"
    | "/services"
    | "/settings"
    | "/wa-cloud"
    | "/verify/$id"
    | "/calendar/dte-links"
    | "/calendar/sync-history"
    | "/certificates/medical"
    | "/clinical/agenda"
    | "/clinical/analytics"
    | "/clinical/classify"
    | "/clinical/day"
    | "/clinical/doctoralia"
    | "/clinical/heatmap"
    | "/clinical/records"
    | "/dev/routes-audit"
    | "/exam-reports/$id"
    | "/finanzas/cash-flow"
    | "/finanzas/counterparts"
    | "/finanzas/daily"
    | "/finanzas/dashboard"
    | "/finanzas/dte-analytics"
    | "/finanzas/loans"
    | "/finanzas/personal"
    | "/finanzas/production-balances"
    | "/finanzas/statistics"
    | "/hr/attendance"
    | "/hr/audit"
    | "/hr/employees"
    | "/hr/reports"
    | "/hr/timesheets"
    | "/operations/catalog"
    | "/operations/channel-prices"
    | "/operations/haulmer-dte"
    | "/operations/inventory"
    | "/operations/reviews"
    | "/operations/shipments"
    | "/operations/supplies"
    | "/outreach/campanas"
    | "/outreach/crawler-masivo"
    | "/outreach/descubrir"
    | "/outreach/establecimientos"
    | "/patients/campaigns"
    | "/patients/new"
    | "/services/agenda"
    | "/settings/backups"
    | "/settings/clinic"
    | "/settings/conclusion-templates"
    | "/settings/csv-upload"
    | "/settings/doctoralia"
    | "/settings/haulmer"
    | "/settings/inventario"
    | "/settings/mercadolibre"
    | "/settings/mercadopago"
    | "/settings/notifications"
    | "/settings/roles"
    | "/settings/tienda"
    | "/wa-cloud/alertas"
    | "/wa-cloud/analytics"
    | "/wa-cloud/broadcasts"
    | "/wa-cloud/buscar"
    | "/wa-cloud/catalogo"
    | "/wa-cloud/configuracion"
    | "/wa-cloud/plantillas"
    | "/wa-cloud/programados"
    | "/wa-cloud/webhooks"
    | "/clinical/"
    | "/exam-reports/"
    | "/hr/"
    | "/outreach/"
    | "/patients/"
    | "/services/"
    | "/settings/"
    | "/wa-cloud/"
    | "/finanzas/personal/$creditId"
    | "/outreach/campanas/$id"
    | "/outreach/campanas/nueva"
    | "/outreach/establecimientos/$rbd"
    | "/patients/$id/new-budget"
    | "/patients/$id/new-consultation"
    | "/patients/$id/new-payment"
    | "/services/$id/edit"
    | "/settings/users/add"
    | "/patients/$id/"
    | "/settings/users/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/login"
    | "/onboarding"
    | "/account"
    | "/calendar"
    | "/certificates"
    | "/finanzas"
    | "/marcar"
    | "/operations"
    | "/verify/$id"
    | "/"
    | "/calendar/dte-links"
    | "/calendar/sync-history"
    | "/certificates/medical"
    | "/clinical/agenda"
    | "/clinical/analytics"
    | "/clinical/classify"
    | "/clinical/day"
    | "/clinical/doctoralia"
    | "/clinical/heatmap"
    | "/clinical/records"
    | "/dev/routes-audit"
    | "/exam-reports/$id"
    | "/finanzas/cash-flow"
    | "/finanzas/counterparts"
    | "/finanzas/daily"
    | "/finanzas/dashboard"
    | "/finanzas/dte-analytics"
    | "/finanzas/loans"
    | "/finanzas/personal"
    | "/finanzas/production-balances"
    | "/finanzas/statistics"
    | "/hr/attendance"
    | "/hr/audit"
    | "/hr/employees"
    | "/hr/reports"
    | "/hr/timesheets"
    | "/operations/catalog"
    | "/operations/channel-prices"
    | "/operations/haulmer-dte"
    | "/operations/inventory"
    | "/operations/reviews"
    | "/operations/shipments"
    | "/operations/supplies"
    | "/outreach/campanas"
    | "/outreach/crawler-masivo"
    | "/outreach/descubrir"
    | "/outreach/establecimientos"
    | "/patients/campaigns"
    | "/patients/new"
    | "/services/agenda"
    | "/settings/backups"
    | "/settings/clinic"
    | "/settings/conclusion-templates"
    | "/settings/csv-upload"
    | "/settings/doctoralia"
    | "/settings/haulmer"
    | "/settings/inventario"
    | "/settings/mercadolibre"
    | "/settings/mercadopago"
    | "/settings/notifications"
    | "/settings/roles"
    | "/settings/tienda"
    | "/wa-cloud/alertas"
    | "/wa-cloud/analytics"
    | "/wa-cloud/broadcasts"
    | "/wa-cloud/buscar"
    | "/wa-cloud/catalogo"
    | "/wa-cloud/configuracion"
    | "/wa-cloud/plantillas"
    | "/wa-cloud/programados"
    | "/wa-cloud/webhooks"
    | "/clinical"
    | "/exam-reports"
    | "/hr"
    | "/outreach"
    | "/patients"
    | "/services"
    | "/settings"
    | "/wa-cloud"
    | "/finanzas/personal/$creditId"
    | "/outreach/campanas/$id"
    | "/outreach/campanas/nueva"
    | "/outreach/establecimientos/$rbd"
    | "/patients/$id/new-budget"
    | "/patients/$id/new-consultation"
    | "/patients/$id/new-payment"
    | "/services/$id/edit"
    | "/settings/users/add"
    | "/patients/$id"
    | "/settings/users"
  id:
    | "__root__"
    | "/_authed"
    | "/login"
    | "/onboarding"
    | "/_authed/account"
    | "/_authed/calendar"
    | "/_authed/certificates"
    | "/_authed/clinical"
    | "/_authed/finanzas"
    | "/_authed/hr"
    | "/_authed/marcar"
    | "/_authed/operations"
    | "/_authed/outreach"
    | "/_authed/services"
    | "/_authed/settings"
    | "/_authed/wa-cloud"
    | "/verify/$id"
    | "/_authed/"
    | "/_authed/calendar/dte-links"
    | "/_authed/calendar/sync-history"
    | "/_authed/certificates/medical"
    | "/_authed/clinical/agenda"
    | "/_authed/clinical/analytics"
    | "/_authed/clinical/classify"
    | "/_authed/clinical/day"
    | "/_authed/clinical/doctoralia"
    | "/_authed/clinical/heatmap"
    | "/_authed/clinical/records"
    | "/_authed/dev/routes-audit"
    | "/_authed/exam-reports/$id"
    | "/_authed/finanzas/cash-flow"
    | "/_authed/finanzas/counterparts"
    | "/_authed/finanzas/daily"
    | "/_authed/finanzas/dashboard"
    | "/_authed/finanzas/dte-analytics"
    | "/_authed/finanzas/loans"
    | "/_authed/finanzas/personal"
    | "/_authed/finanzas/production-balances"
    | "/_authed/finanzas/statistics"
    | "/_authed/hr/attendance"
    | "/_authed/hr/audit"
    | "/_authed/hr/employees"
    | "/_authed/hr/reports"
    | "/_authed/hr/timesheets"
    | "/_authed/operations/catalog"
    | "/_authed/operations/channel-prices"
    | "/_authed/operations/haulmer-dte"
    | "/_authed/operations/inventory"
    | "/_authed/operations/reviews"
    | "/_authed/operations/shipments"
    | "/_authed/operations/supplies"
    | "/_authed/outreach/campanas"
    | "/_authed/outreach/crawler-masivo"
    | "/_authed/outreach/descubrir"
    | "/_authed/outreach/establecimientos"
    | "/_authed/patients/campaigns"
    | "/_authed/patients/new"
    | "/_authed/services/agenda"
    | "/_authed/settings/backups"
    | "/_authed/settings/clinic"
    | "/_authed/settings/conclusion-templates"
    | "/_authed/settings/csv-upload"
    | "/_authed/settings/doctoralia"
    | "/_authed/settings/haulmer"
    | "/_authed/settings/inventario"
    | "/_authed/settings/mercadolibre"
    | "/_authed/settings/mercadopago"
    | "/_authed/settings/notifications"
    | "/_authed/settings/roles"
    | "/_authed/settings/tienda"
    | "/_authed/wa-cloud/alertas"
    | "/_authed/wa-cloud/analytics"
    | "/_authed/wa-cloud/broadcasts"
    | "/_authed/wa-cloud/buscar"
    | "/_authed/wa-cloud/catalogo"
    | "/_authed/wa-cloud/configuracion"
    | "/_authed/wa-cloud/plantillas"
    | "/_authed/wa-cloud/programados"
    | "/_authed/wa-cloud/webhooks"
    | "/_authed/clinical/"
    | "/_authed/exam-reports/"
    | "/_authed/hr/"
    | "/_authed/outreach/"
    | "/_authed/patients/"
    | "/_authed/services/"
    | "/_authed/settings/"
    | "/_authed/wa-cloud/"
    | "/_authed/finanzas/personal/$creditId"
    | "/_authed/outreach/campanas/$id"
    | "/_authed/outreach/campanas/nueva"
    | "/_authed/outreach/establecimientos/$rbd"
    | "/_authed/patients/$id/new-budget"
    | "/_authed/patients/$id/new-consultation"
    | "/_authed/patients/$id/new-payment"
    | "/_authed/services/$id/edit"
    | "/_authed/settings/users/add"
    | "/_authed/patients/$id/"
    | "/_authed/settings/users/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  VerifyIdRoute: typeof VerifyIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/onboarding": {
      id: "/onboarding"
      path: "/onboarding"
      fullPath: "/onboarding"
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed": {
      id: "/_authed"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed/": {
      id: "/_authed/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/verify/$id": {
      id: "/verify/$id"
      path: "/verify/$id"
      fullPath: "/verify/$id"
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed/wa-cloud": {
      id: "/_authed/wa-cloud"
      path: "/wa-cloud"
      fullPath: "/wa-cloud"
      preLoaderRoute: typeof AuthedWaCloudRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/settings": {
      id: "/_authed/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/services": {
      id: "/_authed/services"
      path: "/services"
      fullPath: "/services"
      preLoaderRoute: typeof AuthedServicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/outreach": {
      id: "/_authed/outreach"
      path: "/outreach"
      fullPath: "/outreach"
      preLoaderRoute: typeof AuthedOutreachRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/operations": {
      id: "/_authed/operations"
      path: "/operations"
      fullPath: "/operations"
      preLoaderRoute: typeof AuthedOperationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/marcar": {
      id: "/_authed/marcar"
      path: "/marcar"
      fullPath: "/marcar"
      preLoaderRoute: typeof AuthedMarcarRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/hr": {
      id: "/_authed/hr"
      path: "/hr"
      fullPath: "/hr"
      preLoaderRoute: typeof AuthedHrRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/finanzas": {
      id: "/_authed/finanzas"
      path: "/finanzas"
      fullPath: "/finanzas"
      preLoaderRoute: typeof AuthedFinanzasRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/clinical": {
      id: "/_authed/clinical"
      path: "/clinical"
      fullPath: "/clinical"
      preLoaderRoute: typeof AuthedClinicalRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/certificates": {
      id: "/_authed/certificates"
      path: "/certificates"
      fullPath: "/certificates"
      preLoaderRoute: typeof AuthedCertificatesRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/calendar": {
      id: "/_authed/calendar"
      path: "/calendar"
      fullPath: "/calendar"
      preLoaderRoute: typeof AuthedCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/account": {
      id: "/_authed/account"
      path: "/account"
      fullPath: "/account"
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/wa-cloud/": {
      id: "/_authed/wa-cloud/"
      path: "/"
      fullPath: "/wa-cloud/"
      preLoaderRoute: typeof AuthedWaCloudIndexRouteImport
      parentRoute: typeof AuthedWaCloudRoute
    }
    "/_authed/settings/": {
      id: "/_authed/settings/"
      path: "/"
      fullPath: "/settings/"
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/services/": {
      id: "/_authed/services/"
      path: "/"
      fullPath: "/services/"
      preLoaderRoute: typeof AuthedServicesIndexRouteImport
      parentRoute: typeof AuthedServicesRoute
    }
    "/_authed/patients/": {
      id: "/_authed/patients/"
      path: "/patients"
      fullPath: "/patients/"
      preLoaderRoute: typeof AuthedPatientsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/outreach/": {
      id: "/_authed/outreach/"
      path: "/"
      fullPath: "/outreach/"
      preLoaderRoute: typeof AuthedOutreachIndexRouteImport
      parentRoute: typeof AuthedOutreachRoute
    }
    "/_authed/hr/": {
      id: "/_authed/hr/"
      path: "/"
      fullPath: "/hr/"
      preLoaderRoute: typeof AuthedHrIndexRouteImport
      parentRoute: typeof AuthedHrRoute
    }
    "/_authed/exam-reports/": {
      id: "/_authed/exam-reports/"
      path: "/exam-reports"
      fullPath: "/exam-reports/"
      preLoaderRoute: typeof AuthedExamReportsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/clinical/": {
      id: "/_authed/clinical/"
      path: "/"
      fullPath: "/clinical/"
      preLoaderRoute: typeof AuthedClinicalIndexRouteImport
      parentRoute: typeof AuthedClinicalRoute
    }
    "/_authed/wa-cloud/webhooks": {
      id: "/_authed/wa-cloud/webhooks"
      path: "/webhooks"
      fullPath: "/wa-cloud/webhooks"
      preLoaderRoute: typeof AuthedWaCloudWebhooksRouteImport
      parentRoute: typeof AuthedWaCloudRoute
    }
    "/_authed/wa-cloud/programados": {
      id: "/_authed/wa-cloud/programados"
      path: "/programados"
      fullPath: "/wa-cloud/programados"
      preLoaderRoute: typeof AuthedWaCloudProgramadosRouteImport
      parentRoute: typeof AuthedWaCloudRoute
    }
    "/_authed/wa-cloud/plantillas": {
      id: "/_authed/wa-cloud/plantillas"
      path: "/plantillas"
      fullPath: "/wa-cloud/plantillas"
      preLoaderRoute: typeof AuthedWaCloudPlantillasRouteImport
      parentRoute: typeof AuthedWaCloudRoute
    }
    "/_authed/wa-cloud/configuracion": {
      id: "/_authed/wa-cloud/configuracion"
      path: "/configuracion"
      fullPath: "/wa-cloud/configuracion"
      preLoaderRoute: typeof AuthedWaCloudConfiguracionRouteImport
      parentRoute: typeof AuthedWaCloudRoute
    }
    "/_authed/wa-cloud/catalogo": {
      id: "/_authed/wa-cloud/catalogo"
      path: "/catalogo"
      fullPath: "/wa-cloud/catalogo"
      preLoaderRoute: typeof AuthedWaCloudCatalogoRouteImport
      parentRoute: typeof AuthedWaCloudRoute
    }
    "/_authed/wa-cloud/buscar": {
      id: "/_authed/wa-cloud/buscar"
      path: "/buscar"
      fullPath: "/wa-cloud/buscar"
      preLoaderRoute: typeof AuthedWaCloudBuscarRouteImport
      parentRoute: typeof AuthedWaCloudRoute
    }
    "/_authed/wa-cloud/broadcasts": {
      id: "/_authed/wa-cloud/broadcasts"
      path: "/broadcasts"
      fullPath: "/wa-cloud/broadcasts"
      preLoaderRoute: typeof AuthedWaCloudBroadcastsRouteImport
      parentRoute: typeof AuthedWaCloudRoute
    }
    "/_authed/wa-cloud/analytics": {
      id: "/_authed/wa-cloud/analytics"
      path: "/analytics"
      fullPath: "/wa-cloud/analytics"
      preLoaderRoute: typeof AuthedWaCloudAnalyticsRouteImport
      parentRoute: typeof AuthedWaCloudRoute
    }
    "/_authed/wa-cloud/alertas": {
      id: "/_authed/wa-cloud/alertas"
      path: "/alertas"
      fullPath: "/wa-cloud/alertas"
      preLoaderRoute: typeof AuthedWaCloudAlertasRouteImport
      parentRoute: typeof AuthedWaCloudRoute
    }
    "/_authed/settings/tienda": {
      id: "/_authed/settings/tienda"
      path: "/tienda"
      fullPath: "/settings/tienda"
      preLoaderRoute: typeof AuthedSettingsTiendaRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/settings/roles": {
      id: "/_authed/settings/roles"
      path: "/roles"
      fullPath: "/settings/roles"
      preLoaderRoute: typeof AuthedSettingsRolesRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/settings/notifications": {
      id: "/_authed/settings/notifications"
      path: "/notifications"
      fullPath: "/settings/notifications"
      preLoaderRoute: typeof AuthedSettingsNotificationsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/settings/mercadopago": {
      id: "/_authed/settings/mercadopago"
      path: "/mercadopago"
      fullPath: "/settings/mercadopago"
      preLoaderRoute: typeof AuthedSettingsMercadopagoRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/settings/mercadolibre": {
      id: "/_authed/settings/mercadolibre"
      path: "/mercadolibre"
      fullPath: "/settings/mercadolibre"
      preLoaderRoute: typeof AuthedSettingsMercadolibreRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/settings/inventario": {
      id: "/_authed/settings/inventario"
      path: "/inventario"
      fullPath: "/settings/inventario"
      preLoaderRoute: typeof AuthedSettingsInventarioRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/settings/haulmer": {
      id: "/_authed/settings/haulmer"
      path: "/haulmer"
      fullPath: "/settings/haulmer"
      preLoaderRoute: typeof AuthedSettingsHaulmerRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/settings/doctoralia": {
      id: "/_authed/settings/doctoralia"
      path: "/doctoralia"
      fullPath: "/settings/doctoralia"
      preLoaderRoute: typeof AuthedSettingsDoctoraliaRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/settings/csv-upload": {
      id: "/_authed/settings/csv-upload"
      path: "/csv-upload"
      fullPath: "/settings/csv-upload"
      preLoaderRoute: typeof AuthedSettingsCsvUploadRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/settings/conclusion-templates": {
      id: "/_authed/settings/conclusion-templates"
      path: "/conclusion-templates"
      fullPath: "/settings/conclusion-templates"
      preLoaderRoute: typeof AuthedSettingsConclusionTemplatesRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/settings/clinic": {
      id: "/_authed/settings/clinic"
      path: "/clinic"
      fullPath: "/settings/clinic"
      preLoaderRoute: typeof AuthedSettingsClinicRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/settings/backups": {
      id: "/_authed/settings/backups"
      path: "/backups"
      fullPath: "/settings/backups"
      preLoaderRoute: typeof AuthedSettingsBackupsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/services/agenda": {
      id: "/_authed/services/agenda"
      path: "/agenda"
      fullPath: "/services/agenda"
      preLoaderRoute: typeof AuthedServicesAgendaRouteImport
      parentRoute: typeof AuthedServicesRoute
    }
    "/_authed/patients/new": {
      id: "/_authed/patients/new"
      path: "/patients/new"
      fullPath: "/patients/new"
      preLoaderRoute: typeof AuthedPatientsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/patients/campaigns": {
      id: "/_authed/patients/campaigns"
      path: "/patients/campaigns"
      fullPath: "/patients/campaigns"
      preLoaderRoute: typeof AuthedPatientsCampaignsRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/outreach/establecimientos": {
      id: "/_authed/outreach/establecimientos"
      path: "/establecimientos"
      fullPath: "/outreach/establecimientos"
      preLoaderRoute: typeof AuthedOutreachEstablecimientosRouteImport
      parentRoute: typeof AuthedOutreachRoute
    }
    "/_authed/outreach/descubrir": {
      id: "/_authed/outreach/descubrir"
      path: "/descubrir"
      fullPath: "/outreach/descubrir"
      preLoaderRoute: typeof AuthedOutreachDescubrirRouteImport
      parentRoute: typeof AuthedOutreachRoute
    }
    "/_authed/outreach/crawler-masivo": {
      id: "/_authed/outreach/crawler-masivo"
      path: "/crawler-masivo"
      fullPath: "/outreach/crawler-masivo"
      preLoaderRoute: typeof AuthedOutreachCrawlerMasivoRouteImport
      parentRoute: typeof AuthedOutreachRoute
    }
    "/_authed/outreach/campanas": {
      id: "/_authed/outreach/campanas"
      path: "/campanas"
      fullPath: "/outreach/campanas"
      preLoaderRoute: typeof AuthedOutreachCampanasRouteImport
      parentRoute: typeof AuthedOutreachRoute
    }
    "/_authed/operations/supplies": {
      id: "/_authed/operations/supplies"
      path: "/supplies"
      fullPath: "/operations/supplies"
      preLoaderRoute: typeof AuthedOperationsSuppliesRouteImport
      parentRoute: typeof AuthedOperationsRoute
    }
    "/_authed/operations/shipments": {
      id: "/_authed/operations/shipments"
      path: "/shipments"
      fullPath: "/operations/shipments"
      preLoaderRoute: typeof AuthedOperationsShipmentsRouteImport
      parentRoute: typeof AuthedOperationsRoute
    }
    "/_authed/operations/reviews": {
      id: "/_authed/operations/reviews"
      path: "/reviews"
      fullPath: "/operations/reviews"
      preLoaderRoute: typeof AuthedOperationsReviewsRouteImport
      parentRoute: typeof AuthedOperationsRoute
    }
    "/_authed/operations/inventory": {
      id: "/_authed/operations/inventory"
      path: "/inventory"
      fullPath: "/operations/inventory"
      preLoaderRoute: typeof AuthedOperationsInventoryRouteImport
      parentRoute: typeof AuthedOperationsRoute
    }
    "/_authed/operations/haulmer-dte": {
      id: "/_authed/operations/haulmer-dte"
      path: "/haulmer-dte"
      fullPath: "/operations/haulmer-dte"
      preLoaderRoute: typeof AuthedOperationsHaulmerDteRouteImport
      parentRoute: typeof AuthedOperationsRoute
    }
    "/_authed/operations/channel-prices": {
      id: "/_authed/operations/channel-prices"
      path: "/channel-prices"
      fullPath: "/operations/channel-prices"
      preLoaderRoute: typeof AuthedOperationsChannelPricesRouteImport
      parentRoute: typeof AuthedOperationsRoute
    }
    "/_authed/operations/catalog": {
      id: "/_authed/operations/catalog"
      path: "/catalog"
      fullPath: "/operations/catalog"
      preLoaderRoute: typeof AuthedOperationsCatalogRouteImport
      parentRoute: typeof AuthedOperationsRoute
    }
    "/_authed/hr/timesheets": {
      id: "/_authed/hr/timesheets"
      path: "/timesheets"
      fullPath: "/hr/timesheets"
      preLoaderRoute: typeof AuthedHrTimesheetsRouteImport
      parentRoute: typeof AuthedHrRoute
    }
    "/_authed/hr/reports": {
      id: "/_authed/hr/reports"
      path: "/reports"
      fullPath: "/hr/reports"
      preLoaderRoute: typeof AuthedHrReportsRouteImport
      parentRoute: typeof AuthedHrRoute
    }
    "/_authed/hr/employees": {
      id: "/_authed/hr/employees"
      path: "/employees"
      fullPath: "/hr/employees"
      preLoaderRoute: typeof AuthedHrEmployeesRouteImport
      parentRoute: typeof AuthedHrRoute
    }
    "/_authed/hr/audit": {
      id: "/_authed/hr/audit"
      path: "/audit"
      fullPath: "/hr/audit"
      preLoaderRoute: typeof AuthedHrAuditRouteImport
      parentRoute: typeof AuthedHrRoute
    }
    "/_authed/hr/attendance": {
      id: "/_authed/hr/attendance"
      path: "/attendance"
      fullPath: "/hr/attendance"
      preLoaderRoute: typeof AuthedHrAttendanceRouteImport
      parentRoute: typeof AuthedHrRoute
    }
    "/_authed/finanzas/statistics": {
      id: "/_authed/finanzas/statistics"
      path: "/statistics"
      fullPath: "/finanzas/statistics"
      preLoaderRoute: typeof AuthedFinanzasStatisticsRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/production-balances": {
      id: "/_authed/finanzas/production-balances"
      path: "/production-balances"
      fullPath: "/finanzas/production-balances"
      preLoaderRoute: typeof AuthedFinanzasProductionBalancesRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/personal": {
      id: "/_authed/finanzas/personal"
      path: "/personal"
      fullPath: "/finanzas/personal"
      preLoaderRoute: typeof AuthedFinanzasPersonalRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/loans": {
      id: "/_authed/finanzas/loans"
      path: "/loans"
      fullPath: "/finanzas/loans"
      preLoaderRoute: typeof AuthedFinanzasLoansRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/dte-analytics": {
      id: "/_authed/finanzas/dte-analytics"
      path: "/dte-analytics"
      fullPath: "/finanzas/dte-analytics"
      preLoaderRoute: typeof AuthedFinanzasDteAnalyticsRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/dashboard": {
      id: "/_authed/finanzas/dashboard"
      path: "/dashboard"
      fullPath: "/finanzas/dashboard"
      preLoaderRoute: typeof AuthedFinanzasDashboardRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/daily": {
      id: "/_authed/finanzas/daily"
      path: "/daily"
      fullPath: "/finanzas/daily"
      preLoaderRoute: typeof AuthedFinanzasDailyRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/counterparts": {
      id: "/_authed/finanzas/counterparts"
      path: "/counterparts"
      fullPath: "/finanzas/counterparts"
      preLoaderRoute: typeof AuthedFinanzasCounterpartsRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/cash-flow": {
      id: "/_authed/finanzas/cash-flow"
      path: "/cash-flow"
      fullPath: "/finanzas/cash-flow"
      preLoaderRoute: typeof AuthedFinanzasCashFlowRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/exam-reports/$id": {
      id: "/_authed/exam-reports/$id"
      path: "/exam-reports/$id"
      fullPath: "/exam-reports/$id"
      preLoaderRoute: typeof AuthedExamReportsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/dev/routes-audit": {
      id: "/_authed/dev/routes-audit"
      path: "/dev/routes-audit"
      fullPath: "/dev/routes-audit"
      preLoaderRoute: typeof AuthedDevRoutesAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/clinical/records": {
      id: "/_authed/clinical/records"
      path: "/records"
      fullPath: "/clinical/records"
      preLoaderRoute: typeof AuthedClinicalRecordsRouteImport
      parentRoute: typeof AuthedClinicalRoute
    }
    "/_authed/clinical/heatmap": {
      id: "/_authed/clinical/heatmap"
      path: "/heatmap"
      fullPath: "/clinical/heatmap"
      preLoaderRoute: typeof AuthedClinicalHeatmapRouteImport
      parentRoute: typeof AuthedClinicalRoute
    }
    "/_authed/clinical/doctoralia": {
      id: "/_authed/clinical/doctoralia"
      path: "/doctoralia"
      fullPath: "/clinical/doctoralia"
      preLoaderRoute: typeof AuthedClinicalDoctoraliaRouteImport
      parentRoute: typeof AuthedClinicalRoute
    }
    "/_authed/clinical/day": {
      id: "/_authed/clinical/day"
      path: "/day"
      fullPath: "/clinical/day"
      preLoaderRoute: typeof AuthedClinicalDayRouteImport
      parentRoute: typeof AuthedClinicalRoute
    }
    "/_authed/clinical/classify": {
      id: "/_authed/clinical/classify"
      path: "/classify"
      fullPath: "/clinical/classify"
      preLoaderRoute: typeof AuthedClinicalClassifyRouteImport
      parentRoute: typeof AuthedClinicalRoute
    }
    "/_authed/clinical/analytics": {
      id: "/_authed/clinical/analytics"
      path: "/analytics"
      fullPath: "/clinical/analytics"
      preLoaderRoute: typeof AuthedClinicalAnalyticsRouteImport
      parentRoute: typeof AuthedClinicalRoute
    }
    "/_authed/clinical/agenda": {
      id: "/_authed/clinical/agenda"
      path: "/agenda"
      fullPath: "/clinical/agenda"
      preLoaderRoute: typeof AuthedClinicalAgendaRouteImport
      parentRoute: typeof AuthedClinicalRoute
    }
    "/_authed/certificates/medical": {
      id: "/_authed/certificates/medical"
      path: "/medical"
      fullPath: "/certificates/medical"
      preLoaderRoute: typeof AuthedCertificatesMedicalRouteImport
      parentRoute: typeof AuthedCertificatesRoute
    }
    "/_authed/calendar/sync-history": {
      id: "/_authed/calendar/sync-history"
      path: "/sync-history"
      fullPath: "/calendar/sync-history"
      preLoaderRoute: typeof AuthedCalendarSyncHistoryRouteImport
      parentRoute: typeof AuthedCalendarRoute
    }
    "/_authed/calendar/dte-links": {
      id: "/_authed/calendar/dte-links"
      path: "/dte-links"
      fullPath: "/calendar/dte-links"
      preLoaderRoute: typeof AuthedCalendarDteLinksRouteImport
      parentRoute: typeof AuthedCalendarRoute
    }
    "/_authed/settings/users/": {
      id: "/_authed/settings/users/"
      path: "/users"
      fullPath: "/settings/users/"
      preLoaderRoute: typeof AuthedSettingsUsersIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/patients/$id/": {
      id: "/_authed/patients/$id/"
      path: "/patients/$id"
      fullPath: "/patients/$id/"
      preLoaderRoute: typeof AuthedPatientsIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/settings/users/add": {
      id: "/_authed/settings/users/add"
      path: "/users/add"
      fullPath: "/settings/users/add"
      preLoaderRoute: typeof AuthedSettingsUsersAddRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/services/$id/edit": {
      id: "/_authed/services/$id/edit"
      path: "/$id/edit"
      fullPath: "/services/$id/edit"
      preLoaderRoute: typeof AuthedServicesIdEditRouteImport
      parentRoute: typeof AuthedServicesRoute
    }
    "/_authed/patients/$id/new-payment": {
      id: "/_authed/patients/$id/new-payment"
      path: "/patients/$id/new-payment"
      fullPath: "/patients/$id/new-payment"
      preLoaderRoute: typeof AuthedPatientsIdNewPaymentRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/patients/$id/new-consultation": {
      id: "/_authed/patients/$id/new-consultation"
      path: "/patients/$id/new-consultation"
      fullPath: "/patients/$id/new-consultation"
      preLoaderRoute: typeof AuthedPatientsIdNewConsultationRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/patients/$id/new-budget": {
      id: "/_authed/patients/$id/new-budget"
      path: "/patients/$id/new-budget"
      fullPath: "/patients/$id/new-budget"
      preLoaderRoute: typeof AuthedPatientsIdNewBudgetRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/outreach/establecimientos/$rbd": {
      id: "/_authed/outreach/establecimientos/$rbd"
      path: "/$rbd"
      fullPath: "/outreach/establecimientos/$rbd"
      preLoaderRoute: typeof AuthedOutreachEstablecimientosRbdRouteImport
      parentRoute: typeof AuthedOutreachEstablecimientosRoute
    }
    "/_authed/outreach/campanas/nueva": {
      id: "/_authed/outreach/campanas/nueva"
      path: "/nueva"
      fullPath: "/outreach/campanas/nueva"
      preLoaderRoute: typeof AuthedOutreachCampanasNuevaRouteImport
      parentRoute: typeof AuthedOutreachCampanasRoute
    }
    "/_authed/outreach/campanas/$id": {
      id: "/_authed/outreach/campanas/$id"
      path: "/$id"
      fullPath: "/outreach/campanas/$id"
      preLoaderRoute: typeof AuthedOutreachCampanasIdRouteImport
      parentRoute: typeof AuthedOutreachCampanasRoute
    }
    "/_authed/finanzas/personal/$creditId": {
      id: "/_authed/finanzas/personal/$creditId"
      path: "/$creditId"
      fullPath: "/finanzas/personal/$creditId"
      preLoaderRoute: typeof AuthedFinanzasPersonalCreditIdRouteImport
      parentRoute: typeof AuthedFinanzasPersonalRoute
    }
  }
}

interface AuthedCalendarRouteChildren {
  AuthedCalendarDteLinksRoute: typeof AuthedCalendarDteLinksRoute
  AuthedCalendarSyncHistoryRoute: typeof AuthedCalendarSyncHistoryRoute
}

const AuthedCalendarRouteChildren: AuthedCalendarRouteChildren = {
  AuthedCalendarDteLinksRoute: AuthedCalendarDteLinksRoute,
  AuthedCalendarSyncHistoryRoute: AuthedCalendarSyncHistoryRoute,
}

const AuthedCalendarRouteWithChildren = AuthedCalendarRoute._addFileChildren(
  AuthedCalendarRouteChildren,
)

interface AuthedCertificatesRouteChildren {
  AuthedCertificatesMedicalRoute: typeof AuthedCertificatesMedicalRoute
}

const AuthedCertificatesRouteChildren: AuthedCertificatesRouteChildren = {
  AuthedCertificatesMedicalRoute: AuthedCertificatesMedicalRoute,
}

const AuthedCertificatesRouteWithChildren =
  AuthedCertificatesRoute._addFileChildren(AuthedCertificatesRouteChildren)

interface AuthedClinicalRouteChildren {
  AuthedClinicalAgendaRoute: typeof AuthedClinicalAgendaRoute
  AuthedClinicalAnalyticsRoute: typeof AuthedClinicalAnalyticsRoute
  AuthedClinicalClassifyRoute: typeof AuthedClinicalClassifyRoute
  AuthedClinicalDayRoute: typeof AuthedClinicalDayRoute
  AuthedClinicalDoctoraliaRoute: typeof AuthedClinicalDoctoraliaRoute
  AuthedClinicalHeatmapRoute: typeof AuthedClinicalHeatmapRoute
  AuthedClinicalRecordsRoute: typeof AuthedClinicalRecordsRoute
  AuthedClinicalIndexRoute: typeof AuthedClinicalIndexRoute
}

const AuthedClinicalRouteChildren: AuthedClinicalRouteChildren = {
  AuthedClinicalAgendaRoute: AuthedClinicalAgendaRoute,
  AuthedClinicalAnalyticsRoute: AuthedClinicalAnalyticsRoute,
  AuthedClinicalClassifyRoute: AuthedClinicalClassifyRoute,
  AuthedClinicalDayRoute: AuthedClinicalDayRoute,
  AuthedClinicalDoctoraliaRoute: AuthedClinicalDoctoraliaRoute,
  AuthedClinicalHeatmapRoute: AuthedClinicalHeatmapRoute,
  AuthedClinicalRecordsRoute: AuthedClinicalRecordsRoute,
  AuthedClinicalIndexRoute: AuthedClinicalIndexRoute,
}

const AuthedClinicalRouteWithChildren = AuthedClinicalRoute._addFileChildren(
  AuthedClinicalRouteChildren,
)

interface AuthedFinanzasPersonalRouteChildren {
  AuthedFinanzasPersonalCreditIdRoute: typeof AuthedFinanzasPersonalCreditIdRoute
}

const AuthedFinanzasPersonalRouteChildren: AuthedFinanzasPersonalRouteChildren =
  {
    AuthedFinanzasPersonalCreditIdRoute: AuthedFinanzasPersonalCreditIdRoute,
  }

const AuthedFinanzasPersonalRouteWithChildren =
  AuthedFinanzasPersonalRoute._addFileChildren(
    AuthedFinanzasPersonalRouteChildren,
  )

interface AuthedFinanzasRouteChildren {
  AuthedFinanzasCashFlowRoute: typeof AuthedFinanzasCashFlowRoute
  AuthedFinanzasCounterpartsRoute: typeof AuthedFinanzasCounterpartsRoute
  AuthedFinanzasDailyRoute: typeof AuthedFinanzasDailyRoute
  AuthedFinanzasDashboardRoute: typeof AuthedFinanzasDashboardRoute
  AuthedFinanzasDteAnalyticsRoute: typeof AuthedFinanzasDteAnalyticsRoute
  AuthedFinanzasLoansRoute: typeof AuthedFinanzasLoansRoute
  AuthedFinanzasPersonalRoute: typeof AuthedFinanzasPersonalRouteWithChildren
  AuthedFinanzasProductionBalancesRoute: typeof AuthedFinanzasProductionBalancesRoute
  AuthedFinanzasStatisticsRoute: typeof AuthedFinanzasStatisticsRoute
}

const AuthedFinanzasRouteChildren: AuthedFinanzasRouteChildren = {
  AuthedFinanzasCashFlowRoute: AuthedFinanzasCashFlowRoute,
  AuthedFinanzasCounterpartsRoute: AuthedFinanzasCounterpartsRoute,
  AuthedFinanzasDailyRoute: AuthedFinanzasDailyRoute,
  AuthedFinanzasDashboardRoute: AuthedFinanzasDashboardRoute,
  AuthedFinanzasDteAnalyticsRoute: AuthedFinanzasDteAnalyticsRoute,
  AuthedFinanzasLoansRoute: AuthedFinanzasLoansRoute,
  AuthedFinanzasPersonalRoute: AuthedFinanzasPersonalRouteWithChildren,
  AuthedFinanzasProductionBalancesRoute: AuthedFinanzasProductionBalancesRoute,
  AuthedFinanzasStatisticsRoute: AuthedFinanzasStatisticsRoute,
}

const AuthedFinanzasRouteWithChildren = AuthedFinanzasRoute._addFileChildren(
  AuthedFinanzasRouteChildren,
)

interface AuthedHrRouteChildren {
  AuthedHrAttendanceRoute: typeof AuthedHrAttendanceRoute
  AuthedHrAuditRoute: typeof AuthedHrAuditRoute
  AuthedHrEmployeesRoute: typeof AuthedHrEmployeesRoute
  AuthedHrReportsRoute: typeof AuthedHrReportsRoute
  AuthedHrTimesheetsRoute: typeof AuthedHrTimesheetsRoute
  AuthedHrIndexRoute: typeof AuthedHrIndexRoute
}

const AuthedHrRouteChildren: AuthedHrRouteChildren = {
  AuthedHrAttendanceRoute: AuthedHrAttendanceRoute,
  AuthedHrAuditRoute: AuthedHrAuditRoute,
  AuthedHrEmployeesRoute: AuthedHrEmployeesRoute,
  AuthedHrReportsRoute: AuthedHrReportsRoute,
  AuthedHrTimesheetsRoute: AuthedHrTimesheetsRoute,
  AuthedHrIndexRoute: AuthedHrIndexRoute,
}

const AuthedHrRouteWithChildren = AuthedHrRoute._addFileChildren(
  AuthedHrRouteChildren,
)

interface AuthedOperationsRouteChildren {
  AuthedOperationsCatalogRoute: typeof AuthedOperationsCatalogRoute
  AuthedOperationsChannelPricesRoute: typeof AuthedOperationsChannelPricesRoute
  AuthedOperationsHaulmerDteRoute: typeof AuthedOperationsHaulmerDteRoute
  AuthedOperationsInventoryRoute: typeof AuthedOperationsInventoryRoute
  AuthedOperationsReviewsRoute: typeof AuthedOperationsReviewsRoute
  AuthedOperationsShipmentsRoute: typeof AuthedOperationsShipmentsRoute
  AuthedOperationsSuppliesRoute: typeof AuthedOperationsSuppliesRoute
}

const AuthedOperationsRouteChildren: AuthedOperationsRouteChildren = {
  AuthedOperationsCatalogRoute: AuthedOperationsCatalogRoute,
  AuthedOperationsChannelPricesRoute: AuthedOperationsChannelPricesRoute,
  AuthedOperationsHaulmerDteRoute: AuthedOperationsHaulmerDteRoute,
  AuthedOperationsInventoryRoute: AuthedOperationsInventoryRoute,
  AuthedOperationsReviewsRoute: AuthedOperationsReviewsRoute,
  AuthedOperationsShipmentsRoute: AuthedOperationsShipmentsRoute,
  AuthedOperationsSuppliesRoute: AuthedOperationsSuppliesRoute,
}

const AuthedOperationsRouteWithChildren =
  AuthedOperationsRoute._addFileChildren(AuthedOperationsRouteChildren)

interface AuthedOutreachCampanasRouteChildren {
  AuthedOutreachCampanasIdRoute: typeof AuthedOutreachCampanasIdRoute
  AuthedOutreachCampanasNuevaRoute: typeof AuthedOutreachCampanasNuevaRoute
}

const AuthedOutreachCampanasRouteChildren: AuthedOutreachCampanasRouteChildren =
  {
    AuthedOutreachCampanasIdRoute: AuthedOutreachCampanasIdRoute,
    AuthedOutreachCampanasNuevaRoute: AuthedOutreachCampanasNuevaRoute,
  }

const AuthedOutreachCampanasRouteWithChildren =
  AuthedOutreachCampanasRoute._addFileChildren(
    AuthedOutreachCampanasRouteChildren,
  )

interface AuthedOutreachEstablecimientosRouteChildren {
  AuthedOutreachEstablecimientosRbdRoute: typeof AuthedOutreachEstablecimientosRbdRoute
}

const AuthedOutreachEstablecimientosRouteChildren: AuthedOutreachEstablecimientosRouteChildren =
  {
    AuthedOutreachEstablecimientosRbdRoute:
      AuthedOutreachEstablecimientosRbdRoute,
  }

const AuthedOutreachEstablecimientosRouteWithChildren =
  AuthedOutreachEstablecimientosRoute._addFileChildren(
    AuthedOutreachEstablecimientosRouteChildren,
  )

interface AuthedOutreachRouteChildren {
  AuthedOutreachCampanasRoute: typeof AuthedOutreachCampanasRouteWithChildren
  AuthedOutreachCrawlerMasivoRoute: typeof AuthedOutreachCrawlerMasivoRoute
  AuthedOutreachDescubrirRoute: typeof AuthedOutreachDescubrirRoute
  AuthedOutreachEstablecimientosRoute: typeof AuthedOutreachEstablecimientosRouteWithChildren
  AuthedOutreachIndexRoute: typeof AuthedOutreachIndexRoute
}

const AuthedOutreachRouteChildren: AuthedOutreachRouteChildren = {
  AuthedOutreachCampanasRoute: AuthedOutreachCampanasRouteWithChildren,
  AuthedOutreachCrawlerMasivoRoute: AuthedOutreachCrawlerMasivoRoute,
  AuthedOutreachDescubrirRoute: AuthedOutreachDescubrirRoute,
  AuthedOutreachEstablecimientosRoute:
    AuthedOutreachEstablecimientosRouteWithChildren,
  AuthedOutreachIndexRoute: AuthedOutreachIndexRoute,
}

const AuthedOutreachRouteWithChildren = AuthedOutreachRoute._addFileChildren(
  AuthedOutreachRouteChildren,
)

interface AuthedServicesRouteChildren {
  AuthedServicesAgendaRoute: typeof AuthedServicesAgendaRoute
  AuthedServicesIndexRoute: typeof AuthedServicesIndexRoute
  AuthedServicesIdEditRoute: typeof AuthedServicesIdEditRoute
}

const AuthedServicesRouteChildren: AuthedServicesRouteChildren = {
  AuthedServicesAgendaRoute: AuthedServicesAgendaRoute,
  AuthedServicesIndexRoute: AuthedServicesIndexRoute,
  AuthedServicesIdEditRoute: AuthedServicesIdEditRoute,
}

const AuthedServicesRouteWithChildren = AuthedServicesRoute._addFileChildren(
  AuthedServicesRouteChildren,
)

interface AuthedSettingsRouteChildren {
  AuthedSettingsBackupsRoute: typeof AuthedSettingsBackupsRoute
  AuthedSettingsClinicRoute: typeof AuthedSettingsClinicRoute
  AuthedSettingsConclusionTemplatesRoute: typeof AuthedSettingsConclusionTemplatesRoute
  AuthedSettingsCsvUploadRoute: typeof AuthedSettingsCsvUploadRoute
  AuthedSettingsDoctoraliaRoute: typeof AuthedSettingsDoctoraliaRoute
  AuthedSettingsHaulmerRoute: typeof AuthedSettingsHaulmerRoute
  AuthedSettingsInventarioRoute: typeof AuthedSettingsInventarioRoute
  AuthedSettingsMercadolibreRoute: typeof AuthedSettingsMercadolibreRoute
  AuthedSettingsMercadopagoRoute: typeof AuthedSettingsMercadopagoRoute
  AuthedSettingsNotificationsRoute: typeof AuthedSettingsNotificationsRoute
  AuthedSettingsRolesRoute: typeof AuthedSettingsRolesRoute
  AuthedSettingsTiendaRoute: typeof AuthedSettingsTiendaRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedSettingsUsersAddRoute: typeof AuthedSettingsUsersAddRoute
  AuthedSettingsUsersIndexRoute: typeof AuthedSettingsUsersIndexRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsBackupsRoute: AuthedSettingsBackupsRoute,
  AuthedSettingsClinicRoute: AuthedSettingsClinicRoute,
  AuthedSettingsConclusionTemplatesRoute:
    AuthedSettingsConclusionTemplatesRoute,
  AuthedSettingsCsvUploadRoute: AuthedSettingsCsvUploadRoute,
  AuthedSettingsDoctoraliaRoute: AuthedSettingsDoctoraliaRoute,
  AuthedSettingsHaulmerRoute: AuthedSettingsHaulmerRoute,
  AuthedSettingsInventarioRoute: AuthedSettingsInventarioRoute,
  AuthedSettingsMercadolibreRoute: AuthedSettingsMercadolibreRoute,
  AuthedSettingsMercadopagoRoute: AuthedSettingsMercadopagoRoute,
  AuthedSettingsNotificationsRoute: AuthedSettingsNotificationsRoute,
  AuthedSettingsRolesRoute: AuthedSettingsRolesRoute,
  AuthedSettingsTiendaRoute: AuthedSettingsTiendaRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedSettingsUsersAddRoute: AuthedSettingsUsersAddRoute,
  AuthedSettingsUsersIndexRoute: AuthedSettingsUsersIndexRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedWaCloudRouteChildren {
  AuthedWaCloudAlertasRoute: typeof AuthedWaCloudAlertasRoute
  AuthedWaCloudAnalyticsRoute: typeof AuthedWaCloudAnalyticsRoute
  AuthedWaCloudBroadcastsRoute: typeof AuthedWaCloudBroadcastsRoute
  AuthedWaCloudBuscarRoute: typeof AuthedWaCloudBuscarRoute
  AuthedWaCloudCatalogoRoute: typeof AuthedWaCloudCatalogoRoute
  AuthedWaCloudConfiguracionRoute: typeof AuthedWaCloudConfiguracionRoute
  AuthedWaCloudPlantillasRoute: typeof AuthedWaCloudPlantillasRoute
  AuthedWaCloudProgramadosRoute: typeof AuthedWaCloudProgramadosRoute
  AuthedWaCloudWebhooksRoute: typeof AuthedWaCloudWebhooksRoute
  AuthedWaCloudIndexRoute: typeof AuthedWaCloudIndexRoute
}

const AuthedWaCloudRouteChildren: AuthedWaCloudRouteChildren = {
  AuthedWaCloudAlertasRoute: AuthedWaCloudAlertasRoute,
  AuthedWaCloudAnalyticsRoute: AuthedWaCloudAnalyticsRoute,
  AuthedWaCloudBroadcastsRoute: AuthedWaCloudBroadcastsRoute,
  AuthedWaCloudBuscarRoute: AuthedWaCloudBuscarRoute,
  AuthedWaCloudCatalogoRoute: AuthedWaCloudCatalogoRoute,
  AuthedWaCloudConfiguracionRoute: AuthedWaCloudConfiguracionRoute,
  AuthedWaCloudPlantillasRoute: AuthedWaCloudPlantillasRoute,
  AuthedWaCloudProgramadosRoute: AuthedWaCloudProgramadosRoute,
  AuthedWaCloudWebhooksRoute: AuthedWaCloudWebhooksRoute,
  AuthedWaCloudIndexRoute: AuthedWaCloudIndexRoute,
}

const AuthedWaCloudRouteWithChildren = AuthedWaCloudRoute._addFileChildren(
  AuthedWaCloudRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedCalendarRoute: typeof AuthedCalendarRouteWithChildren
  AuthedCertificatesRoute: typeof AuthedCertificatesRouteWithChildren
  AuthedClinicalRoute: typeof AuthedClinicalRouteWithChildren
  AuthedFinanzasRoute: typeof AuthedFinanzasRouteWithChildren
  AuthedHrRoute: typeof AuthedHrRouteWithChildren
  AuthedMarcarRoute: typeof AuthedMarcarRoute
  AuthedOperationsRoute: typeof AuthedOperationsRouteWithChildren
  AuthedOutreachRoute: typeof AuthedOutreachRouteWithChildren
  AuthedServicesRoute: typeof AuthedServicesRouteWithChildren
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedWaCloudRoute: typeof AuthedWaCloudRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedDevRoutesAuditRoute: typeof AuthedDevRoutesAuditRoute
  AuthedExamReportsIdRoute: typeof AuthedExamReportsIdRoute
  AuthedPatientsCampaignsRoute: typeof AuthedPatientsCampaignsRoute
  AuthedPatientsNewRoute: typeof AuthedPatientsNewRoute
  AuthedExamReportsIndexRoute: typeof AuthedExamReportsIndexRoute
  AuthedPatientsIndexRoute: typeof AuthedPatientsIndexRoute
  AuthedPatientsIdNewBudgetRoute: typeof AuthedPatientsIdNewBudgetRoute
  AuthedPatientsIdNewConsultationRoute: typeof AuthedPatientsIdNewConsultationRoute
  AuthedPatientsIdNewPaymentRoute: typeof AuthedPatientsIdNewPaymentRoute
  AuthedPatientsIdIndexRoute: typeof AuthedPatientsIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedCalendarRoute: AuthedCalendarRouteWithChildren,
  AuthedCertificatesRoute: AuthedCertificatesRouteWithChildren,
  AuthedClinicalRoute: AuthedClinicalRouteWithChildren,
  AuthedFinanzasRoute: AuthedFinanzasRouteWithChildren,
  AuthedHrRoute: AuthedHrRouteWithChildren,
  AuthedMarcarRoute: AuthedMarcarRoute,
  AuthedOperationsRoute: AuthedOperationsRouteWithChildren,
  AuthedOutreachRoute: AuthedOutreachRouteWithChildren,
  AuthedServicesRoute: AuthedServicesRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedWaCloudRoute: AuthedWaCloudRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedDevRoutesAuditRoute: AuthedDevRoutesAuditRoute,
  AuthedExamReportsIdRoute: AuthedExamReportsIdRoute,
  AuthedPatientsCampaignsRoute: AuthedPatientsCampaignsRoute,
  AuthedPatientsNewRoute: AuthedPatientsNewRoute,
  AuthedExamReportsIndexRoute: AuthedExamReportsIndexRoute,
  AuthedPatientsIndexRoute: AuthedPatientsIndexRoute,
  AuthedPatientsIdNewBudgetRoute: AuthedPatientsIdNewBudgetRoute,
  AuthedPatientsIdNewConsultationRoute: AuthedPatientsIdNewConsultationRoute,
  AuthedPatientsIdNewPaymentRoute: AuthedPatientsIdNewPaymentRoute,
  AuthedPatientsIdIndexRoute: AuthedPatientsIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  VerifyIdRoute: VerifyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
