/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

// You should NOT make any changes in this file as it will be overwritten.

// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being modified or creating issues.

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as OnboardingRouteImport } from "./routes/onboarding"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AuthedRouteImport } from "./routes/_authed"
import { Route as AuthedIndexRouteImport } from "./routes/_authed/index"
import { Route as VerifyIdRouteImport } from "./routes/verify.$id"
import { Route as AuthedSettingsRouteImport } from "./routes/_authed/settings"
import { Route as AuthedServicesRouteImport } from "./routes/_authed/services"
import { Route as AuthedOperationsRouteImport } from "./routes/_authed/operations"
import { Route as AuthedHrRouteImport } from "./routes/_authed/hr"
import { Route as AuthedFinanzasRouteImport } from "./routes/_authed/finanzas"
import { Route as AuthedCertificatesRouteImport } from "./routes/_authed/certificates"
import { Route as AuthedCalendarRouteImport } from "./routes/_authed/calendar"
import { Route as AuthedAccountRouteImport } from "./routes/_authed/account"
import { Route as AuthedSettingsIndexRouteImport } from "./routes/_authed/settings/index"
import { Route as AuthedServicesIndexRouteImport } from "./routes/_authed/services/index"
import { Route as AuthedPatientsIndexRouteImport } from "./routes/_authed/patients/index"
import { Route as AuthedHrIndexRouteImport } from "./routes/_authed/hr/index"
import { Route as AuthedFinanzasIndexRouteImport } from "./routes/_authed/finanzas/index"
import { Route as AuthedSettingsUsersRouteImport } from "./routes/_authed/settings/users"
import { Route as AuthedSettingsRolesRouteImport } from "./routes/_authed/settings/roles"
import { Route as AuthedSettingsMercadopagoRouteImport } from "./routes/_authed/settings/mercadopago"
import { Route as AuthedSettingsInventarioRouteImport } from "./routes/_authed/settings/inventario"
import { Route as AuthedSettingsCsvUploadRouteImport } from "./routes/_authed/settings/csv-upload"
import { Route as AuthedSettingsBackupsRouteImport } from "./routes/_authed/settings/backups"
import { Route as AuthedServicesTemplatesRouteImport } from "./routes/_authed/services/templates"
import { Route as AuthedServicesCreateRouteImport } from "./routes/_authed/services/create"
import { Route as AuthedServicesAgendaRouteImport } from "./routes/_authed/services/agenda"
import { Route as AuthedPatientsNewRouteImport } from "./routes/_authed/patients/new"
import { Route as AuthedOperationsSuppliesAnalyticsRouteImport } from "./routes/_authed/operations/supplies-analytics"
import { Route as AuthedOperationsSuppliesRouteImport } from "./routes/_authed/operations/supplies"
import { Route as AuthedOperationsInventoryRouteImport } from "./routes/_authed/operations/inventory"
import { Route as AuthedHrTimesheetsRouteImport } from "./routes/_authed/hr/timesheets"
import { Route as AuthedHrReportsRouteImport } from "./routes/_authed/hr/reports"
import { Route as AuthedHrEmployeesRouteImport } from "./routes/_authed/hr/employees"
import { Route as AuthedHrAuditRouteImport } from "./routes/_authed/hr/audit"
import { Route as AuthedFinanzasStatisticsRouteImport } from "./routes/_authed/finanzas/statistics"
import { Route as AuthedFinanzasProductionBalancesRouteImport } from "./routes/_authed/finanzas/production-balances"
import { Route as AuthedFinanzasPersonalCreditsRouteImport } from "./routes/_authed/finanzas/personal-credits"
import { Route as AuthedFinanzasPayoutsRouteImport } from "./routes/_authed/finanzas/payouts"
import { Route as AuthedFinanzasParticipantsRouteImport } from "./routes/_authed/finanzas/participants"
import { Route as AuthedFinanzasLoansRouteImport } from "./routes/_authed/finanzas/loans"
import { Route as AuthedFinanzasLiberacionesRouteImport } from "./routes/_authed/finanzas/liberaciones"
import { Route as AuthedFinanzasDteAnalyticsRouteImport } from "./routes/_authed/finanzas/dte-analytics"
import { Route as AuthedFinanzasDashboardRouteImport } from "./routes/_authed/finanzas/dashboard"
import { Route as AuthedFinanzasDailyRouteImport } from "./routes/_authed/finanzas/daily"
import { Route as AuthedFinanzasCounterpartsRouteImport } from "./routes/_authed/finanzas/counterparts"
import { Route as AuthedFinanzasConciliacionesLiberacionesRouteImport } from "./routes/_authed/finanzas/conciliaciones-liberaciones"
import { Route as AuthedFinanzasConciliacionesRouteImport } from "./routes/_authed/finanzas/conciliaciones"
import { Route as AuthedDevRoutesAuditRouteImport } from "./routes/_authed/dev/routes-audit"
import { Route as AuthedCertificatesMedicalRouteImport } from "./routes/_authed/certificates/medical"
import { Route as AuthedCalendarSyncHistoryRouteImport } from "./routes/_authed/calendar/sync-history"
import { Route as AuthedCalendarScheduleRouteImport } from "./routes/_authed/calendar/schedule"
import { Route as AuthedCalendarHeatmapRouteImport } from "./routes/_authed/calendar/heatmap"
import { Route as AuthedCalendarDailyRouteImport } from "./routes/_authed/calendar/daily"
import { Route as AuthedCalendarClassifyRouteImport } from "./routes/_authed/calendar/classify"
import { Route as AuthedPatientsIdIndexRouteImport } from "./routes/_authed/patients/$id/index"
import { Route as AuthedSettingsUsersAddRouteImport } from "./routes/_authed/settings/users.add"
import { Route as AuthedServicesIdEditRouteImport } from "./routes/_authed/services/$id.edit"
import { Route as AuthedPatientsIdNewPaymentRouteImport } from "./routes/_authed/patients/$id/new-payment"
import { Route as AuthedPatientsIdNewConsultationRouteImport } from "./routes/_authed/patients/$id/new-consultation"
import { Route as AuthedPatientsIdNewBudgetRouteImport } from "./routes/_authed/patients/$id/new-budget"
import { Route as AuthedFinanzasPersonalCreditsCreditIdRouteImport } from "./routes/_authed/finanzas/personal-credits.$creditId"

const OnboardingRoute = OnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedRoute,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: "/verify/$id",
  path: "/verify/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServicesRoute = AuthedServicesRouteImport.update({
  id: "/services",
  path: "/services",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOperationsRoute = AuthedOperationsRouteImport.update({
  id: "/operations",
  path: "/operations",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHrRoute = AuthedHrRouteImport.update({
  id: "/hr",
  path: "/hr",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFinanzasRoute = AuthedFinanzasRouteImport.update({
  id: "/finanzas",
  path: "/finanzas",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCertificatesRoute = AuthedCertificatesRouteImport.update({
  id: "/certificates",
  path: "/certificates",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalendarRoute = AuthedCalendarRouteImport.update({
  id: "/calendar",
  path: "/calendar",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedServicesIndexRoute = AuthedServicesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedServicesRoute,
} as any)
const AuthedPatientsIndexRoute = AuthedPatientsIndexRouteImport.update({
  id: "/patients/",
  path: "/patients/",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHrIndexRoute = AuthedHrIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedHrRoute,
} as any)
const AuthedFinanzasIndexRoute = AuthedFinanzasIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedFinanzasRoute,
} as any)
const AuthedSettingsUsersRoute = AuthedSettingsUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsRolesRoute = AuthedSettingsRolesRouteImport.update({
  id: "/roles",
  path: "/roles",
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsMercadopagoRoute =
  AuthedSettingsMercadopagoRouteImport.update({
    id: "/mercadopago",
    path: "/mercadopago",
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsInventarioRoute =
  AuthedSettingsInventarioRouteImport.update({
    id: "/inventario",
    path: "/inventario",
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsCsvUploadRoute = AuthedSettingsCsvUploadRouteImport.update({
  id: "/csv-upload",
  path: "/csv-upload",
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsBackupsRoute = AuthedSettingsBackupsRouteImport.update({
  id: "/backups",
  path: "/backups",
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedServicesTemplatesRoute = AuthedServicesTemplatesRouteImport.update({
  id: "/templates",
  path: "/templates",
  getParentRoute: () => AuthedServicesRoute,
} as any)
const AuthedServicesCreateRoute = AuthedServicesCreateRouteImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => AuthedServicesRoute,
} as any)
const AuthedServicesAgendaRoute = AuthedServicesAgendaRouteImport.update({
  id: "/agenda",
  path: "/agenda",
  getParentRoute: () => AuthedServicesRoute,
} as any)
const AuthedPatientsNewRoute = AuthedPatientsNewRouteImport.update({
  id: "/patients/new",
  path: "/patients/new",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOperationsSuppliesAnalyticsRoute =
  AuthedOperationsSuppliesAnalyticsRouteImport.update({
    id: "/supplies-analytics",
    path: "/supplies-analytics",
    getParentRoute: () => AuthedOperationsRoute,
  } as any)
const AuthedOperationsSuppliesRoute =
  AuthedOperationsSuppliesRouteImport.update({
    id: "/supplies",
    path: "/supplies",
    getParentRoute: () => AuthedOperationsRoute,
  } as any)
const AuthedOperationsInventoryRoute =
  AuthedOperationsInventoryRouteImport.update({
    id: "/inventory",
    path: "/inventory",
    getParentRoute: () => AuthedOperationsRoute,
  } as any)
const AuthedHrTimesheetsRoute = AuthedHrTimesheetsRouteImport.update({
  id: "/timesheets",
  path: "/timesheets",
  getParentRoute: () => AuthedHrRoute,
} as any)
const AuthedHrReportsRoute = AuthedHrReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => AuthedHrRoute,
} as any)
const AuthedHrEmployeesRoute = AuthedHrEmployeesRouteImport.update({
  id: "/employees",
  path: "/employees",
  getParentRoute: () => AuthedHrRoute,
} as any)
const AuthedHrAuditRoute = AuthedHrAuditRouteImport.update({
  id: "/audit",
  path: "/audit",
  getParentRoute: () => AuthedHrRoute,
} as any)
const AuthedFinanzasStatisticsRoute =
  AuthedFinanzasStatisticsRouteImport.update({
    id: "/statistics",
    path: "/statistics",
    getParentRoute: () => AuthedFinanzasRoute,
  } as any)
const AuthedFinanzasProductionBalancesRoute =
  AuthedFinanzasProductionBalancesRouteImport.update({
    id: "/production-balances",
    path: "/production-balances",
    getParentRoute: () => AuthedFinanzasRoute,
  } as any)
const AuthedFinanzasPersonalCreditsRoute =
  AuthedFinanzasPersonalCreditsRouteImport.update({
    id: "/personal-credits",
    path: "/personal-credits",
    getParentRoute: () => AuthedFinanzasRoute,
  } as any)
const AuthedFinanzasPayoutsRoute = AuthedFinanzasPayoutsRouteImport.update({
  id: "/payouts",
  path: "/payouts",
  getParentRoute: () => AuthedFinanzasRoute,
} as any)
const AuthedFinanzasParticipantsRoute =
  AuthedFinanzasParticipantsRouteImport.update({
    id: "/participants",
    path: "/participants",
    getParentRoute: () => AuthedFinanzasRoute,
  } as any)
const AuthedFinanzasLoansRoute = AuthedFinanzasLoansRouteImport.update({
  id: "/loans",
  path: "/loans",
  getParentRoute: () => AuthedFinanzasRoute,
} as any)
const AuthedFinanzasLiberacionesRoute =
  AuthedFinanzasLiberacionesRouteImport.update({
    id: "/liberaciones",
    path: "/liberaciones",
    getParentRoute: () => AuthedFinanzasRoute,
  } as any)
const AuthedFinanzasDteAnalyticsRoute =
  AuthedFinanzasDteAnalyticsRouteImport.update({
    id: "/dte-analytics",
    path: "/dte-analytics",
    getParentRoute: () => AuthedFinanzasRoute,
  } as any)
const AuthedFinanzasDashboardRoute = AuthedFinanzasDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthedFinanzasRoute,
} as any)
const AuthedFinanzasDailyRoute = AuthedFinanzasDailyRouteImport.update({
  id: "/daily",
  path: "/daily",
  getParentRoute: () => AuthedFinanzasRoute,
} as any)
const AuthedFinanzasCounterpartsRoute =
  AuthedFinanzasCounterpartsRouteImport.update({
    id: "/counterparts",
    path: "/counterparts",
    getParentRoute: () => AuthedFinanzasRoute,
  } as any)
const AuthedFinanzasConciliacionesLiberacionesRoute =
  AuthedFinanzasConciliacionesLiberacionesRouteImport.update({
    id: "/conciliaciones-liberaciones",
    path: "/conciliaciones-liberaciones",
    getParentRoute: () => AuthedFinanzasRoute,
  } as any)
const AuthedFinanzasConciliacionesRoute =
  AuthedFinanzasConciliacionesRouteImport.update({
    id: "/conciliaciones",
    path: "/conciliaciones",
    getParentRoute: () => AuthedFinanzasRoute,
  } as any)
const AuthedDevRoutesAuditRoute = AuthedDevRoutesAuditRouteImport.update({
  id: "/dev/routes-audit",
  path: "/dev/routes-audit",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCertificatesMedicalRoute =
  AuthedCertificatesMedicalRouteImport.update({
    id: "/medical",
    path: "/medical",
    getParentRoute: () => AuthedCertificatesRoute,
  } as any)
const AuthedCalendarSyncHistoryRoute =
  AuthedCalendarSyncHistoryRouteImport.update({
    id: "/sync-history",
    path: "/sync-history",
    getParentRoute: () => AuthedCalendarRoute,
  } as any)
const AuthedCalendarScheduleRoute = AuthedCalendarScheduleRouteImport.update({
  id: "/schedule",
  path: "/schedule",
  getParentRoute: () => AuthedCalendarRoute,
} as any)
const AuthedCalendarHeatmapRoute = AuthedCalendarHeatmapRouteImport.update({
  id: "/heatmap",
  path: "/heatmap",
  getParentRoute: () => AuthedCalendarRoute,
} as any)
const AuthedCalendarDailyRoute = AuthedCalendarDailyRouteImport.update({
  id: "/daily",
  path: "/daily",
  getParentRoute: () => AuthedCalendarRoute,
} as any)
const AuthedCalendarClassifyRoute = AuthedCalendarClassifyRouteImport.update({
  id: "/classify",
  path: "/classify",
  getParentRoute: () => AuthedCalendarRoute,
} as any)
const AuthedPatientsIdIndexRoute = AuthedPatientsIdIndexRouteImport.update({
  id: "/patients/$id/",
  path: "/patients/$id/",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsUsersAddRoute = AuthedSettingsUsersAddRouteImport.update({
  id: "/add",
  path: "/add",
  getParentRoute: () => AuthedSettingsUsersRoute,
} as any)
const AuthedServicesIdEditRoute = AuthedServicesIdEditRouteImport.update({
  id: "/$id/edit",
  path: "/$id/edit",
  getParentRoute: () => AuthedServicesRoute,
} as any)
const AuthedPatientsIdNewPaymentRoute =
  AuthedPatientsIdNewPaymentRouteImport.update({
    id: "/patients/$id/new-payment",
    path: "/patients/$id/new-payment",
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPatientsIdNewConsultationRoute =
  AuthedPatientsIdNewConsultationRouteImport.update({
    id: "/patients/$id/new-consultation",
    path: "/patients/$id/new-consultation",
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPatientsIdNewBudgetRoute =
  AuthedPatientsIdNewBudgetRouteImport.update({
    id: "/patients/$id/new-budget",
    path: "/patients/$id/new-budget",
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedFinanzasPersonalCreditsCreditIdRoute =
  AuthedFinanzasPersonalCreditsCreditIdRouteImport.update({
    id: "/$creditId",
    path: "/$creditId",
    getParentRoute: () => AuthedFinanzasPersonalCreditsRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof AuthedIndexRoute
  "/login": typeof LoginRoute
  "/onboarding": typeof OnboardingRoute
  "/account": typeof AuthedAccountRoute
  "/calendar": typeof AuthedCalendarRouteWithChildren
  "/certificates": typeof AuthedCertificatesRouteWithChildren
  "/finanzas": typeof AuthedFinanzasRouteWithChildren
  "/hr": typeof AuthedHrRouteWithChildren
  "/operations": typeof AuthedOperationsRouteWithChildren
  "/services": typeof AuthedServicesRouteWithChildren
  "/settings": typeof AuthedSettingsRouteWithChildren
  "/verify/$id": typeof VerifyIdRoute
  "/calendar/classify": typeof AuthedCalendarClassifyRoute
  "/calendar/daily": typeof AuthedCalendarDailyRoute
  "/calendar/heatmap": typeof AuthedCalendarHeatmapRoute
  "/calendar/schedule": typeof AuthedCalendarScheduleRoute
  "/calendar/sync-history": typeof AuthedCalendarSyncHistoryRoute
  "/certificates/medical": typeof AuthedCertificatesMedicalRoute
  "/dev/routes-audit": typeof AuthedDevRoutesAuditRoute
  "/finanzas/conciliaciones": typeof AuthedFinanzasConciliacionesRoute
  "/finanzas/conciliaciones-liberaciones": typeof AuthedFinanzasConciliacionesLiberacionesRoute
  "/finanzas/counterparts": typeof AuthedFinanzasCounterpartsRoute
  "/finanzas/daily": typeof AuthedFinanzasDailyRoute
  "/finanzas/dashboard": typeof AuthedFinanzasDashboardRoute
  "/finanzas/dte-analytics": typeof AuthedFinanzasDteAnalyticsRoute
  "/finanzas/liberaciones": typeof AuthedFinanzasLiberacionesRoute
  "/finanzas/loans": typeof AuthedFinanzasLoansRoute
  "/finanzas/participants": typeof AuthedFinanzasParticipantsRoute
  "/finanzas/payouts": typeof AuthedFinanzasPayoutsRoute
  "/finanzas/personal-credits": typeof AuthedFinanzasPersonalCreditsRouteWithChildren
  "/finanzas/production-balances": typeof AuthedFinanzasProductionBalancesRoute
  "/finanzas/statistics": typeof AuthedFinanzasStatisticsRoute
  "/hr/audit": typeof AuthedHrAuditRoute
  "/hr/employees": typeof AuthedHrEmployeesRoute
  "/hr/reports": typeof AuthedHrReportsRoute
  "/hr/timesheets": typeof AuthedHrTimesheetsRoute
  "/operations/inventory": typeof AuthedOperationsInventoryRoute
  "/operations/supplies": typeof AuthedOperationsSuppliesRoute
  "/operations/supplies-analytics": typeof AuthedOperationsSuppliesAnalyticsRoute
  "/patients/new": typeof AuthedPatientsNewRoute
  "/services/agenda": typeof AuthedServicesAgendaRoute
  "/services/create": typeof AuthedServicesCreateRoute
  "/services/templates": typeof AuthedServicesTemplatesRoute
  "/settings/backups": typeof AuthedSettingsBackupsRoute
  "/settings/csv-upload": typeof AuthedSettingsCsvUploadRoute
  "/settings/inventario": typeof AuthedSettingsInventarioRoute
  "/settings/mercadopago": typeof AuthedSettingsMercadopagoRoute
  "/settings/roles": typeof AuthedSettingsRolesRoute
  "/settings/users": typeof AuthedSettingsUsersRouteWithChildren
  "/finanzas/": typeof AuthedFinanzasIndexRoute
  "/hr/": typeof AuthedHrIndexRoute
  "/patients/": typeof AuthedPatientsIndexRoute
  "/services/": typeof AuthedServicesIndexRoute
  "/settings/": typeof AuthedSettingsIndexRoute
  "/finanzas/personal-credits/$creditId": typeof AuthedFinanzasPersonalCreditsCreditIdRoute
  "/patients/$id/new-budget": typeof AuthedPatientsIdNewBudgetRoute
  "/patients/$id/new-consultation": typeof AuthedPatientsIdNewConsultationRoute
  "/patients/$id/new-payment": typeof AuthedPatientsIdNewPaymentRoute
  "/services/$id/edit": typeof AuthedServicesIdEditRoute
  "/settings/users/add": typeof AuthedSettingsUsersAddRoute
  "/patients/$id/": typeof AuthedPatientsIdIndexRoute
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute
  "/onboarding": typeof OnboardingRoute
  "/account": typeof AuthedAccountRoute
  "/calendar": typeof AuthedCalendarRouteWithChildren
  "/certificates": typeof AuthedCertificatesRouteWithChildren
  "/operations": typeof AuthedOperationsRouteWithChildren
  "/verify/$id": typeof VerifyIdRoute
  "/": typeof AuthedIndexRoute
  "/calendar/classify": typeof AuthedCalendarClassifyRoute
  "/calendar/daily": typeof AuthedCalendarDailyRoute
  "/calendar/heatmap": typeof AuthedCalendarHeatmapRoute
  "/calendar/schedule": typeof AuthedCalendarScheduleRoute
  "/calendar/sync-history": typeof AuthedCalendarSyncHistoryRoute
  "/certificates/medical": typeof AuthedCertificatesMedicalRoute
  "/dev/routes-audit": typeof AuthedDevRoutesAuditRoute
  "/finanzas/conciliaciones": typeof AuthedFinanzasConciliacionesRoute
  "/finanzas/conciliaciones-liberaciones": typeof AuthedFinanzasConciliacionesLiberacionesRoute
  "/finanzas/counterparts": typeof AuthedFinanzasCounterpartsRoute
  "/finanzas/daily": typeof AuthedFinanzasDailyRoute
  "/finanzas/dashboard": typeof AuthedFinanzasDashboardRoute
  "/finanzas/dte-analytics": typeof AuthedFinanzasDteAnalyticsRoute
  "/finanzas/liberaciones": typeof AuthedFinanzasLiberacionesRoute
  "/finanzas/loans": typeof AuthedFinanzasLoansRoute
  "/finanzas/participants": typeof AuthedFinanzasParticipantsRoute
  "/finanzas/payouts": typeof AuthedFinanzasPayoutsRoute
  "/finanzas/personal-credits": typeof AuthedFinanzasPersonalCreditsRouteWithChildren
  "/finanzas/production-balances": typeof AuthedFinanzasProductionBalancesRoute
  "/finanzas/statistics": typeof AuthedFinanzasStatisticsRoute
  "/hr/audit": typeof AuthedHrAuditRoute
  "/hr/employees": typeof AuthedHrEmployeesRoute
  "/hr/reports": typeof AuthedHrReportsRoute
  "/hr/timesheets": typeof AuthedHrTimesheetsRoute
  "/operations/inventory": typeof AuthedOperationsInventoryRoute
  "/operations/supplies": typeof AuthedOperationsSuppliesRoute
  "/operations/supplies-analytics": typeof AuthedOperationsSuppliesAnalyticsRoute
  "/patients/new": typeof AuthedPatientsNewRoute
  "/services/agenda": typeof AuthedServicesAgendaRoute
  "/services/create": typeof AuthedServicesCreateRoute
  "/services/templates": typeof AuthedServicesTemplatesRoute
  "/settings/backups": typeof AuthedSettingsBackupsRoute
  "/settings/csv-upload": typeof AuthedSettingsCsvUploadRoute
  "/settings/inventario": typeof AuthedSettingsInventarioRoute
  "/settings/mercadopago": typeof AuthedSettingsMercadopagoRoute
  "/settings/roles": typeof AuthedSettingsRolesRoute
  "/settings/users": typeof AuthedSettingsUsersRouteWithChildren
  "/finanzas": typeof AuthedFinanzasIndexRoute
  "/hr": typeof AuthedHrIndexRoute
  "/patients": typeof AuthedPatientsIndexRoute
  "/services": typeof AuthedServicesIndexRoute
  "/settings": typeof AuthedSettingsIndexRoute
  "/finanzas/personal-credits/$creditId": typeof AuthedFinanzasPersonalCreditsCreditIdRoute
  "/patients/$id/new-budget": typeof AuthedPatientsIdNewBudgetRoute
  "/patients/$id/new-consultation": typeof AuthedPatientsIdNewConsultationRoute
  "/patients/$id/new-payment": typeof AuthedPatientsIdNewPaymentRoute
  "/services/$id/edit": typeof AuthedServicesIdEditRoute
  "/settings/users/add": typeof AuthedSettingsUsersAddRoute
  "/patients/$id": typeof AuthedPatientsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_authed": typeof AuthedRouteWithChildren
  "/login": typeof LoginRoute
  "/onboarding": typeof OnboardingRoute
  "/_authed/account": typeof AuthedAccountRoute
  "/_authed/calendar": typeof AuthedCalendarRouteWithChildren
  "/_authed/certificates": typeof AuthedCertificatesRouteWithChildren
  "/_authed/finanzas": typeof AuthedFinanzasRouteWithChildren
  "/_authed/hr": typeof AuthedHrRouteWithChildren
  "/_authed/operations": typeof AuthedOperationsRouteWithChildren
  "/_authed/services": typeof AuthedServicesRouteWithChildren
  "/_authed/settings": typeof AuthedSettingsRouteWithChildren
  "/verify/$id": typeof VerifyIdRoute
  "/_authed/": typeof AuthedIndexRoute
  "/_authed/calendar/classify": typeof AuthedCalendarClassifyRoute
  "/_authed/calendar/daily": typeof AuthedCalendarDailyRoute
  "/_authed/calendar/heatmap": typeof AuthedCalendarHeatmapRoute
  "/_authed/calendar/schedule": typeof AuthedCalendarScheduleRoute
  "/_authed/calendar/sync-history": typeof AuthedCalendarSyncHistoryRoute
  "/_authed/certificates/medical": typeof AuthedCertificatesMedicalRoute
  "/_authed/dev/routes-audit": typeof AuthedDevRoutesAuditRoute
  "/_authed/finanzas/conciliaciones": typeof AuthedFinanzasConciliacionesRoute
  "/_authed/finanzas/conciliaciones-liberaciones": typeof AuthedFinanzasConciliacionesLiberacionesRoute
  "/_authed/finanzas/counterparts": typeof AuthedFinanzasCounterpartsRoute
  "/_authed/finanzas/daily": typeof AuthedFinanzasDailyRoute
  "/_authed/finanzas/dashboard": typeof AuthedFinanzasDashboardRoute
  "/_authed/finanzas/dte-analytics": typeof AuthedFinanzasDteAnalyticsRoute
  "/_authed/finanzas/liberaciones": typeof AuthedFinanzasLiberacionesRoute
  "/_authed/finanzas/loans": typeof AuthedFinanzasLoansRoute
  "/_authed/finanzas/participants": typeof AuthedFinanzasParticipantsRoute
  "/_authed/finanzas/payouts": typeof AuthedFinanzasPayoutsRoute
  "/_authed/finanzas/personal-credits": typeof AuthedFinanzasPersonalCreditsRouteWithChildren
  "/_authed/finanzas/production-balances": typeof AuthedFinanzasProductionBalancesRoute
  "/_authed/finanzas/statistics": typeof AuthedFinanzasStatisticsRoute
  "/_authed/hr/audit": typeof AuthedHrAuditRoute
  "/_authed/hr/employees": typeof AuthedHrEmployeesRoute
  "/_authed/hr/reports": typeof AuthedHrReportsRoute
  "/_authed/hr/timesheets": typeof AuthedHrTimesheetsRoute
  "/_authed/operations/inventory": typeof AuthedOperationsInventoryRoute
  "/_authed/operations/supplies": typeof AuthedOperationsSuppliesRoute
  "/_authed/operations/supplies-analytics": typeof AuthedOperationsSuppliesAnalyticsRoute
  "/_authed/patients/new": typeof AuthedPatientsNewRoute
  "/_authed/services/agenda": typeof AuthedServicesAgendaRoute
  "/_authed/services/create": typeof AuthedServicesCreateRoute
  "/_authed/services/templates": typeof AuthedServicesTemplatesRoute
  "/_authed/settings/backups": typeof AuthedSettingsBackupsRoute
  "/_authed/settings/csv-upload": typeof AuthedSettingsCsvUploadRoute
  "/_authed/settings/inventario": typeof AuthedSettingsInventarioRoute
  "/_authed/settings/mercadopago": typeof AuthedSettingsMercadopagoRoute
  "/_authed/settings/roles": typeof AuthedSettingsRolesRoute
  "/_authed/settings/users": typeof AuthedSettingsUsersRouteWithChildren
  "/_authed/finanzas/": typeof AuthedFinanzasIndexRoute
  "/_authed/hr/": typeof AuthedHrIndexRoute
  "/_authed/patients/": typeof AuthedPatientsIndexRoute
  "/_authed/services/": typeof AuthedServicesIndexRoute
  "/_authed/settings/": typeof AuthedSettingsIndexRoute
  "/_authed/finanzas/personal-credits/$creditId": typeof AuthedFinanzasPersonalCreditsCreditIdRoute
  "/_authed/patients/$id/new-budget": typeof AuthedPatientsIdNewBudgetRoute
  "/_authed/patients/$id/new-consultation": typeof AuthedPatientsIdNewConsultationRoute
  "/_authed/patients/$id/new-payment": typeof AuthedPatientsIdNewPaymentRoute
  "/_authed/services/$id/edit": typeof AuthedServicesIdEditRoute
  "/_authed/settings/users/add": typeof AuthedSettingsUsersAddRoute
  "/_authed/patients/$id/": typeof AuthedPatientsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/onboarding"
    | "/account"
    | "/calendar"
    | "/certificates"
    | "/finanzas"
    | "/hr"
    | "/operations"
    | "/services"
    | "/settings"
    | "/verify/$id"
    | "/calendar/classify"
    | "/calendar/daily"
    | "/calendar/heatmap"
    | "/calendar/schedule"
    | "/calendar/sync-history"
    | "/certificates/medical"
    | "/dev/routes-audit"
    | "/finanzas/conciliaciones"
    | "/finanzas/conciliaciones-liberaciones"
    | "/finanzas/counterparts"
    | "/finanzas/daily"
    | "/finanzas/dashboard"
    | "/finanzas/dte-analytics"
    | "/finanzas/liberaciones"
    | "/finanzas/loans"
    | "/finanzas/participants"
    | "/finanzas/payouts"
    | "/finanzas/personal-credits"
    | "/finanzas/production-balances"
    | "/finanzas/statistics"
    | "/hr/audit"
    | "/hr/employees"
    | "/hr/reports"
    | "/hr/timesheets"
    | "/operations/inventory"
    | "/operations/supplies"
    | "/operations/supplies-analytics"
    | "/patients/new"
    | "/services/agenda"
    | "/services/create"
    | "/services/templates"
    | "/settings/backups"
    | "/settings/csv-upload"
    | "/settings/inventario"
    | "/settings/mercadopago"
    | "/settings/roles"
    | "/settings/users"
    | "/finanzas/"
    | "/hr/"
    | "/patients/"
    | "/services/"
    | "/settings/"
    | "/finanzas/personal-credits/$creditId"
    | "/patients/$id/new-budget"
    | "/patients/$id/new-consultation"
    | "/patients/$id/new-payment"
    | "/services/$id/edit"
    | "/settings/users/add"
    | "/patients/$id/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/login"
    | "/onboarding"
    | "/account"
    | "/calendar"
    | "/certificates"
    | "/operations"
    | "/verify/$id"
    | "/"
    | "/calendar/classify"
    | "/calendar/daily"
    | "/calendar/heatmap"
    | "/calendar/schedule"
    | "/calendar/sync-history"
    | "/certificates/medical"
    | "/dev/routes-audit"
    | "/finanzas/conciliaciones"
    | "/finanzas/conciliaciones-liberaciones"
    | "/finanzas/counterparts"
    | "/finanzas/daily"
    | "/finanzas/dashboard"
    | "/finanzas/dte-analytics"
    | "/finanzas/liberaciones"
    | "/finanzas/loans"
    | "/finanzas/participants"
    | "/finanzas/payouts"
    | "/finanzas/personal-credits"
    | "/finanzas/production-balances"
    | "/finanzas/statistics"
    | "/hr/audit"
    | "/hr/employees"
    | "/hr/reports"
    | "/hr/timesheets"
    | "/operations/inventory"
    | "/operations/supplies"
    | "/operations/supplies-analytics"
    | "/patients/new"
    | "/services/agenda"
    | "/services/create"
    | "/services/templates"
    | "/settings/backups"
    | "/settings/csv-upload"
    | "/settings/inventario"
    | "/settings/mercadopago"
    | "/settings/roles"
    | "/settings/users"
    | "/finanzas"
    | "/hr"
    | "/patients"
    | "/services"
    | "/settings"
    | "/finanzas/personal-credits/$creditId"
    | "/patients/$id/new-budget"
    | "/patients/$id/new-consultation"
    | "/patients/$id/new-payment"
    | "/services/$id/edit"
    | "/settings/users/add"
    | "/patients/$id"
  id:
    | "__root__"
    | "/_authed"
    | "/login"
    | "/onboarding"
    | "/_authed/account"
    | "/_authed/calendar"
    | "/_authed/certificates"
    | "/_authed/finanzas"
    | "/_authed/hr"
    | "/_authed/operations"
    | "/_authed/services"
    | "/_authed/settings"
    | "/verify/$id"
    | "/_authed/"
    | "/_authed/calendar/classify"
    | "/_authed/calendar/daily"
    | "/_authed/calendar/heatmap"
    | "/_authed/calendar/schedule"
    | "/_authed/calendar/sync-history"
    | "/_authed/certificates/medical"
    | "/_authed/dev/routes-audit"
    | "/_authed/finanzas/conciliaciones"
    | "/_authed/finanzas/conciliaciones-liberaciones"
    | "/_authed/finanzas/counterparts"
    | "/_authed/finanzas/daily"
    | "/_authed/finanzas/dashboard"
    | "/_authed/finanzas/dte-analytics"
    | "/_authed/finanzas/liberaciones"
    | "/_authed/finanzas/loans"
    | "/_authed/finanzas/participants"
    | "/_authed/finanzas/payouts"
    | "/_authed/finanzas/personal-credits"
    | "/_authed/finanzas/production-balances"
    | "/_authed/finanzas/statistics"
    | "/_authed/hr/audit"
    | "/_authed/hr/employees"
    | "/_authed/hr/reports"
    | "/_authed/hr/timesheets"
    | "/_authed/operations/inventory"
    | "/_authed/operations/supplies"
    | "/_authed/operations/supplies-analytics"
    | "/_authed/patients/new"
    | "/_authed/services/agenda"
    | "/_authed/services/create"
    | "/_authed/services/templates"
    | "/_authed/settings/backups"
    | "/_authed/settings/csv-upload"
    | "/_authed/settings/inventario"
    | "/_authed/settings/mercadopago"
    | "/_authed/settings/roles"
    | "/_authed/settings/users"
    | "/_authed/finanzas/"
    | "/_authed/hr/"
    | "/_authed/patients/"
    | "/_authed/services/"
    | "/_authed/settings/"
    | "/_authed/finanzas/personal-credits/$creditId"
    | "/_authed/patients/$id/new-budget"
    | "/_authed/patients/$id/new-consultation"
    | "/_authed/patients/$id/new-payment"
    | "/_authed/services/$id/edit"
    | "/_authed/settings/users/add"
    | "/_authed/patients/$id/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  VerifyIdRoute: typeof VerifyIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/onboarding": {
      id: "/onboarding"
      path: "/onboarding"
      fullPath: "/onboarding"
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed": {
      id: "/_authed"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed/": {
      id: "/_authed/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/verify/$id": {
      id: "/verify/$id"
      path: "/verify/$id"
      fullPath: "/verify/$id"
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed/settings": {
      id: "/_authed/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/services": {
      id: "/_authed/services"
      path: "/services"
      fullPath: "/services"
      preLoaderRoute: typeof AuthedServicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/operations": {
      id: "/_authed/operations"
      path: "/operations"
      fullPath: "/operations"
      preLoaderRoute: typeof AuthedOperationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/hr": {
      id: "/_authed/hr"
      path: "/hr"
      fullPath: "/hr"
      preLoaderRoute: typeof AuthedHrRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/finanzas": {
      id: "/_authed/finanzas"
      path: "/finanzas"
      fullPath: "/finanzas"
      preLoaderRoute: typeof AuthedFinanzasRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/certificates": {
      id: "/_authed/certificates"
      path: "/certificates"
      fullPath: "/certificates"
      preLoaderRoute: typeof AuthedCertificatesRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/calendar": {
      id: "/_authed/calendar"
      path: "/calendar"
      fullPath: "/calendar"
      preLoaderRoute: typeof AuthedCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/account": {
      id: "/_authed/account"
      path: "/account"
      fullPath: "/account"
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/settings/": {
      id: "/_authed/settings/"
      path: "/"
      fullPath: "/settings/"
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/services/": {
      id: "/_authed/services/"
      path: "/"
      fullPath: "/services/"
      preLoaderRoute: typeof AuthedServicesIndexRouteImport
      parentRoute: typeof AuthedServicesRoute
    }
    "/_authed/patients/": {
      id: "/_authed/patients/"
      path: "/patients"
      fullPath: "/patients/"
      preLoaderRoute: typeof AuthedPatientsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/hr/": {
      id: "/_authed/hr/"
      path: "/"
      fullPath: "/hr/"
      preLoaderRoute: typeof AuthedHrIndexRouteImport
      parentRoute: typeof AuthedHrRoute
    }
    "/_authed/finanzas/": {
      id: "/_authed/finanzas/"
      path: "/"
      fullPath: "/finanzas/"
      preLoaderRoute: typeof AuthedFinanzasIndexRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/settings/users": {
      id: "/_authed/settings/users"
      path: "/users"
      fullPath: "/settings/users"
      preLoaderRoute: typeof AuthedSettingsUsersRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/settings/roles": {
      id: "/_authed/settings/roles"
      path: "/roles"
      fullPath: "/settings/roles"
      preLoaderRoute: typeof AuthedSettingsRolesRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/settings/mercadopago": {
      id: "/_authed/settings/mercadopago"
      path: "/mercadopago"
      fullPath: "/settings/mercadopago"
      preLoaderRoute: typeof AuthedSettingsMercadopagoRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/settings/inventario": {
      id: "/_authed/settings/inventario"
      path: "/inventario"
      fullPath: "/settings/inventario"
      preLoaderRoute: typeof AuthedSettingsInventarioRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/settings/csv-upload": {
      id: "/_authed/settings/csv-upload"
      path: "/csv-upload"
      fullPath: "/settings/csv-upload"
      preLoaderRoute: typeof AuthedSettingsCsvUploadRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/settings/backups": {
      id: "/_authed/settings/backups"
      path: "/backups"
      fullPath: "/settings/backups"
      preLoaderRoute: typeof AuthedSettingsBackupsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    "/_authed/services/templates": {
      id: "/_authed/services/templates"
      path: "/templates"
      fullPath: "/services/templates"
      preLoaderRoute: typeof AuthedServicesTemplatesRouteImport
      parentRoute: typeof AuthedServicesRoute
    }
    "/_authed/services/create": {
      id: "/_authed/services/create"
      path: "/create"
      fullPath: "/services/create"
      preLoaderRoute: typeof AuthedServicesCreateRouteImport
      parentRoute: typeof AuthedServicesRoute
    }
    "/_authed/services/agenda": {
      id: "/_authed/services/agenda"
      path: "/agenda"
      fullPath: "/services/agenda"
      preLoaderRoute: typeof AuthedServicesAgendaRouteImport
      parentRoute: typeof AuthedServicesRoute
    }
    "/_authed/patients/new": {
      id: "/_authed/patients/new"
      path: "/patients/new"
      fullPath: "/patients/new"
      preLoaderRoute: typeof AuthedPatientsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/operations/supplies-analytics": {
      id: "/_authed/operations/supplies-analytics"
      path: "/supplies-analytics"
      fullPath: "/operations/supplies-analytics"
      preLoaderRoute: typeof AuthedOperationsSuppliesAnalyticsRouteImport
      parentRoute: typeof AuthedOperationsRoute
    }
    "/_authed/operations/supplies": {
      id: "/_authed/operations/supplies"
      path: "/supplies"
      fullPath: "/operations/supplies"
      preLoaderRoute: typeof AuthedOperationsSuppliesRouteImport
      parentRoute: typeof AuthedOperationsRoute
    }
    "/_authed/operations/inventory": {
      id: "/_authed/operations/inventory"
      path: "/inventory"
      fullPath: "/operations/inventory"
      preLoaderRoute: typeof AuthedOperationsInventoryRouteImport
      parentRoute: typeof AuthedOperationsRoute
    }
    "/_authed/hr/timesheets": {
      id: "/_authed/hr/timesheets"
      path: "/timesheets"
      fullPath: "/hr/timesheets"
      preLoaderRoute: typeof AuthedHrTimesheetsRouteImport
      parentRoute: typeof AuthedHrRoute
    }
    "/_authed/hr/reports": {
      id: "/_authed/hr/reports"
      path: "/reports"
      fullPath: "/hr/reports"
      preLoaderRoute: typeof AuthedHrReportsRouteImport
      parentRoute: typeof AuthedHrRoute
    }
    "/_authed/hr/employees": {
      id: "/_authed/hr/employees"
      path: "/employees"
      fullPath: "/hr/employees"
      preLoaderRoute: typeof AuthedHrEmployeesRouteImport
      parentRoute: typeof AuthedHrRoute
    }
    "/_authed/hr/audit": {
      id: "/_authed/hr/audit"
      path: "/audit"
      fullPath: "/hr/audit"
      preLoaderRoute: typeof AuthedHrAuditRouteImport
      parentRoute: typeof AuthedHrRoute
    }
    "/_authed/finanzas/statistics": {
      id: "/_authed/finanzas/statistics"
      path: "/statistics"
      fullPath: "/finanzas/statistics"
      preLoaderRoute: typeof AuthedFinanzasStatisticsRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/production-balances": {
      id: "/_authed/finanzas/production-balances"
      path: "/production-balances"
      fullPath: "/finanzas/production-balances"
      preLoaderRoute: typeof AuthedFinanzasProductionBalancesRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/personal-credits": {
      id: "/_authed/finanzas/personal-credits"
      path: "/personal-credits"
      fullPath: "/finanzas/personal-credits"
      preLoaderRoute: typeof AuthedFinanzasPersonalCreditsRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/payouts": {
      id: "/_authed/finanzas/payouts"
      path: "/payouts"
      fullPath: "/finanzas/payouts"
      preLoaderRoute: typeof AuthedFinanzasPayoutsRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/participants": {
      id: "/_authed/finanzas/participants"
      path: "/participants"
      fullPath: "/finanzas/participants"
      preLoaderRoute: typeof AuthedFinanzasParticipantsRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/loans": {
      id: "/_authed/finanzas/loans"
      path: "/loans"
      fullPath: "/finanzas/loans"
      preLoaderRoute: typeof AuthedFinanzasLoansRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/liberaciones": {
      id: "/_authed/finanzas/liberaciones"
      path: "/liberaciones"
      fullPath: "/finanzas/liberaciones"
      preLoaderRoute: typeof AuthedFinanzasLiberacionesRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/dte-analytics": {
      id: "/_authed/finanzas/dte-analytics"
      path: "/dte-analytics"
      fullPath: "/finanzas/dte-analytics"
      preLoaderRoute: typeof AuthedFinanzasDteAnalyticsRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/dashboard": {
      id: "/_authed/finanzas/dashboard"
      path: "/dashboard"
      fullPath: "/finanzas/dashboard"
      preLoaderRoute: typeof AuthedFinanzasDashboardRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/daily": {
      id: "/_authed/finanzas/daily"
      path: "/daily"
      fullPath: "/finanzas/daily"
      preLoaderRoute: typeof AuthedFinanzasDailyRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/counterparts": {
      id: "/_authed/finanzas/counterparts"
      path: "/counterparts"
      fullPath: "/finanzas/counterparts"
      preLoaderRoute: typeof AuthedFinanzasCounterpartsRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/conciliaciones-liberaciones": {
      id: "/_authed/finanzas/conciliaciones-liberaciones"
      path: "/conciliaciones-liberaciones"
      fullPath: "/finanzas/conciliaciones-liberaciones"
      preLoaderRoute: typeof AuthedFinanzasConciliacionesLiberacionesRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/finanzas/conciliaciones": {
      id: "/_authed/finanzas/conciliaciones"
      path: "/conciliaciones"
      fullPath: "/finanzas/conciliaciones"
      preLoaderRoute: typeof AuthedFinanzasConciliacionesRouteImport
      parentRoute: typeof AuthedFinanzasRoute
    }
    "/_authed/dev/routes-audit": {
      id: "/_authed/dev/routes-audit"
      path: "/dev/routes-audit"
      fullPath: "/dev/routes-audit"
      preLoaderRoute: typeof AuthedDevRoutesAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/certificates/medical": {
      id: "/_authed/certificates/medical"
      path: "/medical"
      fullPath: "/certificates/medical"
      preLoaderRoute: typeof AuthedCertificatesMedicalRouteImport
      parentRoute: typeof AuthedCertificatesRoute
    }
    "/_authed/calendar/sync-history": {
      id: "/_authed/calendar/sync-history"
      path: "/sync-history"
      fullPath: "/calendar/sync-history"
      preLoaderRoute: typeof AuthedCalendarSyncHistoryRouteImport
      parentRoute: typeof AuthedCalendarRoute
    }
    "/_authed/calendar/schedule": {
      id: "/_authed/calendar/schedule"
      path: "/schedule"
      fullPath: "/calendar/schedule"
      preLoaderRoute: typeof AuthedCalendarScheduleRouteImport
      parentRoute: typeof AuthedCalendarRoute
    }
    "/_authed/calendar/heatmap": {
      id: "/_authed/calendar/heatmap"
      path: "/heatmap"
      fullPath: "/calendar/heatmap"
      preLoaderRoute: typeof AuthedCalendarHeatmapRouteImport
      parentRoute: typeof AuthedCalendarRoute
    }
    "/_authed/calendar/daily": {
      id: "/_authed/calendar/daily"
      path: "/daily"
      fullPath: "/calendar/daily"
      preLoaderRoute: typeof AuthedCalendarDailyRouteImport
      parentRoute: typeof AuthedCalendarRoute
    }
    "/_authed/calendar/classify": {
      id: "/_authed/calendar/classify"
      path: "/classify"
      fullPath: "/calendar/classify"
      preLoaderRoute: typeof AuthedCalendarClassifyRouteImport
      parentRoute: typeof AuthedCalendarRoute
    }
    "/_authed/patients/$id/": {
      id: "/_authed/patients/$id/"
      path: "/patients/$id"
      fullPath: "/patients/$id/"
      preLoaderRoute: typeof AuthedPatientsIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/settings/users/add": {
      id: "/_authed/settings/users/add"
      path: "/add"
      fullPath: "/settings/users/add"
      preLoaderRoute: typeof AuthedSettingsUsersAddRouteImport
      parentRoute: typeof AuthedSettingsUsersRoute
    }
    "/_authed/services/$id/edit": {
      id: "/_authed/services/$id/edit"
      path: "/$id/edit"
      fullPath: "/services/$id/edit"
      preLoaderRoute: typeof AuthedServicesIdEditRouteImport
      parentRoute: typeof AuthedServicesRoute
    }
    "/_authed/patients/$id/new-payment": {
      id: "/_authed/patients/$id/new-payment"
      path: "/patients/$id/new-payment"
      fullPath: "/patients/$id/new-payment"
      preLoaderRoute: typeof AuthedPatientsIdNewPaymentRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/patients/$id/new-consultation": {
      id: "/_authed/patients/$id/new-consultation"
      path: "/patients/$id/new-consultation"
      fullPath: "/patients/$id/new-consultation"
      preLoaderRoute: typeof AuthedPatientsIdNewConsultationRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/patients/$id/new-budget": {
      id: "/_authed/patients/$id/new-budget"
      path: "/patients/$id/new-budget"
      fullPath: "/patients/$id/new-budget"
      preLoaderRoute: typeof AuthedPatientsIdNewBudgetRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/finanzas/personal-credits/$creditId": {
      id: "/_authed/finanzas/personal-credits/$creditId"
      path: "/$creditId"
      fullPath: "/finanzas/personal-credits/$creditId"
      preLoaderRoute: typeof AuthedFinanzasPersonalCreditsCreditIdRouteImport
      parentRoute: typeof AuthedFinanzasPersonalCreditsRoute
    }
  }
}

interface AuthedCalendarRouteChildren {
  AuthedCalendarClassifyRoute: typeof AuthedCalendarClassifyRoute
  AuthedCalendarDailyRoute: typeof AuthedCalendarDailyRoute
  AuthedCalendarHeatmapRoute: typeof AuthedCalendarHeatmapRoute
  AuthedCalendarScheduleRoute: typeof AuthedCalendarScheduleRoute
  AuthedCalendarSyncHistoryRoute: typeof AuthedCalendarSyncHistoryRoute
}

const AuthedCalendarRouteChildren: AuthedCalendarRouteChildren = {
  AuthedCalendarClassifyRoute: AuthedCalendarClassifyRoute,
  AuthedCalendarDailyRoute: AuthedCalendarDailyRoute,
  AuthedCalendarHeatmapRoute: AuthedCalendarHeatmapRoute,
  AuthedCalendarScheduleRoute: AuthedCalendarScheduleRoute,
  AuthedCalendarSyncHistoryRoute: AuthedCalendarSyncHistoryRoute,
}

const AuthedCalendarRouteWithChildren = AuthedCalendarRoute._addFileChildren(
  AuthedCalendarRouteChildren,
)

interface AuthedCertificatesRouteChildren {
  AuthedCertificatesMedicalRoute: typeof AuthedCertificatesMedicalRoute
}

const AuthedCertificatesRouteChildren: AuthedCertificatesRouteChildren = {
  AuthedCertificatesMedicalRoute: AuthedCertificatesMedicalRoute,
}

const AuthedCertificatesRouteWithChildren =
  AuthedCertificatesRoute._addFileChildren(AuthedCertificatesRouteChildren)

interface AuthedFinanzasPersonalCreditsRouteChildren {
  AuthedFinanzasPersonalCreditsCreditIdRoute: typeof AuthedFinanzasPersonalCreditsCreditIdRoute
}

const AuthedFinanzasPersonalCreditsRouteChildren: AuthedFinanzasPersonalCreditsRouteChildren =
  {
    AuthedFinanzasPersonalCreditsCreditIdRoute:
      AuthedFinanzasPersonalCreditsCreditIdRoute,
  }

const AuthedFinanzasPersonalCreditsRouteWithChildren =
  AuthedFinanzasPersonalCreditsRoute._addFileChildren(
    AuthedFinanzasPersonalCreditsRouteChildren,
  )

interface AuthedFinanzasRouteChildren {
  AuthedFinanzasConciliacionesRoute: typeof AuthedFinanzasConciliacionesRoute
  AuthedFinanzasConciliacionesLiberacionesRoute: typeof AuthedFinanzasConciliacionesLiberacionesRoute
  AuthedFinanzasCounterpartsRoute: typeof AuthedFinanzasCounterpartsRoute
  AuthedFinanzasDailyRoute: typeof AuthedFinanzasDailyRoute
  AuthedFinanzasDashboardRoute: typeof AuthedFinanzasDashboardRoute
  AuthedFinanzasDteAnalyticsRoute: typeof AuthedFinanzasDteAnalyticsRoute
  AuthedFinanzasLiberacionesRoute: typeof AuthedFinanzasLiberacionesRoute
  AuthedFinanzasLoansRoute: typeof AuthedFinanzasLoansRoute
  AuthedFinanzasParticipantsRoute: typeof AuthedFinanzasParticipantsRoute
  AuthedFinanzasPayoutsRoute: typeof AuthedFinanzasPayoutsRoute
  AuthedFinanzasPersonalCreditsRoute: typeof AuthedFinanzasPersonalCreditsRouteWithChildren
  AuthedFinanzasProductionBalancesRoute: typeof AuthedFinanzasProductionBalancesRoute
  AuthedFinanzasStatisticsRoute: typeof AuthedFinanzasStatisticsRoute
  AuthedFinanzasIndexRoute: typeof AuthedFinanzasIndexRoute
}

const AuthedFinanzasRouteChildren: AuthedFinanzasRouteChildren = {
  AuthedFinanzasConciliacionesRoute: AuthedFinanzasConciliacionesRoute,
  AuthedFinanzasConciliacionesLiberacionesRoute:
    AuthedFinanzasConciliacionesLiberacionesRoute,
  AuthedFinanzasCounterpartsRoute: AuthedFinanzasCounterpartsRoute,
  AuthedFinanzasDailyRoute: AuthedFinanzasDailyRoute,
  AuthedFinanzasDashboardRoute: AuthedFinanzasDashboardRoute,
  AuthedFinanzasDteAnalyticsRoute: AuthedFinanzasDteAnalyticsRoute,
  AuthedFinanzasLiberacionesRoute: AuthedFinanzasLiberacionesRoute,
  AuthedFinanzasLoansRoute: AuthedFinanzasLoansRoute,
  AuthedFinanzasParticipantsRoute: AuthedFinanzasParticipantsRoute,
  AuthedFinanzasPayoutsRoute: AuthedFinanzasPayoutsRoute,
  AuthedFinanzasPersonalCreditsRoute:
    AuthedFinanzasPersonalCreditsRouteWithChildren,
  AuthedFinanzasProductionBalancesRoute: AuthedFinanzasProductionBalancesRoute,
  AuthedFinanzasStatisticsRoute: AuthedFinanzasStatisticsRoute,
  AuthedFinanzasIndexRoute: AuthedFinanzasIndexRoute,
}

const AuthedFinanzasRouteWithChildren = AuthedFinanzasRoute._addFileChildren(
  AuthedFinanzasRouteChildren,
)

interface AuthedHrRouteChildren {
  AuthedHrAuditRoute: typeof AuthedHrAuditRoute
  AuthedHrEmployeesRoute: typeof AuthedHrEmployeesRoute
  AuthedHrReportsRoute: typeof AuthedHrReportsRoute
  AuthedHrTimesheetsRoute: typeof AuthedHrTimesheetsRoute
  AuthedHrIndexRoute: typeof AuthedHrIndexRoute
}

const AuthedHrRouteChildren: AuthedHrRouteChildren = {
  AuthedHrAuditRoute: AuthedHrAuditRoute,
  AuthedHrEmployeesRoute: AuthedHrEmployeesRoute,
  AuthedHrReportsRoute: AuthedHrReportsRoute,
  AuthedHrTimesheetsRoute: AuthedHrTimesheetsRoute,
  AuthedHrIndexRoute: AuthedHrIndexRoute,
}

const AuthedHrRouteWithChildren = AuthedHrRoute._addFileChildren(
  AuthedHrRouteChildren,
)

interface AuthedOperationsRouteChildren {
  AuthedOperationsInventoryRoute: typeof AuthedOperationsInventoryRoute
  AuthedOperationsSuppliesRoute: typeof AuthedOperationsSuppliesRoute
  AuthedOperationsSuppliesAnalyticsRoute: typeof AuthedOperationsSuppliesAnalyticsRoute
}

const AuthedOperationsRouteChildren: AuthedOperationsRouteChildren = {
  AuthedOperationsInventoryRoute: AuthedOperationsInventoryRoute,
  AuthedOperationsSuppliesRoute: AuthedOperationsSuppliesRoute,
  AuthedOperationsSuppliesAnalyticsRoute:
    AuthedOperationsSuppliesAnalyticsRoute,
}

const AuthedOperationsRouteWithChildren =
  AuthedOperationsRoute._addFileChildren(AuthedOperationsRouteChildren)

interface AuthedServicesRouteChildren {
  AuthedServicesAgendaRoute: typeof AuthedServicesAgendaRoute
  AuthedServicesCreateRoute: typeof AuthedServicesCreateRoute
  AuthedServicesTemplatesRoute: typeof AuthedServicesTemplatesRoute
  AuthedServicesIndexRoute: typeof AuthedServicesIndexRoute
  AuthedServicesIdEditRoute: typeof AuthedServicesIdEditRoute
}

const AuthedServicesRouteChildren: AuthedServicesRouteChildren = {
  AuthedServicesAgendaRoute: AuthedServicesAgendaRoute,
  AuthedServicesCreateRoute: AuthedServicesCreateRoute,
  AuthedServicesTemplatesRoute: AuthedServicesTemplatesRoute,
  AuthedServicesIndexRoute: AuthedServicesIndexRoute,
  AuthedServicesIdEditRoute: AuthedServicesIdEditRoute,
}

const AuthedServicesRouteWithChildren = AuthedServicesRoute._addFileChildren(
  AuthedServicesRouteChildren,
)

interface AuthedSettingsUsersRouteChildren {
  AuthedSettingsUsersAddRoute: typeof AuthedSettingsUsersAddRoute
}

const AuthedSettingsUsersRouteChildren: AuthedSettingsUsersRouteChildren = {
  AuthedSettingsUsersAddRoute: AuthedSettingsUsersAddRoute,
}

const AuthedSettingsUsersRouteWithChildren =
  AuthedSettingsUsersRoute._addFileChildren(AuthedSettingsUsersRouteChildren)

interface AuthedSettingsRouteChildren {
  AuthedSettingsBackupsRoute: typeof AuthedSettingsBackupsRoute
  AuthedSettingsCsvUploadRoute: typeof AuthedSettingsCsvUploadRoute
  AuthedSettingsInventarioRoute: typeof AuthedSettingsInventarioRoute
  AuthedSettingsMercadopagoRoute: typeof AuthedSettingsMercadopagoRoute
  AuthedSettingsRolesRoute: typeof AuthedSettingsRolesRoute
  AuthedSettingsUsersRoute: typeof AuthedSettingsUsersRouteWithChildren
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsBackupsRoute: AuthedSettingsBackupsRoute,
  AuthedSettingsCsvUploadRoute: AuthedSettingsCsvUploadRoute,
  AuthedSettingsInventarioRoute: AuthedSettingsInventarioRoute,
  AuthedSettingsMercadopagoRoute: AuthedSettingsMercadopagoRoute,
  AuthedSettingsRolesRoute: AuthedSettingsRolesRoute,
  AuthedSettingsUsersRoute: AuthedSettingsUsersRouteWithChildren,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedCalendarRoute: typeof AuthedCalendarRouteWithChildren
  AuthedCertificatesRoute: typeof AuthedCertificatesRouteWithChildren
  AuthedFinanzasRoute: typeof AuthedFinanzasRouteWithChildren
  AuthedHrRoute: typeof AuthedHrRouteWithChildren
  AuthedOperationsRoute: typeof AuthedOperationsRouteWithChildren
  AuthedServicesRoute: typeof AuthedServicesRouteWithChildren
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedDevRoutesAuditRoute: typeof AuthedDevRoutesAuditRoute
  AuthedPatientsNewRoute: typeof AuthedPatientsNewRoute
  AuthedPatientsIndexRoute: typeof AuthedPatientsIndexRoute
  AuthedPatientsIdNewBudgetRoute: typeof AuthedPatientsIdNewBudgetRoute
  AuthedPatientsIdNewConsultationRoute: typeof AuthedPatientsIdNewConsultationRoute
  AuthedPatientsIdNewPaymentRoute: typeof AuthedPatientsIdNewPaymentRoute
  AuthedPatientsIdIndexRoute: typeof AuthedPatientsIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedCalendarRoute: AuthedCalendarRouteWithChildren,
  AuthedCertificatesRoute: AuthedCertificatesRouteWithChildren,
  AuthedFinanzasRoute: AuthedFinanzasRouteWithChildren,
  AuthedHrRoute: AuthedHrRouteWithChildren,
  AuthedOperationsRoute: AuthedOperationsRouteWithChildren,
  AuthedServicesRoute: AuthedServicesRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedDevRoutesAuditRoute: AuthedDevRoutesAuditRoute,
  AuthedPatientsNewRoute: AuthedPatientsNewRoute,
  AuthedPatientsIndexRoute: AuthedPatientsIndexRoute,
  AuthedPatientsIdNewBudgetRoute: AuthedPatientsIdNewBudgetRoute,
  AuthedPatientsIdNewConsultationRoute: AuthedPatientsIdNewConsultationRoute,
  AuthedPatientsIdNewPaymentRoute: AuthedPatientsIdNewPaymentRoute,
  AuthedPatientsIdIndexRoute: AuthedPatientsIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  VerifyIdRoute: VerifyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
