//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import { type ModelResult as $ModelResult } from "@zenstackhq/orm";
export type Person = $ModelResult<$Schema, "Person">;
export type User = $ModelResult<$Schema, "User">;
export type Role = $ModelResult<$Schema, "Role">;
export type Permission = $ModelResult<$Schema, "Permission">;
export type RolePermission = $ModelResult<$Schema, "RolePermission">;
export type UserRoleAssignment = $ModelResult<$Schema, "UserRoleAssignment">;
export type UserPermissionVersion = $ModelResult<$Schema, "UserPermissionVersion">;
export type Employee = $ModelResult<$Schema, "Employee">;
export type Counterpart = $ModelResult<$Schema, "Counterpart">;
export type CounterpartAccount = $ModelResult<$Schema, "CounterpartAccount">;
export type EmployeeTimesheet = $ModelResult<$Schema, "EmployeeTimesheet">;
export type Transaction = $ModelResult<$Schema, "Transaction">;
export type DailyBalance = $ModelResult<$Schema, "DailyBalance">;
export type Service = $ModelResult<$Schema, "Service">;
export type Loan = $ModelResult<$Schema, "Loan">;
export type LoanSchedule = $ModelResult<$Schema, "LoanSchedule">;
export type AuditLog = $ModelResult<$Schema, "AuditLog">;
export type Setting = $ModelResult<$Schema, "Setting">;
export type PushSubscription = $ModelResult<$Schema, "PushSubscription">;
export type Calendar = $ModelResult<$Schema, "Calendar">;
export type CalendarWatchChannel = $ModelResult<$Schema, "CalendarWatchChannel">;
export type Event = $ModelResult<$Schema, "Event">;
export type SyncLog = $ModelResult<$Schema, "SyncLog">;
export type BackupLog = $ModelResult<$Schema, "BackupLog">;
export type InventoryCategory = $ModelResult<$Schema, "InventoryCategory">;
export type InventoryItem = $ModelResult<$Schema, "InventoryItem">;
export type InventoryMovement = $ModelResult<$Schema, "InventoryMovement">;
export type DailyProductionBalance = $ModelResult<$Schema, "DailyProductionBalance">;
export type SupplyRequest = $ModelResult<$Schema, "SupplyRequest">;
export type CommonSupply = $ModelResult<$Schema, "CommonSupply">;
export const PersonType = $schema.enums.PersonType.values;
export type PersonType = (typeof PersonType)[keyof typeof PersonType];
export const CounterpartCategory = $schema.enums.CounterpartCategory.values;
export type CounterpartCategory = (typeof CounterpartCategory)[keyof typeof CounterpartCategory];
export const EmployeeStatus = $schema.enums.EmployeeStatus.values;
export type EmployeeStatus = (typeof EmployeeStatus)[keyof typeof EmployeeStatus];
export const EmployeeSalaryType = $schema.enums.EmployeeSalaryType.values;
export type EmployeeSalaryType = (typeof EmployeeSalaryType)[keyof typeof EmployeeSalaryType];
export const TransactionDirection = $schema.enums.TransactionDirection.values;
export type TransactionDirection = (typeof TransactionDirection)[keyof typeof TransactionDirection];
export const ServiceType = $schema.enums.ServiceType.values;
export type ServiceType = (typeof ServiceType)[keyof typeof ServiceType];
export const ServiceFrequency = $schema.enums.ServiceFrequency.values;
export type ServiceFrequency = (typeof ServiceFrequency)[keyof typeof ServiceFrequency];
export const ServiceStatus = $schema.enums.ServiceStatus.values;
export type ServiceStatus = (typeof ServiceStatus)[keyof typeof ServiceStatus];
export const LoanStatus = $schema.enums.LoanStatus.values;
export type LoanStatus = (typeof LoanStatus)[keyof typeof LoanStatus];
export const LoanScheduleStatus = $schema.enums.LoanScheduleStatus.values;
export type LoanScheduleStatus = (typeof LoanScheduleStatus)[keyof typeof LoanScheduleStatus];
export const UserStatus = $schema.enums.UserStatus.values;
export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus];
